//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.64.2.0.0
//
#ifndef MTL4RenderCommandEncoderGGDSPI_Protocol_h
#define MTL4RenderCommandEncoderGGDSPI_Protocol_h
@import Foundation;

#include "MTL4CommandEncoderGGDSPI-Protocol.h"
#include "MTL4RenderCommandEncoderSPI-Protocol.h"

@protocol MTL4RenderCommandEncoderGGDSPI <MTL4RenderCommandEncoderSPI, MTL4CommandEncoderGGDSPI>

@required

/* required instance methods */
- (void)setDepthClipModeSPI:(unsigned long long)spi;
- (void)setCommandDataCorruptModeSPI:(unsigned long long)spi;
- (signed char)isMemorylessRender;
- (void)dispatchThreadsPerTile:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })tile inRegion:(struct { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x0; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x1; })region;
- (void)dispatchThreadsPerTile:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })tile inRegion:(struct { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x0; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x1; })region withRenderTargetArrayIndex:(unsigned int)index;
- (void)setVertexAmplificationMode:(unsigned long long)mode value:(unsigned long long)value;

@optional

@end

#endif /* MTL4RenderCommandEncoderGGDSPI_Protocol_h */
