//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.64.2.0.0
//
#ifndef MTLArgumentInternal_h
#define MTLArgumentInternal_h
@import Foundation;

#include "MTLBindingInternal.h"

@interface MTLArgumentInternal :  {
    /* instance variables */
    MTLBindingInternal *_binding;
}

/* instance methods */
- (id)initWithBinding:(id)binding;
- (void)dealloc;

@end

#endif /* MTLArgumentInternal_h */
