//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.64.2.0.0
//
#ifndef MTLBlitPassDescriptorInternal_h
#define MTLBlitPassDescriptorInternal_h
@import Foundation;

#include "MTLBlitPassSampleBufferAttachmentDescriptorArrayInternal.h"

@interface MTLBlitPassDescriptorInternal :  {
    /* instance variables */
    struct MTLBlitPassDescriptorPrivate { MTLBlitPassSampleBufferAttachmentDescriptorArrayInternal *sampleBufferAttachments; } _private;
}

/* class methods */
+ (id)blitPassDescriptor;

/* instance methods */
- (id)init;
- (void)dealloc;
- (unsigned long long)hash;
- (signed char)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (const struct MTLBlitPassDescriptorPrivate { id x0; } *)_descriptorPrivate;
- (id)sampleBufferAttachments;

@end

#endif /* MTLBlitPassDescriptorInternal_h */
