//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.64.2.0.0
//
#ifndef MTLComputePassDescriptorInternal_h
#define MTLComputePassDescriptorInternal_h
@import Foundation;

#include "MTLComputePassSampleBufferAttachmentDescriptorArrayInternal.h"

@interface MTLComputePassDescriptorInternal :  {
    /* instance variables */
    struct MTLComputePassDescriptorPrivate { unsigned long long dispatchType; MTLComputePassSampleBufferAttachmentDescriptorArrayInternal *sampleBufferAttachments; unsigned int substreamCount; signed char allowCommandEncoderCoalescing; signed char usedForRaytracingEmulation; } _private;
}

@property (nonatomic) unsigned int substreamCount;
@property (nonatomic) signed char allowCommandEncoderCoalescing;
@property (nonatomic) signed char usedForRaytracingEmulation;

/* class methods */
+ (id)computePassDescriptor;

/* instance methods */
- (id)init;
- (void)dealloc;
- (unsigned long long)hash;
- (signed char)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (const struct MTLComputePassDescriptorPrivate { unsigned long long x0; id x1; unsigned int x2; signed char x3; signed char x4; } *)_descriptorPrivate;
- (id)sampleBufferAttachments;
- (unsigned long long)dispatchType;
- (void)setDispatchType:(unsigned long long)type;

@end

#endif /* MTLComputePassDescriptorInternal_h */
