//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.64.2.0.0
//
#ifndef MTLDepthStencilStateSPI_Protocol_h
#define MTLDepthStencilStateSPI_Protocol_h
@import Foundation;

#include "MTLDepthStencilState-Protocol.h"

@protocol MTLDepthStencilStateSPI <MTLDepthStencilState>

@required

@property (readonly) signed char readsDepth;
@property (readonly) signed char writesDepth;
@property (readonly) signed char readsStencil;
@property (readonly) signed char writesStencil;
@property (readonly) unsigned long long uniqueIdentifier;
@property (readonly, nonatomic) unsigned long long resourceIndex;

@optional

@end

#endif /* MTLDepthStencilStateSPI_Protocol_h */
