//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.64.2.0.0
//
#ifndef MTLEvent_Protocol_h
#define MTLEvent_Protocol_h
@import Foundation;

#include "MTLDevice-Protocol.h"
#include "NSObject-Protocol.h"

@class NSString;

@protocol MTLEvent <NSObject>

@required

@property (readonly) id <MTLDevice> device;
@property (copy) NSString *label;

@optional

@end

#endif /* MTLEvent_Protocol_h */
