//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.64.2.0.0
//
#ifndef MTLIntersectionFunctionTableSPI_Protocol_h
#define MTLIntersectionFunctionTableSPI_Protocol_h
@import Foundation;

#include "MTLBuffer-Protocol.h"
#include "MTLIntersectionFunctionTable-Protocol.h"

@protocol MTLIntersectionFunctionTableSPI <MTLIntersectionFunctionTable>

@required

@property (readonly) unsigned long long gpuHandle;

/* required instance methods */
- (unsigned long long)bufferAddressAtIndex:(unsigned long long)index;

@optional

@property (readonly, nonatomic) unsigned long long resourceIndex;
@property (readonly) unsigned long long uniqueIdentifier;
@property (retain, nonatomic) id <MTLBuffer> globalBuffer;
@property (nonatomic) unsigned long long globalBufferOffset;

@end

#endif /* MTLIntersectionFunctionTableSPI_Protocol_h */
