//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.64.2.0.0
//
#ifndef MTLIndirectRenderCommand_Protocol_h
#define MTLIndirectRenderCommand_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol MTLIndirectRenderCommand <NSObject>

@required

/* required instance methods */
- (void)setRenderPipelineState:(id)state;
- (void)setVertexBuffer:(id)buffer offset:(unsigned long long)offset atIndex:(unsigned long long)index;
- (void)setFragmentBuffer:(id)buffer offset:(unsigned long long)offset atIndex:(unsigned long long)index;
- (void)setVertexBuffer:(id)buffer offset:(unsigned long long)offset attributeStride:(unsigned long long)stride atIndex:(unsigned long long)index;
- (void)drawPatches:(unsigned long long)patches patchStart:(unsigned long long)start patchCount:(unsigned long long)count patchIndexBuffer:(id)buffer patchIndexBufferOffset:(unsigned long long)offset instanceCount:(unsigned long long)count baseInstance:(unsigned long long)instance tessellationFactorBuffer:(id)buffer tessellationFactorBufferOffset:(unsigned long long)offset tessellationFactorBufferInstanceStride:(unsigned long long)stride;
- (void)drawIndexedPatches:(unsigned long long)patches patchStart:(unsigned long long)start patchCount:(unsigned long long)count patchIndexBuffer:(id)buffer patchIndexBufferOffset:(unsigned long long)offset controlPointIndexBuffer:(id)buffer controlPointIndexBufferOffset:(unsigned long long)offset instanceCount:(unsigned long long)count baseInstance:(unsigned long long)instance tessellationFactorBuffer:(id)buffer tessellationFactorBufferOffset:(unsigned long long)offset tessellationFactorBufferInstanceStride:(unsigned long long)stride;
- (void)drawPrimitives:(unsigned long long)primitives vertexStart:(unsigned long long)start vertexCount:(unsigned long long)count instanceCount:(unsigned long long)count baseInstance:(unsigned long long)instance;
- (void)drawIndexedPrimitives:(unsigned long long)primitives indexCount:(unsigned long long)count indexType:(unsigned long long)type indexBuffer:(id)buffer indexBufferOffset:(unsigned long long)offset instanceCount:(unsigned long long)count baseVertex:(long long)vertex baseInstance:(unsigned long long)instance;
- (void)setObjectThreadgroupMemoryLength:(unsigned long long)length atIndex:(unsigned long long)index;
- (void)setObjectBuffer:(id)buffer offset:(unsigned long long)offset atIndex:(unsigned long long)index;
- (void)setMeshBuffer:(id)buffer offset:(unsigned long long)offset atIndex:(unsigned long long)index;
- (void)drawMeshThreadgroups:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroups threadsPerObjectThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup threadsPerMeshThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup;
- (void)drawMeshThreads:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threads threadsPerObjectThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup threadsPerMeshThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup;
- (void)setBarrier;
- (void)clearBarrier;
- (void)setDepthStencilState:(id)state;
- (void)setDepthBias:(float)bias slopeScale:(float)scale clamp:(float)clamp;
- (void)setDepthClipMode:(unsigned long long)mode;
- (void)setCullMode:(unsigned long long)mode;
- (void)setFrontFacingWinding:(unsigned long long)winding;
- (void)setTriangleFillMode:(unsigned long long)mode;
- (void)reset;

@optional

@end

#endif /* MTLIndirectRenderCommand_Protocol_h */
