//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.64.2.0.0
//
#ifndef MTLLoadedFile_h
#define MTLLoadedFile_h
@import Foundation;

@class NSData, NSObject;

@interface MTLLoadedFile : NSObject {
    /* instance variables */
    NSData *_fileData;
    void * _parent;
    long long _modifiedTimeWhenCached;
    struct FileIdentifier { int dev; unsigned long long ino; } _identity;
    _Bool _isCached;
}

@property (readonly) NSData *contents;

/* instance methods */
- (id)initWithData:(id)data parent:(void *)parent;
- (void)dealloc;

@end

#endif /* MTLLoadedFile_h */
