//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.64.2.0.0
//
#ifndef MTLObjectPayloadBindingInternal_h
#define MTLObjectPayloadBindingInternal_h
@import Foundation;

#include "MTLBindingInternal.h"
#include "MTLObjectPayloadBinding-Protocol.h"

@class NSString;

@interface MTLObjectPayloadBindingInternal : MTLBindingInternal <MTLObjectPayloadBinding> {
    /* instance variables */
    unsigned short _alignment;
    unsigned int _dataSize;
    unsigned long long _dataType;
}

@property (readonly) unsigned long long objectPayloadAlignment;
@property (readonly) unsigned long long objectPayloadDataSize;
@property (readonly) NSString *name;
@property (readonly) long long type;
@property (readonly) unsigned long long access;
@property (readonly) unsigned long long index;
@property (readonly) signed char used;
@property (readonly) signed char argument;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithName:(id)name type:(unsigned long long)type access:(unsigned long long)access isActive:(signed char)active arraySize:(unsigned long long)size dataType:(unsigned long long)type dataSize:(unsigned long long)size alignment:(unsigned long long)alignment;
- (id)initWithName:(id)name type:(unsigned long long)type access:(unsigned long long)access isActive:(signed char)active locationIndex:(unsigned long long)index arraySize:(unsigned long long)size dataType:(unsigned long long)type dataSize:(unsigned long long)size alignment:(unsigned long long)alignment;
- (unsigned long long)objectPayloadDataType;
- (id)objectPayloadStructType;
- (id)structType;
- (void)setStructType:(id)type doRetain:(signed char)retain;
- (void)setStructType:(id)type;
- (id)formattedDescription:(unsigned long long)description;
- (signed char)isEqual:(id)equal;

@end

#endif /* MTLObjectPayloadBindingInternal_h */
