//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.64.2.0.0
//
#ifndef MTLRenderPipelineState_Protocol_h
#define MTLRenderPipelineState_Protocol_h
@import Foundation;

#include "MTLAllocation-Protocol.h"
#include "MTLDevice-Protocol.h"
#include "MTLRenderPipelineReflection.h"
#include "NSObject-Protocol.h"

@class NSString;

@protocol MTLRenderPipelineState <MTLAllocation, NSObject>

@required

@property (readonly) NSString *label;
@property (readonly) id <MTLDevice> device;
@property (readonly) MTLRenderPipelineReflection *reflection;
@property (readonly) unsigned long long maxTotalThreadsPerThreadgroup;
@property (readonly) signed char threadgroupSizeMatchesTileSize;
@property (readonly) unsigned long long imageblockSampleLength;
@property (readonly) signed char supportIndirectCommandBuffers;
@property (readonly) unsigned long long maxTotalThreadsPerObjectThreadgroup;
@property (readonly) unsigned long long maxTotalThreadsPerMeshThreadgroup;
@property (readonly) unsigned long long objectThreadExecutionWidth;
@property (readonly) unsigned long long meshThreadExecutionWidth;
@property (readonly) unsigned long long maxTotalThreadgroupsPerMeshGrid;
@property (readonly) struct MTLResourceID { unsigned long long x0; } gpuResourceID;
@property (readonly, nonatomic) long long shaderValidation;
@property (readonly) struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } requiredThreadsPerTileThreadgroup;
@property (readonly) struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } requiredThreadsPerObjectThreadgroup;
@property (readonly) struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } requiredThreadsPerMeshThreadgroup;

/* required instance methods */
- (id)functionHandleWithName:(id)name stage:(unsigned long long)stage;
- (id)functionHandleWithBinaryFunction:(id)function stage:(unsigned long long)stage;
- (id)newRenderPipelineStateWithBinaryFunctions:(id)functions error:(id *)error;
- (id)newRenderPipelineDescriptorForSpecialization;
- (unsigned long long)imageblockMemoryLengthForDimensions:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })dimensions;
- (id)functionHandleWithFunction:(id)function stage:(unsigned long long)stage;
- (id)newVisibleFunctionTableWithDescriptor:(id)descriptor stage:(unsigned long long)stage;
- (id)newIntersectionFunctionTableWithDescriptor:(id)descriptor stage:(unsigned long long)stage;
- (id)newRenderPipelineStateWithAdditionalBinaryFunctions:(id)functions error:(id *)error;

@optional

@end

#endif /* MTLRenderPipelineState_Protocol_h */
