//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.64.2.0.0
//
#ifndef MTLSamplerStateSPI_Protocol_h
#define MTLSamplerStateSPI_Protocol_h
@import Foundation;

#include "MTLSamplerState-Protocol.h"

@protocol MTLSamplerStateSPI <MTLSamplerState>

@required

@property (readonly, nonatomic) unsigned long long pixelFormat;

@optional

@property (readonly, nonatomic) unsigned long long resourceIndex;
@property (readonly, nonatomic) unsigned long long gpuAddress;
@property (readonly) unsigned long long uniqueIdentifier;
@property (readonly) unsigned long long gpuHandle;

@end

#endif /* MTLSamplerStateSPI_Protocol_h */
