//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.64.2.0.0
//
#ifndef MTLTextureBinding_Protocol_h
#define MTLTextureBinding_Protocol_h
@import Foundation;

#include "MTLBinding-Protocol.h"

@protocol MTLTextureBinding <MTLBinding>

@required

@property (readonly) unsigned long long textureType;
@property (readonly) unsigned long long textureDataType;
@property (readonly) signed char depthTexture;
@property (readonly) unsigned long long arrayLength;

/* required instance methods */
- (signed char)isDepthTexture;

@optional

@end

#endif /* MTLTextureBinding_Protocol_h */
