//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.64.2.0.0
//
#ifndef MTLTextureViewPool_Protocol_h
#define MTLTextureViewPool_Protocol_h
@import Foundation;

#include "MTLResourceViewPool-Protocol.h"

@protocol MTLTextureViewPool <MTLResourceViewPool>

@required

/* required instance methods */
- (struct MTLResourceID { unsigned long long x0; })setTextureView:(id)view atIndex:(unsigned long long)index;
- (struct MTLResourceID { unsigned long long x0; })setTextureView:(id)view descriptor:(id)descriptor atIndex:(unsigned long long)index;
- (struct MTLResourceID { unsigned long long x0; })setTextureViewFromBuffer:(id)buffer descriptor:(id)descriptor offset:(unsigned long long)offset bytesPerRow:(unsigned long long)row atIndex:(unsigned long long)index;

@optional

@end

#endif /* MTLTextureViewPool_Protocol_h */
