//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.64.2.0.0
//
#ifndef NSError_MTLCaptureError_h
#define NSError_MTLCaptureError_h
@import Foundation;

@interface NSError (MTLCaptureError)

/* class methods */
+ (id)errorWithMTLCaptureErrorCode:(long long)code;

/* instance methods */
- (id)initWithIOAccelError:(long long)error;

@end

#endif /* NSError_MTLCaptureError_h */
