//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1216.1)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 29, SDK: 29, Tool: ld (1216.1)
//    - LC_SOURCE_VERSION: 370.50.5.0.0
//
#ifndef _MTL4CommandBufferRetainData_h
#define _MTL4CommandBufferRetainData_h
@import Foundation;

#include "MTLBuffer-Protocol.h"
#include "MTLLogState-Protocol.h"

@class NSObject;

@interface _MTL4CommandBufferRetainData : NSObject

@property (retain, nonatomic) id <MTLLogState> logState;
@property (retain, nonatomic) id <MTLBuffer> privateData;
@property (nonatomic) unsigned long long privateDataOffset;

/* instance methods */
- (id)init;
- (void)dealloc;

@end

#endif /* _MTL4CommandBufferRetainData_h */
