//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1216.1)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 29, SDK: 29, Tool: ld (1216.1)
//    - LC_SOURCE_VERSION: 370.50.5.0.0
//
#ifndef MTL4ArgumentTable_Protocol_h
#define MTL4ArgumentTable_Protocol_h
@import Foundation;

#include "MTLDevice-Protocol.h"
#include "NSObject-Protocol.h"

@class NSString;

@protocol MTL4ArgumentTable <NSObject>

@required

@property (readonly) id <MTLDevice> device;
@property (readonly, nonatomic) NSString *label;

/* required instance methods */
- (void)setAddress:(unsigned long long)address atIndex:(unsigned long long)index;
- (void)setAddress:(unsigned long long)address attributeStride:(unsigned long long)stride atIndex:(unsigned long long)index;
- (void)setResource:(struct MTLResourceID { unsigned long long x0; })resource atBufferIndex:(unsigned long long)index;
- (void)setTexture:(struct MTLResourceID { unsigned long long x0; })texture atIndex:(unsigned long long)index;
- (void)setSamplerState:(struct MTLResourceID { unsigned long long x0; })state atIndex:(unsigned long long)index;

@optional

@end

#endif /* MTL4ArgumentTable_Protocol_h */
