//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1216.1)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 29, SDK: 29, Tool: ld (1216.1)
//    - LC_SOURCE_VERSION: 370.50.5.0.0
//
#ifndef MTL4CompilerGGDSPI_Protocol_h
#define MTL4CompilerGGDSPI_Protocol_h
@import Foundation;

#include "MTL4CompilerSPI-Protocol.h"
#include "MTLBinaryArchive-Protocol.h"

@protocol MTL4CompilerGGDSPI <MTL4CompilerSPI>

@required

@property (readonly) id <MTLBinaryArchive> destinationBinaryArchive;
@property (readonly) signed char shouldMaximizeConcurrentCompilation;

/* required instance methods */
- (id)newDynamicLibraryWithURL:(id)url options:(unsigned long long)options error:(id *)error;
- (id)newDynamicLibraryWithURL:(id)url options:(unsigned long long)options completionHandler:(id /* block */)handler;

@optional

@end

#endif /* MTL4CompilerGGDSPI_Protocol_h */
