//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1216.1)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 29, SDK: 29, Tool: ld (1216.1)
//    - LC_SOURCE_VERSION: 370.50.5.0.0
//
#ifndef MTL4ArgumentTableGGDSPI_Protocol_h
#define MTL4ArgumentTableGGDSPI_Protocol_h
@import Foundation;

#include "MTL4ArgumentTableSPI-Protocol.h"

@protocol MTL4ArgumentTableGGDSPI <MTL4ArgumentTableSPI>

@required

/* required instance methods */
- (unsigned long long)bufferBindingCount;
- (unsigned long long)textureBindingCount;
- (unsigned long long)samplerBindingCount;
- (void)getBufferBindings:(struct MTLResourceID { unsigned long long x0; } *)bindings bindingCount:(unsigned long long)count;
- (void)getTextureBindings:(struct MTLResourceID { unsigned long long x0; } *)bindings bindingCount:(unsigned long long)count;

@optional

@end

#endif /* MTL4ArgumentTableGGDSPI_Protocol_h */
