//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1216.1)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 29, SDK: 29, Tool: ld (1216.1)
//    - LC_SOURCE_VERSION: 370.50.5.0.0
//
#ifndef MTLBufferBindingInternal_h
#define MTLBufferBindingInternal_h
@import Foundation;

#include "MTLBindingInternal.h"
#include "MTLBufferBinding-Protocol.h"
#include "MTLPointerType.h"
#include "MTLStructType.h"

@class NSString;

@interface MTLBufferBindingInternal : MTLBindingInternal <MTLBufferBinding> {
    /* instance variables */
    unsigned int _dataType:15;
    unsigned int _vertexDescriptorBuffer:1;
    unsigned short _alignment;
    unsigned int _dataSize;
    unsigned long long _pixelFormat;
    unsigned long long _aluType;
}

@property (readonly) unsigned long long bufferAlignment;
@property (readonly) unsigned long long bufferDataSize;
@property (readonly) unsigned long long bufferDataType;
@property (readonly) MTLStructType *bufferStructType;
@property (readonly) MTLPointerType *bufferPointerType;
@property (readonly) NSString *name;
@property (readonly) long long type;
@property (readonly) unsigned long long access;
@property (readonly) unsigned long long index;
@property (readonly) signed char used;
@property (readonly) signed char argument;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithName:(id)name type:(unsigned long long)type access:(unsigned long long)access isActive:(signed char)active locationIndex:(unsigned long long)index arraySize:(unsigned long long)size dataType:(unsigned long long)type pixelFormat:(unsigned long long)format aluType:(unsigned long long)type isConstantBuffer:(signed char)buffer dataSize:(unsigned long long)size alignment:(unsigned long long)alignment;
- (void)dealloc;
- (void)setDataSize:(unsigned long long)size;
- (void)setAlignment:(unsigned long long)alignment;
- (void)setVertexDescriptorBuffer:(signed char)buffer;
- (signed char)isVertexDescriptorBuffer;
- (void)setStructType:(id)type doRetain:(signed char)retain;
- (void)setStructType:(id)type;
- (unsigned long long)bufferPixelFormat;
- (unsigned long long)bufferALUType;
- (id)structType;
- (id)bufferIndirectArgumentType;
- (id)formattedDescription:(unsigned long long)description;
- (signed char)isEqual:(id)equal;

@end

#endif /* MTLBufferBindingInternal_h */
