//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1216.1)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 29, SDK: 29, Tool: ld (1216.1)
//    - LC_SOURCE_VERSION: 370.50.5.0.0
//
#ifndef MTLResourceSPI_Protocol_h
#define MTLResourceSPI_Protocol_h
@import Foundation;

#include "MTLResource-Protocol.h"

@protocol MTLResourceSPI <MTLResource>

@required

@property int responsibleProcess;
@property (readonly) unsigned long long allocationID;
@property (readonly) unsigned long long protectionOptions;
@property (readonly) unsigned long long unfilteredResourceOptions;

/* required instance methods */
- (signed char)isPurgeable;
- (signed char)isComplete;
- (void)waitUntilComplete;
- (signed char)isWriteComplete;
- (signed char)doesAliasResource:(id)resource;
- (signed char)doesAliasAllResources:(const id *)resources count:(unsigned long long)count;
- (signed char)doesAliasAnyResources:(const id *)resources count:(unsigned long long)count;

@optional

/* optional instance methods */
- (int)setOwnerWithIdentity:(unsigned int)identity;

@end

#endif /* MTLResourceSPI_Protocol_h */
