//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1216.1)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 29, SDK: 29, Tool: ld (1216.1)
//    - LC_SOURCE_VERSION: 370.50.5.0.0
//
#ifndef MTLStructTypeInternal_h
#define MTLStructTypeInternal_h
@import Foundation;

@class NSArray, NSDictionary, NSString;

@interface MTLStructTypeInternal :  {
    /* instance variables */
    unsigned long long _dataType;
    NSDictionary *_dictionary;
    NSArray *_members;
}

@property signed char isIndirectArgumentBuffer;
@property (readonly) NSString *typeName;

/* instance methods */
- (id)initWithMembers:(id *)members count:(unsigned long long)count;
- (id)initWithMembers:(id *)members count:(unsigned long long)count typeName:(id)name;
- (id)init;
- (void)setMembers:(id *)members count:(unsigned long long)count;
- (id)memberByName:(id)name;
- (void)dealloc;
- (id)formattedDescription:(unsigned long long)description withPrintedTypes:(id)types;
- (id)description;
- (id)members;
- (_Bool)isStructLayoutThreadSafeWith:(id)with;
- (signed char)isEqual:(id)equal;
- (unsigned long long)dataType;

@end

#endif /* MTLStructTypeInternal_h */
