//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1216.1)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 29, SDK: 29, Tool: ld (1216.1)
//    - LC_SOURCE_VERSION: 370.50.5.0.0
//
#ifndef MTLTensorBinding_Protocol_h
#define MTLTensorBinding_Protocol_h
@import Foundation;

#include "MTLBinding-Protocol.h"
#include "MTLTensorExtents.h"

@protocol MTLTensorBinding <MTLBinding>

@required

@property (readonly) long long tensorDataType;
@property (readonly) unsigned long long indexType;
@property (readonly) MTLTensorExtents *dimensions;

@optional

@end

#endif /* MTLTensorBinding_Protocol_h */
