//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1216.1)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 29, SDK: 29, Tool: ld (1216.1)
//    - LC_SOURCE_VERSION: 370.50.5.0.0
//
#ifndef MTLTensor_Protocol_h
#define MTLTensor_Protocol_h
@import Foundation;

#include "MTLBuffer-Protocol.h"
#include "MTLResource-Protocol.h"
#include "MTLTensorExtents.h"

@protocol MTLTensor <MTLResource>

@required

@property (readonly) struct MTLResourceID { unsigned long long x0; } gpuResourceID;
@property (readonly) id <MTLBuffer> buffer;
@property (readonly) unsigned long long bufferOffset;
@property (readonly) MTLTensorExtents *strides;
@property (readonly) MTLTensorExtents *dimensions;
@property (readonly) long long dataType;
@property (readonly) long long usage;

/* required instance methods */
- (void)replaceSliceOrigin:(id)origin sliceDimensions:(id)dimensions withBytes:(const void *)bytes strides:(id)strides;
- (void)getBytes:(void *)bytes strides:(id)strides fromSliceOrigin:(id)origin sliceDimensions:(id)dimensions;

@optional

@end

#endif /* MTLTensor_Protocol_h */
