//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1216.1)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 29, SDK: 29, Tool: ld (1216.1)
//    - LC_SOURCE_VERSION: 370.50.5.0.0
//
#ifndef NSObject_Protocol_h
#define NSObject_Protocol_h
@import Foundation;

@class NSString;

@protocol NSObject

@required

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;

/* required instance methods */
- (signed char)isEqual:(id)equal;
- (Class)class;
- (id)self;
- (id)performSelector:(SEL)selector;
- (id)performSelector:(SEL)selector withObject:(id)object;
- (id)performSelector:(SEL)selector withObject:(id)object withObject:(id)object;
- (signed char)isProxy;
- (signed char)isKindOfClass:(Class)_class;
- (signed char)isMemberOfClass:(Class)_class;
- (signed char)conformsToProtocol:(id)protocol;
- (signed char)respondsToSelector:(SEL)selector;
- (id)retain;
- (oneway void)release;
- (id)autorelease;
- (unsigned long long)retainCount;
- (struct _NSZone *)zone;

@optional

@property (readonly, copy) NSString *debugDescription;

@end

#endif /* NSObject_Protocol_h */
