//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.7, SDK: 13.7, Tool: ld (857.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 16.6, SDK: 16.6, Tool: ld (857.2)
//    - LC_SOURCE_VERSION: 306.7.5.0.0
//
#ifndef _MTLFunctionInternal_h
#define _MTLFunctionInternal_h
@import Foundation;

#include "MTLFunctionConstantValuesInternal.h"

@class NSData, NSObject, NSString;
@protocol OS_dispatch_data, OS_dispatch_queue;

@interface _MTLFunctionInternal :  {
    /* instance variables */
    struct MTLFunctionData { unsigned long long bitCodeOffset; unsigned long long bitCodeFileSize; unsigned long long publicArgumentsOffset; unsigned long long privateArgumentsOffset; unsigned long long sourceArchiveOffset; unsigned short airMajorVersion; unsigned short airMinorVersion; unsigned short languageMajorVersion; unsigned short languageMinorVersion; struct { unsigned char key[32]; } bitcodeHash; unsigned char bitcodeType; NSData *pluginData; unsigned char renderTargetArrayIndexType; unsigned int patchType:2; unsigned int controlPointCount:6; NSObject<OS_dispatch_data> *functionInputs; struct { unsigned char key[32]; } baseFunctionHash; NSObject<OS_dispatch_data> *specializationAirScript; } _functionData;
    unsigned char _publicMetadataInitialized;
    unsigned char _privateMetadataInitialized;
    unsigned char _sourceArchiveMetadataInitialized;
    unsigned char _stitchableFunctionMetadataInitialized;
    void * _programObject;
    NSString *_filePath;
    long long _lineNumber;
    NSObject<OS_dispatch_queue> *_functionQueue;
    NSString *_baseLibraryFilePath;
    struct { unsigned char key[32]; } _baseLibraryUUID;
    MTLFunctionConstantValuesInternal *_baseFunctionConstantValues;
}

/* instance methods */
- (id)initWithName:(id)name type:(unsigned long long)type libraryData:(struct MTLLibraryData { void * /* function */ *x0; struct { unsigned char x0[32]; } x1; _Atomic int x2; id x3; id x4; } *)data functionData:(struct MTLFunctionData { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; unsigned short x5; unsigned short x6; unsigned short x7; unsigned short x8; struct { unsigned char x0[32]; } x9; unsigned char x10; id x11; unsigned char x12; unsigned int x13:2; unsigned int x14:6; id x15; struct { unsigned char x0[32]; } x16; id x17; } *)data device:(id)device;
- (id)specializationAirScript;
- (id)baseLibraryFilePath;
- (struct { unsigned char x0[32]; })baseLibraryUUID;
- (id)baseFunctionConstantValues;
- (void)dealloc;
- (void *)programObject;
- (const struct MTLFunctionData { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; unsigned short x5; unsigned short x6; unsigned short x7; unsigned short x8; struct { unsigned char x0[32]; } x9; unsigned char x10; id x11; unsigned char x12; unsigned int x13:2; unsigned int x14:6; id x15; struct { unsigned char x0[32]; } x16; id x17; } *)functionData;
- (id)importedSymbols;
- (id)importedLibraries;
- (unsigned long long)bitCodeOffset;
- (unsigned char)bitcodeType;
- (void)setBitcodeType:(unsigned char)type;
- (id)pluginData;
- (void)setPluginData:(id)data;
- (unsigned long long)patchType;
- (long long)patchControlPointCount;
- (void)initializePublicMetadata;
- (void)initializeStitchableFunctionMetadata;
- (id)vertexAttributes;
- (void)setVertexAttributes:(id)attributes;
- (void)setReturnType:(id)type;
- (id)returnType;
- (void)setArguments:(id)arguments;
- (id)arguments;
- (void)setPrecompiledOutput:(id)output;
- (id)precompiledOutput;
- (id)stageInputAttributes;
- (void)setStageInputAttributes:(id)attributes;
- (signed char)needsFunctionConstantValues;
- (id)functionConstants;
- (void)setFunctionConstants:(id)constants;
- (const struct { unsigned char x0[32]; } *)bitCodeHash;
- (void)setFunctionConstantSpecializationHash:(const struct { unsigned char x0[32]; } *)hash;
- (unsigned long long)bitCodeFileSize;
- (unsigned int)requiredLLVMVersion;
- (id)functionConstantsDictionary;
- (unsigned long long)sourceArchiveOffset;
- (void)setSourceArchiveOffset:(unsigned long long)offset;
- (void)setOptions:(unsigned long long)options;
- (_Bool)specializedFunctionHash:(struct { unsigned char x0[32]; } *)hash requestData:(id *)data constants:(id)constants specializedName:(id)name privateFunctions:(id)functions completionHandler:(id /* block */)handler;
- (void)newSpecializedFunctionWithDescriptor:(id)descriptor destinationArchive:(id)archive functionCache:(id)cache sync:(_Bool)sync completionHandler:(id /* block */)handler;
- (id)newSpecializedFunctionWithDescriptor:(id)descriptor destinationArchive:(id)archive functionCache:(id)cache error:(id *)error;
- (id)newFunctionWithPluginData:(id)data bitcodeType:(unsigned char)type;
- (void)initializePrivateMetadata;
- (void)setFilePath:(id)path;
- (id)filePath;
- (void)initializeSourceArchive;
- (void)setUnpackedFilePath:(id)path;
- (id)unpackedFilePath;
- (void)setLineNumber:(long long)number;
- (long long)lineNumber;
- (unsigned long long)renderTargetArrayIndexType;
- (id)functionInputs;
- (void)setRelocations:(id)relocations;
- (id)relocations;

@end

#endif /* _MTLFunctionInternal_h */
