//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.7, SDK: 13.7, Tool: ld (857.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 16.6, SDK: 16.6, Tool: ld (857.2)
//    - LC_SOURCE_VERSION: 306.7.5.0.0
//
#ifndef MTLAccelerationStructureSPI_Protocol_h
#define MTLAccelerationStructureSPI_Protocol_h
@import Foundation;

#include "MTLAccelerationStructure-Protocol.h"
#include "MTLAccelerationStructureDescriptor.h"
#include "MTLBuffer-Protocol.h"

@protocol MTLAccelerationStructureSPI <MTLAccelerationStructure>

@required

@property (readonly, nonatomic) unsigned long long uniqueIdentifier;
@property (readonly, nonatomic) id <MTLBuffer> buffer;
@property (readonly, nonatomic) unsigned long long bufferOffset;
@property (retain, nonatomic) MTLAccelerationStructureDescriptor *descriptor;
@property (readonly, nonatomic) unsigned long long resourceIndex;
@property (readonly) unsigned long long gpuHandle;

@optional

@end

#endif /* MTLAccelerationStructureSPI_Protocol_h */
