//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.7, SDK: 13.7, Tool: ld (857.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 16.6, SDK: 16.6, Tool: ld (857.2)
//    - LC_SOURCE_VERSION: 306.7.5.0.0
//
#ifndef MTLBuiltInArgument_h
#define MTLBuiltInArgument_h
@import Foundation;

#include "MTLBindingInternal.h"

@interface MTLBuiltInArgument : MTLBindingInternal {
    /* instance variables */
    unsigned short _builtInType;
    unsigned short _builtInDataType;
}

/* instance methods */
- (id)initWithName:(id)name type:(unsigned long long)type access:(unsigned long long)access active:(signed char)active index:(unsigned long long)index dataType:(unsigned long long)type builtInType:(unsigned long long)type;
- (unsigned long long)builtInDataType;
- (unsigned long long)builtInType;
- (id)formattedDescription:(unsigned long long)description;

@end

#endif /* MTLBuiltInArgument_h */
