//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.7, SDK: 13.7, Tool: ld (857.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 16.6, SDK: 16.6, Tool: ld (857.2)
//    - LC_SOURCE_VERSION: 306.7.5.0.0
//
#ifndef MTLDebugLocation_h
#define MTLDebugLocation_h
@import Foundation;

#include "MTLDebugInstrumentationData.h"
#include "MTLDebugSubProgram.h"

@class NSObject;

@interface MTLDebugLocation : NSObject {
    /* instance variables */
    MTLDebugInstrumentationData *_data;
    struct DebugLocation { unsigned int x0; unsigned int x1; unsigned int x2; unsigned int x3; } * _debugLoc;
}

@property (readonly, nonatomic) MTLDebugSubProgram *scope;
@property (readonly, nonatomic) unsigned int line;
@property (readonly, nonatomic) unsigned int column;
@property (readonly, nonatomic) MTLDebugLocation *inlinedAt;

/* instance methods */
- (id)formattedDescription:(unsigned long long)description;
- (id)description;
- (id)retain;
- (oneway void)release;
- (oneway void)releaseInternal;
- (void)dealloc;

@end

#endif /* MTLDebugLocation_h */
