//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.7, SDK: 13.7, Tool: ld (857.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 16.6, SDK: 16.6, Tool: ld (857.2)
//    - LC_SOURCE_VERSION: 306.7.5.0.0
//
#ifndef MTLFunctionConstantValuesInternal_h
#define MTLFunctionConstantValuesInternal_h
@import Foundation;

#include "MTLFunctionConstantSPI-Protocol.h"

@interface MTLFunctionConstantValuesInternal :  <MTLFunctionConstantSPI> {
    /* instance variables */
    void * _constantStorage;
}

/* instance methods */
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)zone;
- (unsigned long long)hash;
- (signed char)isEqual:(id)equal;
- (void)setConstantValue:(const void *)value type:(unsigned long long)type atIndex:(unsigned long long)index;
- (void)setConstantValues:(const void *)values type:(unsigned long long)type withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)setConstantValue:(const void *)value type:(unsigned long long)type withName:(id)name;
- (void)reset;
- (id)newNamedConstantArray;
- (id)newIndexedConstantArray;
- (id)description;
- (void *)serializedConstantDataForFunction:(id)function dataSize:(unsigned long long *)size errorMessage:(id *)message;
- (const void *)constantValueWithFunctionConstant:(id)constant;
- (id)newConstantScriptForFunction:(id)function name:(id)name specializedName:(id)name errorMessage:(id *)message;

@end

#endif /* MTLFunctionConstantValuesInternal_h */
