//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.7, SDK: 13.7, Tool: ld (857.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 16.6, SDK: 16.6, Tool: ld (857.2)
//    - LC_SOURCE_VERSION: 306.7.5.0.0
//
#ifndef MTLIntersectionFunctionTable_Protocol_h
#define MTLIntersectionFunctionTable_Protocol_h
@import Foundation;

#include "MTLResource-Protocol.h"

@protocol MTLIntersectionFunctionTable <MTLResource>

@required

@property (readonly) struct MTLResourceID { unsigned long long x0; } gpuResourceID;

/* required instance methods */
- (void)setBuffer:(id)buffer offset:(unsigned long long)offset atIndex:(unsigned long long)index;
- (void)setBuffers:(const id *)buffers offsets:(const unsigned long long *)offsets withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)setFunction:(id)function atIndex:(unsigned long long)index;
- (void)setFunctions:(const id *)functions withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)setOpaqueTriangleIntersectionFunctionWithSignature:(unsigned long long)signature atIndex:(unsigned long long)index;
- (void)setOpaqueTriangleIntersectionFunctionWithSignature:(unsigned long long)signature withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)setVisibleFunctionTable:(id)table atBufferIndex:(unsigned long long)index;
- (void)setVisibleFunctionTables:(const id *)tables withBufferRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;

@optional

@end

#endif /* MTLIntersectionFunctionTable_Protocol_h */
