//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.7, SDK: 13.7, Tool: ld (857.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 16.6, SDK: 16.6, Tool: ld (857.2)
//    - LC_SOURCE_VERSION: 306.7.5.0.0
//
#ifndef MTLIntersectionFunctionTableDescriptorInternal_h
#define MTLIntersectionFunctionTableDescriptorInternal_h
@import Foundation;

@interface MTLIntersectionFunctionTableDescriptorInternal :  {
    /* instance variables */
    struct MTLIntersectionFunctionTableDescriptorPrivate { unsigned long long functionCount; signed char forceResourceIndex; unsigned long long resourceIndex; } _private;
}

/* class methods */
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (unsigned long long)functionCount;
- (void)setFunctionCount:(unsigned long long)count;
- (signed char)forceResourceIndex;
- (void)setForceResourceIndex:(signed char)index;
- (unsigned long long)resourceIndex;
- (void)setResourceIndex:(unsigned long long)index;
- (unsigned long long)hash;
- (signed char)isEqual:(id)equal;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;

@end

#endif /* MTLIntersectionFunctionTableDescriptorInternal_h */
