//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.7, SDK: 13.7, Tool: ld (857.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 16.6, SDK: 16.6, Tool: ld (857.2)
//    - LC_SOURCE_VERSION: 306.7.5.0.0
//
#ifndef MTLIndirectComputeCommandSPI_Protocol_h
#define MTLIndirectComputeCommandSPI_Protocol_h
@import Foundation;

#include "MTLIndirectComputeCommand-Protocol.h"

@protocol MTLIndirectComputeCommandSPI <MTLIndirectComputeCommand>

@required

/* required instance methods */
- (void *)getKernelBufferAtIndex:(unsigned long long)index;
- (unsigned long long)getCommandType;
- (id)dispatchThreadgroupsArguments;
- (id)dispatchThreadsArguments;
- (unsigned long long)getThreadgroupMemoryLengthAtIndex:(unsigned long long)index;
- (struct { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x0; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x1; })getStageInRegion;
- (signed char)hasBarrier;
- (id)getImageBlockSize;
- (unsigned long long)getOptimizedStatus;
- (unsigned long long)getPipelineStateUniqueIdentifier;

@optional

@end

#endif /* MTLIndirectComputeCommandSPI_Protocol_h */
