//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.7, SDK: 13.7, Tool: ld (857.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 16.6, SDK: 16.6, Tool: ld (857.2)
//    - LC_SOURCE_VERSION: 306.7.5.0.0
//
#ifndef MTLPipelineLibrarySPI_Protocol_h
#define MTLPipelineLibrarySPI_Protocol_h
@import Foundation;

#include "MTLDevice-Protocol.h"
#include "MTLPipelineCache-Protocol.h"
#include "MTLPipelineLibrary-Protocol.h"

@class NSArray, NSString;

@protocol MTLPipelineLibrarySPI <MTLPipelineLibrary>

@required

@property (copy) NSString *label;
@property (readonly) id <MTLDevice> device;
@property (readonly) NSArray *pipelineNames;
@property signed char disableRunTimeCompilation;
@property (readonly, nonatomic) id <MTLPipelineCache> pipelineCache;
@property (readonly, nonatomic) id <MTLPipelineCache> functionCache;

/* required instance methods */
- (id)newComputePipelineStateWithName:(id)name options:(unsigned long long)options reflection:(id *)reflection error:(id *)error;
- (id)newRenderPipelineStateWithName:(id)name options:(unsigned long long)options reflection:(id *)reflection error:(id *)error;
- (id)newComputePipelineDescriptorWithName:(id)name error:(id *)error;
- (id)newRenderPipelineDescriptorWithName:(id)name error:(id *)error;

@optional

@end

#endif /* MTLPipelineLibrarySPI_Protocol_h */
