//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.7, SDK: 13.7, Tool: ld (857.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 16.6, SDK: 16.6, Tool: ld (857.2)
//    - LC_SOURCE_VERSION: 306.7.5.0.0
//
#ifndef MTLRenderPassDescriptorInternal_h
#define MTLRenderPassDescriptorInternal_h
@import Foundation;

#include "MTLBuffer-Protocol.h"
#include "MTLRasterizationRateMap-Protocol.h"
#include "MTLRenderPassColorAttachmentDescriptorArrayInternal.h"
#include "MTLRenderPassSampleBufferAttachmentDescriptorArrayInternal.h"

@interface MTLRenderPassDescriptorInternal :  {
    /* instance variables */
    struct MTLRenderPassDescriptorPrivate { MTLRenderPassColorAttachmentDescriptorArrayInternal *attachments; <MTLBuffer> *visibilityResultBuffer; unsigned long long renderTargetWidth; unsigned long long renderTargetHeight; unsigned long long defaultColorSampleCount; signed char fineGrainedBackgroundVisibilityEnabled; signed char skipEmptyTilesOnClearEnabled; signed char ditherEnabled; signed char openGLModeEnabled; unsigned long long renderTargetArrayLength; unsigned long long tileWidth; unsigned long long tileHeight; union { unsigned long long defaultSampleCount; unsigned long long defaultRasterSampleCount; } x12; unsigned long long imageBlockSampleLength; unsigned long long threadgroupMemoryLength; struct { float customSamplePositions; float y; } x[8]; unsigned long long numCustomSamplePositions; <MTLRasterizationRateMap> *rasterizationRateMap; MTLRenderPassSampleBufferAttachmentDescriptorArrayInternal *sampleBufferAttachments; signed char pointCoordYFlipEnabled; } _private;
}

/* class methods */
+ (id)renderPassDescriptor;

/* instance methods */
- (id)init;
- (id)colorAttachments;
- (void)setDepthAttachment:(id)attachment;
- (id)depthAttachment;
- (void)setStencilAttachment:(id)attachment;
- (id)stencilAttachment;
- (void)dealloc;
- (unsigned long long)hash;
- (signed char)isEqual:(id)equal;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)setVisibilityResultBuffer:(id)buffer;
- (id)visibilityResultBuffer;
- (void)setRenderTargetArrayLength:(unsigned long long)length;
- (unsigned long long)renderTargetArrayLength;
- (void)setRenderTargetWidth:(unsigned long long)width;
- (unsigned long long)renderTargetWidth;
- (void)setRenderTargetHeight:(unsigned long long)height;
- (unsigned long long)renderTargetHeight;
- (void)setDefaultColorSampleCount:(unsigned long long)count;
- (unsigned long long)defaultColorSampleCount;
- (void)setFineGrainedBackgroundVisibilityEnabled:(signed char)enabled;
- (signed char)fineGrainedBackgroundVisibilityEnabled;
- (void)setSkipEmptyTilesOnClearEnabled:(signed char)enabled;
- (signed char)skipEmptyTilesOnClearEnabled;
- (void)setDitherEnabled:(signed char)enabled;
- (signed char)isDitherEnabled;
- (void)setOpenGLModeEnabled:(signed char)enabled;
- (signed char)openGLModeEnabled;
- (void)setPointCoordYFlipEnabled:(signed char)enabled;
- (signed char)pointCoordYFlipEnabled;
- (void)setImageblockSampleLength:(unsigned long long)length;
- (unsigned long long)imageblockSampleLength;
- (void)setThreadgroupMemoryLength:(unsigned long long)length;
- (unsigned long long)threadgroupMemoryLength;
- (void)setTileWidth:(unsigned long long)width;
- (unsigned long long)tileWidth;
- (void)setTileHeight:(unsigned long long)height;
- (unsigned long long)tileHeight;
- (void)setDefaultRasterSampleCount:(unsigned long long)count;
- (unsigned long long)defaultRasterSampleCount;
- (id)rasterizationRateMap;
- (void)setRasterizationRateMap:(id)map;
- (void)setSamplePositions:(const struct { float x0; float x1; } *)positions count:(unsigned long long)count;
- (unsigned long long)getSamplePositions:(struct { float x0; float x1; } *)positions count:(unsigned long long)count;
- (signed char)validate:(id)validate width:(unsigned long long *)width height:(unsigned long long *)height;
- (const struct MTLRenderPassDescriptorPrivate { id x0; id x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; signed char x5; signed char x6; signed char x7; signed char x8; unsigned long long x9; unsigned long long x10; unsigned long long x11; union { unsigned long long x0; unsigned long long x1; } x12; unsigned long long x13; unsigned long long x14; struct { float x150; float x1; } x[8]; unsigned long long x16; id x17; id x18; signed char x19; } *)_descriptorPrivate;
- (id)sampleBufferAttachments;

@end

#endif /* MTLRenderPassDescriptorInternal_h */
