//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.7, SDK: 13.7, Tool: ld (857.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 16.6, SDK: 16.6, Tool: ld (857.2)
//    - LC_SOURCE_VERSION: 306.7.5.0.0
//
#ifndef MTLResourceStatePassSampleBufferAttachmentDescriptorInternal_h
#define MTLResourceStatePassSampleBufferAttachmentDescriptorInternal_h
@import Foundation;

@protocol MTLCounterSampleBuffer;

@interface MTLResourceStatePassSampleBufferAttachmentDescriptorInternal :  {
    /* instance variables */
    struct MTLResourceStatePassSampleBufferAttachmentDescriptorPrivate { <MTLCounterSampleBuffer> *sampleBuffer; unsigned long long startOfEncoderSampleIndex; unsigned long long endOfEncoderSampleIndex; } _private;
}

/* instance methods */
- (id)init;
- (void)dealloc;
- (const struct MTLResourceStatePassSampleBufferAttachmentDescriptorPrivate { id x0; unsigned long long x1; unsigned long long x2; } *)_descriptorPrivate;
- (void)setSampleBuffer:(id)buffer;
- (id)sampleBuffer;
- (void)setStartOfEncoderSampleIndex:(unsigned long long)index;
- (unsigned long long)startOfEncoderSampleIndex;
- (void)setEndOfEncoderSampleIndex:(unsigned long long)index;
- (unsigned long long)endOfEncoderSampleIndex;
- (id)copyWithZone:(struct _NSZone *)zone;
- (signed char)isEqual:(id)equal;
- (unsigned long long)hash;

@end

#endif /* MTLResourceStatePassSampleBufferAttachmentDescriptorInternal_h */
