//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.7, SDK: 13.7, Tool: ld (857.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 16.6, SDK: 16.6, Tool: ld (857.2)
//    - LC_SOURCE_VERSION: 306.7.5.0.0
//
#ifndef MTLSharedEventListenerInternal_h
#define MTLSharedEventListenerInternal_h
@import Foundation;

@class NSObject;
@protocol OS_dispatch_queue;

@interface MTLSharedEventListenerInternal :  {
    /* instance variables */
    struct IONotificationPort * _notificationPort;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
}

/* instance methods */
- (id)init;
- (id)initWithDispatchQueue:(id)queue;
- (void)dealloc;
- (id)dispatchQueue;
- (void)_notifyEventPort:(unsigned int)port event:(id)event atValue:(unsigned long long)value block:(id /* block */)block;

@end

#endif /* MTLSharedEventListenerInternal_h */
