//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.7, SDK: 13.7, Tool: ld (857.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 16.6, SDK: 16.6, Tool: ld (857.2)
//    - LC_SOURCE_VERSION: 306.7.5.0.0
//
#ifndef MTLTileRenderPipelineColorAttachmentDescriptorInternal_h
#define MTLTileRenderPipelineColorAttachmentDescriptorInternal_h
@import Foundation;

@interface MTLTileRenderPipelineColorAttachmentDescriptorInternal :  {
    /* instance variables */
    struct MTLTileRenderPipelineAttachmentDescriptorPrivate { union { struct { unsigned int pixelFormat; } x0; struct { unsigned int bits; } x1; } x0; } _private;
}

/* instance methods */
- (id)init;
- (void)dealloc;
- (signed char)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;
- (unsigned long long)pixelFormat;
- (void)setPixelFormat:(unsigned long long)format;

@end

#endif /* MTLTileRenderPipelineColorAttachmentDescriptorInternal_h */
