//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.7, SDK: 13.7, Tool: ld (857.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 16.6, SDK: 16.6, Tool: ld (857.2)
//    - LC_SOURCE_VERSION: 306.7.5.0.0
//
#ifndef MTLTextureReferenceTypeInternal_h
#define MTLTextureReferenceTypeInternal_h
@import Foundation;

@interface MTLTextureReferenceTypeInternal :  {
    /* instance variables */
    unsigned long long _dataType;
    unsigned long long _textureDataType;
    unsigned long long _textureType;
    unsigned long long _access;
    signed char _isDepthTexture;
}

/* instance methods */
- (id)initWithDataType:(unsigned long long)type textureType:(unsigned long long)type access:(unsigned long long)access isDepthTexture:(signed char)texture;
- (void)dealloc;
- (id)formattedDescription:(unsigned long long)description;
- (unsigned long long)dataType;
- (unsigned long long)textureDataType;
- (unsigned long long)textureType;
- (unsigned long long)access;
- (signed char)isDepthTexture;

@end

#endif /* MTLTextureReferenceTypeInternal_h */
