//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 13.7, SDK: 13.7, Tool: ld (857.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 16.6, SDK: 16.6, Tool: ld (857.2)
//    - LC_SOURCE_VERSION: 306.7.5.0.0
//
#ifndef MTLVisibleFunctionTableSPI_Protocol_h
#define MTLVisibleFunctionTableSPI_Protocol_h
@import Foundation;

#include "MTLBuffer-Protocol.h"
#include "MTLVisibleFunctionTable-Protocol.h"

@protocol MTLVisibleFunctionTableSPI <MTLVisibleFunctionTable>

@required

@property (readonly, nonatomic) unsigned long long resourceIndex;
@property (readonly) unsigned long long uniqueIdentifier;
@property (retain, nonatomic) id <MTLBuffer> globalBuffer;
@property (nonatomic) unsigned long long globalBufferOffset;
@property (readonly) unsigned long long gpuHandle;

/* required instance methods */
- (void)setBuffer:(id)buffer offset:(unsigned long long)offset atIndex:(unsigned long long)index;
- (void)setBuffers:(const id *)buffers offsets:(const unsigned long long *)offsets withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)setValue:(unsigned long long)value atIndex:(unsigned long long)index;
- (void)setValue:(unsigned long long)value withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)setVisibleFunctionTable:(id)table atBufferIndex:(unsigned long long)index;
- (void)setVisibleFunctionTables:(const id *)tables withBufferRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;

@optional

@end

#endif /* MTLVisibleFunctionTableSPI_Protocol_h */
