//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef _MTLMLLibrary_h
#define _MTLMLLibrary_h
@import Foundation;

#include "MTLDevice-Protocol.h"
#include "MTLLibrarySPI-Protocol.h"

@class NSArray, NSData, NSString, NSURL, NSUUID;
@protocol MPSGraphExecutableProxy, MPSGraphExecutableReflectionProxy;

@interface _MTLMLLibrary :  <MTLLibrarySPI> {
    /* instance variables */
    <MPSGraphExecutableProxy> *_executables[3];
    NSURL *_mpsgraphPackageURL;
    id <MPSGraphExecutableReflectionProxy> _reflection;
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
}

@property (copy) NSString *overrideTriple;
@property (nonatomic) signed char shaderValidationEnabled;
@property (readonly) NSArray *externFunctionNames;
@property (readonly) NSData *bitcodeData;
@property (readonly, copy) NSUUID *libraryIdentifier;
@property (copy) NSString *label;
@property (readonly) id <MTLDevice> device;
@property (readonly) NSArray *functionNames;
@property (readonly) long long type;
@property (readonly) NSString *installName;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithDevice:(id)device executable:(id)executable url:(id)url reflection:(id)reflection;
- (id)executableWithDeviceSelection:(long long)selection;
- (unsigned long long)executableSize;
- (void)dealloc;
- (id)reflectionForFunctionWithName:(id)name;
- (void)newFunctionWithDescriptor:(id)descriptor completionHandler:(id /* block */)handler;
- (id)newFunctionWithDescriptor:(id)descriptor error:(id *)error;
- (id)newFunctionWithName:(id)name;
- (void)newFunctionWithName:(id)name constantValues:(id)values completionHandler:(id /* block */)handler;
- (id)newFunctionWithName:(id)name constantValues:(id)values error:(id *)error;
- (void)newIntersectionFunctionWithDescriptor:(id)descriptor completionHandler:(id /* block */)handler;
- (id)newIntersectionFunctionWithDescriptor:(id)descriptor error:(id *)error;
- (id)newExternFunctionWithName:(id)name;
- (id)newFunctionWithDescriptor:(id)descriptor destinationArchive:(id)archive error:(id *)error;
- (id)newFunctionWithName:(id)name constantValues:(id)values functionCache:(id)cache error:(id *)error;
- (void)newFunctionWithName:(id)name constantValues:(id)values pipelineLibrary:(id)library completionHandler:(id /* block */)handler;
- (id)newFunctionWithName:(id)name constantValues:(id)values pipelineLibrary:(id)library error:(id *)error;
- (signed char)serializeToURL:(id)url error:(id *)error;

@end

#endif /* _MTLMLLibrary_h */
