//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef _MTLIOAccelMTLEvent_h
#define _MTLIOAccelMTLEvent_h
@import Foundation;

#include "MTLDevice-Protocol.h"
#include "MTLEventSPI-Protocol.h"
#include "MTLIOAccelDevice.h"

@class IOAccelMTLEvent, NSString;

@interface _MTLIOAccelMTLEvent : IOAccelMTLEvent <MTLEventSPI> {
    /* instance variables */
    unsigned long long _labelTraceID;
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _labelLock;
}

@property (readonly) id <MTLDevice> device;
@property (copy) NSString *label;
@property (nonatomic) signed char enableBarrier;
@property (readonly) signed char supportsRollback;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithDevice:(id)device;
- (id)initWithDevice:(id)device options:(long long)options;
- (void)dealloc;
- (id)retainedLabel;

@end

#endif /* _MTLIOAccelMTLEvent_h */
