//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTL4RenderCommandEncoder_Protocol_h
#define MTL4RenderCommandEncoder_Protocol_h
@import Foundation;

#include "MTL4CommandEncoder-Protocol.h"

@protocol MTL4RenderCommandEncoder <MTL4CommandEncoder>

@required

@property (readonly) unsigned long long tileWidth;
@property (readonly) unsigned long long tileHeight;

/* required instance methods */
- (void)setColorAttachmentMap:(id)map;
- (void)setRenderPipelineState:(id)state;
- (void)setViewport:(struct { double x0; double x1; double x2; double x3; double x4; double x5; })viewport;
- (void)setViewports:(const struct { double x0; double x1; double x2; double x3; double x4; double x5; } *)viewports count:(unsigned long long)count;
- (void)setVertexAmplificationCount:(unsigned long long)count viewMappings:(const struct { unsigned int x0; unsigned int x1; } *)mappings;
- (void)setCullMode:(unsigned long long)mode;
- (void)setDepthClipMode:(unsigned long long)mode;
- (void)setDepthBias:(float)bias slopeScale:(float)scale clamp:(float)clamp;
- (void)setDepthTestMinBound:(float)bound maxBound:(float)bound;
- (void)setScissorRect:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; })rect;
- (void)setScissorRects:(const struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; } *)rects count:(unsigned long long)count;
- (void)setTriangleFillMode:(unsigned long long)mode;
- (void)setBlendColorRed:(float)red green:(float)green blue:(float)blue alpha:(float)alpha;
- (void)setDepthStencilState:(id)state;
- (void)setStencilReferenceValue:(unsigned int)value;
- (void)setStencilFrontReferenceValue:(unsigned int)value backReferenceValue:(unsigned int)value;
- (void)setVisibilityResultMode:(unsigned long long)mode offset:(unsigned long long)offset;
- (void)setColorStoreAction:(unsigned long long)action atIndex:(unsigned long long)index;
- (void)setDepthStoreAction:(unsigned long long)action;
- (void)setStencilStoreAction:(unsigned long long)action;
- (void)drawPrimitives:(unsigned long long)primitives vertexStart:(unsigned long long)start vertexCount:(unsigned long long)count;
- (void)drawPrimitives:(unsigned long long)primitives vertexStart:(unsigned long long)start vertexCount:(unsigned long long)count instanceCount:(unsigned long long)count;
- (void)drawPrimitives:(unsigned long long)primitives vertexStart:(unsigned long long)start vertexCount:(unsigned long long)count instanceCount:(unsigned long long)count baseInstance:(unsigned long long)instance;
- (void)drawIndexedPrimitives:(unsigned long long)primitives indexCount:(unsigned long long)count indexType:(unsigned long long)type indexBuffer:(unsigned long long)buffer indexBufferLength:(unsigned long long)length;
- (void)drawIndexedPrimitives:(unsigned long long)primitives indexCount:(unsigned long long)count indexType:(unsigned long long)type indexBuffer:(unsigned long long)buffer indexBufferLength:(unsigned long long)length instanceCount:(unsigned long long)count;
- (void)drawIndexedPrimitives:(unsigned long long)primitives indexCount:(unsigned long long)count indexType:(unsigned long long)type indexBuffer:(unsigned long long)buffer indexBufferLength:(unsigned long long)length instanceCount:(unsigned long long)count baseVertex:(long long)vertex baseInstance:(unsigned long long)instance;
- (void)drawPrimitives:(unsigned long long)primitives indirectBuffer:(unsigned long long)buffer;
- (void)drawIndexedPrimitives:(unsigned long long)primitives indexType:(unsigned long long)type indexBuffer:(unsigned long long)buffer indexBufferLength:(unsigned long long)length indirectBuffer:(unsigned long long)buffer;
- (void)executeCommandsInBuffer:(id)buffer withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)executeCommandsInBuffer:(id)buffer indirectBuffer:(unsigned long long)buffer;
- (void)setObjectThreadgroupMemoryLength:(unsigned long long)length atIndex:(unsigned long long)index;
- (void)drawMeshThreadgroups:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroups threadsPerObjectThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup threadsPerMeshThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup;
- (void)drawMeshThreads:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threads threadsPerObjectThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup threadsPerMeshThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup;
- (void)drawMeshThreadgroupsWithIndirectBuffer:(unsigned long long)buffer threadsPerObjectThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup threadsPerMeshThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup;
- (void)dispatchThreadsPerTile:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })tile;
- (void)setThreadgroupMemoryLength:(unsigned long long)length offset:(unsigned long long)offset atIndex:(unsigned long long)index;
- (void)setArgumentTable:(id)table atStages:(unsigned long long)stages;
- (void)setFrontFacingWinding:(unsigned long long)winding;
- (void)writeTimestampWithGranularity:(long long)granularity afterStage:(unsigned long long)stage intoHeap:(id)heap atIndex:(unsigned long long)index;

@optional

@end

#endif /* MTL4RenderCommandEncoder_Protocol_h */
