//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTL4ComputeCommandEncoder_Protocol_h
#define MTL4ComputeCommandEncoder_Protocol_h
@import Foundation;

#include "MTL4CommandEncoder-Protocol.h"

@protocol MTL4ComputeCommandEncoder <MTL4CommandEncoder>

@required

/* required instance methods */
- (unsigned long long)stages;
- (void)setComputePipelineState:(id)state;
- (void)setThreadgroupMemoryLength:(unsigned long long)length atIndex:(unsigned long long)index;
- (void)setImageblockWidth:(unsigned long long)width height:(unsigned long long)height;
- (void)dispatchThreads:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threads threadsPerThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup;
- (void)dispatchThreadgroups:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroups threadsPerThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup;
- (void)dispatchThreadgroupsWithIndirectBuffer:(unsigned long long)buffer threadsPerThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup;
- (void)dispatchThreadsWithIndirectBuffer:(unsigned long long)buffer;
- (void)executeCommandsInBuffer:(id)buffer withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)executeCommandsInBuffer:(id)buffer indirectBuffer:(unsigned long long)buffer;
- (void)copyFromTexture:(id)texture toTexture:(id)texture;
- (void)copyFromTexture:(id)texture sourceSlice:(unsigned long long)slice sourceLevel:(unsigned long long)level toTexture:(id)texture destinationSlice:(unsigned long long)slice destinationLevel:(unsigned long long)level sliceCount:(unsigned long long)count levelCount:(unsigned long long)count;
- (void)copyFromTexture:(id)texture sourceSlice:(unsigned long long)slice sourceLevel:(unsigned long long)level sourceOrigin:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })origin sourceSize:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })size toTexture:(id)texture destinationSlice:(unsigned long long)slice destinationLevel:(unsigned long long)level destinationOrigin:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })origin;
- (void)copyFromTexture:(id)texture sourceSlice:(unsigned long long)slice sourceLevel:(unsigned long long)level sourceOrigin:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })origin sourceSize:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })size toBuffer:(id)buffer destinationOffset:(unsigned long long)offset destinationBytesPerRow:(unsigned long long)row destinationBytesPerImage:(unsigned long long)image;
- (void)copyFromTexture:(id)texture sourceSlice:(unsigned long long)slice sourceLevel:(unsigned long long)level sourceOrigin:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })origin sourceSize:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })size toBuffer:(id)buffer destinationOffset:(unsigned long long)offset destinationBytesPerRow:(unsigned long long)row destinationBytesPerImage:(unsigned long long)image options:(unsigned long long)options;
- (void)copyFromBuffer:(id)buffer sourceOffset:(unsigned long long)offset toBuffer:(id)buffer destinationOffset:(unsigned long long)offset size:(unsigned long long)size;
- (void)copyFromBuffer:(id)buffer sourceOffset:(unsigned long long)offset sourceBytesPerRow:(unsigned long long)row sourceBytesPerImage:(unsigned long long)image sourceSize:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })size toTexture:(id)texture destinationSlice:(unsigned long long)slice destinationLevel:(unsigned long long)level destinationOrigin:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })origin;
- (void)copyFromBuffer:(id)buffer sourceOffset:(unsigned long long)offset sourceBytesPerRow:(unsigned long long)row sourceBytesPerImage:(unsigned long long)image sourceSize:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })size toTexture:(id)texture destinationSlice:(unsigned long long)slice destinationLevel:(unsigned long long)level destinationOrigin:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })origin options:(unsigned long long)options;
- (void)copyFromTensor:(id)tensor sourceOrigin:(id)origin sourceDimensions:(id)dimensions toTensor:(id)tensor destinationOrigin:(id)origin destinationDimensions:(id)dimensions;
- (void)generateMipmapsForTexture:(id)texture;
- (void)fillBuffer:(id)buffer range:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range value:(unsigned char)value;
- (void)optimizeContentsForGPUAccess:(id)gpuaccess;
- (void)optimizeContentsForGPUAccess:(id)gpuaccess slice:(unsigned long long)slice level:(unsigned long long)level;
- (void)optimizeContentsForCPUAccess:(id)cpuaccess;
- (void)optimizeContentsForCPUAccess:(id)cpuaccess slice:(unsigned long long)slice level:(unsigned long long)level;
- (void)resetCommandsInBuffer:(id)buffer withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)copyIndirectCommandBuffer:(id)buffer sourceRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range destination:(id)destination destinationIndex:(unsigned long long)index;
- (void)optimizeIndirectCommandBuffer:(id)buffer withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)setArgumentTable:(id)table;
- (void)buildAccelerationStructure:(id)structure descriptor:(id)descriptor scratchBuffer:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })buffer;
- (void)refitAccelerationStructure:(id)structure descriptor:(id)descriptor destination:(id)destination scratchBuffer:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })buffer;
- (void)refitAccelerationStructure:(id)structure descriptor:(id)descriptor destination:(id)destination scratchBuffer:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })buffer options:(unsigned long long)options;
- (void)copyAccelerationStructure:(id)structure toAccelerationStructure:(id)structure;
- (void)writeCompactedAccelerationStructureSize:(id)size toBuffer:(struct MTL4BufferRange { unsigned long long x0; unsigned long long x1; })buffer;
- (void)copyAndCompactAccelerationStructure:(id)structure toAccelerationStructure:(id)structure;
- (void)writeTimestampWithGranularity:(long long)granularity intoHeap:(id)heap atIndex:(unsigned long long)index;

@optional

@end

#endif /* MTL4ComputeCommandEncoder_Protocol_h */
