//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTL4CommandEncoderGGDSPI_Protocol_h
#define MTL4CommandEncoderGGDSPI_Protocol_h
@import Foundation;

#include "MTL4CommandAllocator-Protocol.h"
#include "MTL4CommandEncoderSPI-Protocol.h"

@protocol MTL4CommandEncoderGGDSPI <MTL4CommandEncoderSPI>

@required

@property (readonly, nonatomic) id <MTL4CommandAllocator> commandAllocator;

/* required instance methods */
- (void)barrierAfterQueueStages:(unsigned long long)stages beforeStages:(unsigned long long)stages options:(unsigned long long)options;
- (void)barrierAfterStages:(unsigned long long)stages beforeQueueStages:(unsigned long long)stages options:(unsigned long long)options;
- (void)barrierAfterEncoderStages:(unsigned long long)stages beforeEncoderStages:(unsigned long long)stages options:(unsigned long long)options;

@optional

@end

#endif /* MTL4CommandEncoderGGDSPI_Protocol_h */
