//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTL4CompilerTask_Protocol_h
#define MTL4CompilerTask_Protocol_h
@import Foundation;

#include "MTL4Compiler-Protocol.h"
#include "NSObject-Protocol.h"

@protocol MTL4CompilerTask <NSObject>

@required

@property (readonly) id <MTL4Compiler> compiler;
@property (readonly) long long status;

/* required instance methods */
- (void)waitUntilCompleted;

@optional

@end

#endif /* MTL4CompilerTask_Protocol_h */
