//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTL4RenderCommandEncoderSPI_Protocol_h
#define MTL4RenderCommandEncoderSPI_Protocol_h
@import Foundation;

#include "MTL4CommandEncoderSPI-Protocol.h"
#include "MTL4RenderCommandEncoder-Protocol.h"

@protocol MTL4RenderCommandEncoderSPI <MTL4RenderCommandEncoder, MTL4CommandEncoderSPI>

@required

/* required instance methods */
- (void)setLineWidth:(float)width;
- (void)setToolsDispatchBufferSPI:(unsigned long long)spi atIndex:(unsigned long long)index stages:(unsigned long long)stages;

@optional

@end

#endif /* MTL4RenderCommandEncoderSPI_Protocol_h */
