//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTL4MachineLearningCommandEncoderGGDSPI_Protocol_h
#define MTL4MachineLearningCommandEncoderGGDSPI_Protocol_h
@import Foundation;

#include "MTL4CommandEncoderGGDSPI-Protocol.h"
#include "MTL4MachineLearningCommandEncoder-Protocol.h"

@protocol MTL4MachineLearningCommandEncoderGGDSPI <MTL4MachineLearningCommandEncoder, MTL4CommandEncoderGGDSPI>

@required

/* required instance methods */
- (void)endEncodingWithSignalEvent:(id)event waitEvent:(id)event signalValue:(unsigned long long)value waitValue:(unsigned long long)value;
- (unsigned long long)startEventValue;
- (unsigned long long)endEventValue;

@optional

@end

#endif /* MTL4MachineLearningCommandEncoderGGDSPI_Protocol_h */
