//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTL4CommandBufferGGDSPI_Protocol_h
#define MTL4CommandBufferGGDSPI_Protocol_h
@import Foundation;

#include "MTL4CommandAllocator-Protocol.h"
#include "MTL4CommandBufferSPI-Protocol.h"
#include "MTLBuffer-Protocol.h"

@protocol MTL4CommandBufferGGDSPI <MTL4CommandBufferSPI>

@required

@property (retain, nonatomic) id <MTLBuffer> privateData;
@property (nonatomic) unsigned long long privateDataOffset;
@property (readonly, nonatomic) id <MTL4CommandAllocator> commandAllocator;

/* required instance methods */
- (id)computeCommandEncoderWithSubstreamCount:(unsigned int)count;
- (void)resetCommandBuffer;

@optional

@end

#endif /* MTL4CommandBufferGGDSPI_Protocol_h */
