//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTLBinaryArchive_Protocol_h
#define MTLBinaryArchive_Protocol_h
@import Foundation;

#include "MTLDevice-Protocol.h"
#include "NSObject-Protocol.h"

@class NSString;

@protocol MTLBinaryArchive <NSObject>

@required

@property (copy) NSString *label;
@property (readonly) id <MTLDevice> device;

/* required instance methods */
- (signed char)addComputePipelineFunctionsWithDescriptor:(id)descriptor error:(id *)error;
- (signed char)addRenderPipelineFunctionsWithDescriptor:(id)descriptor error:(id *)error;
- (signed char)addTileRenderPipelineFunctionsWithDescriptor:(id)descriptor error:(id *)error;
- (signed char)addMeshRenderPipelineFunctionsWithDescriptor:(id)descriptor error:(id *)error;
- (signed char)addLibraryWithDescriptor:(id)descriptor error:(id *)error;
- (signed char)serializeToURL:(id)url error:(id *)error;
- (signed char)addFunctionWithDescriptor:(id)descriptor library:(id)library error:(id *)error;

@optional

@end

#endif /* MTLBinaryArchive_Protocol_h */
