//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTLBinaryKey_h
#define MTLBinaryKey_h
@import Foundation;

#include "NSCopying-Protocol.h"

@class NSObject;

@interface MTLBinaryKey : NSObject <NSCopying> {
    /* instance variables */
    void * _id;
}

@property (readonly) const struct { unsigned char x0[32]; } * value;

/* instance methods */
- (id)initWithHash:(const void *)hash;
- (signed char)isEqualToKey:(id)key;
- (signed char)isEqual:(id)equal;
- (const void *)getFunctionId;
- (void)dealloc;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;

@end

#endif /* MTLBinaryKey_h */
