//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTLBinaryArchiveSPI_Protocol_h
#define MTLBinaryArchiveSPI_Protocol_h
@import Foundation;

#include "MTLBinaryArchive-Protocol.h"

@class NSArray;

@protocol MTLBinaryArchiveSPI <MTLBinaryArchive>

@required

@property (readonly) unsigned long long options;
@property (readonly) NSArray *keys;

/* required instance methods */
- (id)archiveFunctionIds;
- (signed char)recompileToArchiveWithURL:(id)url error:(id *)error;
- (signed char)serializeToURL:(id)url options:(unsigned long long)options error:(id *)error;
- (id)formattedDescription:(unsigned long long)description;
- (signed char)addComputePipelineFunctionsWithDescriptor:(id)descriptor options:(unsigned long long)options error:(id *)error;
- (signed char)addRenderPipelineFunctionsWithDescriptor:(id)descriptor options:(unsigned long long)options error:(id *)error;
- (signed char)addTileRenderPipelineFunctionsWithDescriptor:(id)descriptor options:(unsigned long long)options error:(id *)error;
- (signed char)addMeshRenderPipelineFunctionsWithDescriptor:(id)descriptor options:(unsigned long long)options error:(id *)error;
- (signed char)storeComputePipelineDescriptor:(id)descriptor;
- (signed char)storeRenderPipelineDescriptor:(id)descriptor;
- (signed char)storeTileRenderPipelineDescriptor:(id)descriptor;
- (signed char)storeMeshRenderPipelineDescriptor:(id)descriptor;
- (void *)pipelineCollection;
- (signed char)enumerateArchivesFromBackingFile:(id /* block */)file;
- (signed char)enumerateArchivesFromPipelineCollection:(id /* block */)collection;

@optional

@end

#endif /* MTLBinaryArchiveSPI_Protocol_h */
