//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTLFunctionConstantInternal_h
#define MTLFunctionConstantInternal_h
@import Foundation;

@class NSString;

@interface MTLFunctionConstantInternal :  {
    /* instance variables */
    NSString *_name;
    unsigned long long _type;
    unsigned long long _index;
    signed char _required;
}

/* instance methods */
- (id)initWithName:(id)name type:(unsigned long long)type index:(unsigned long long)index required:(signed char)required;
- (void)dealloc;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;
- (id)name;
- (unsigned long long)type;
- (unsigned long long)index;
- (signed char)required;

@end

#endif /* MTLFunctionConstantInternal_h */
