//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTLIOCommandBufferSPI_Protocol_h
#define MTLIOCommandBufferSPI_Protocol_h
@import Foundation;

#include "MTLIOCommandBuffer-Protocol.h"

@protocol MTLIOCommandBufferSPI <MTLIOCommandBuffer>

@required

@property (readonly, nonatomic) unsigned long long globalTraceObjectID;

/* required instance methods */
- (void)encodeWaitForEvent:(id)event value:(unsigned long long)value;
- (void)encodeSignalEvent:(id)event value:(unsigned long long)value;
- (void)barrier;

@optional

@end

#endif /* MTLIOCommandBufferSPI_Protocol_h */
