//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTLLoader_h
#define MTLLoader_h
@import Foundation;

#include "MTLLoadedFile.h"

@class NSObject;
@protocol OS_dispatch_queue;

@interface MTLLoader : NSObject {
    /* instance variables */
    void * _global;
    NSObject<OS_dispatch_queue> *_claimQueue;
    struct unordered_map<MTLLoadedFile *, id, std::hash<MTLLoadedFile *>, std::equal_to<MTLLoadedFile *>, std::allocator<std::pair<MTLLoadedFile *const, id>>> { struct __hash_table<std::__hash_value_type<MTLLoadedFile *, id>, std::__unordered_map_hasher<MTLLoadedFile *, std::__hash_value_type<MTLLoadedFile *, id>, std::hash<MTLLoadedFile *>, std::equal_to<MTLLoadedFile *>>, std::__unordered_map_equal<MTLLoadedFile *, std::__hash_value_type<MTLLoadedFile *, id>, std::equal_to<MTLLoadedFile *>, std::hash<MTLLoadedFile *>>, std::allocator<std::__hash_value_type<MTLLoadedFile *, id>>> { struct unique_ptr<std::__hash_node_base<std::__hash_node<std::__hash_value_type<MTLLoadedFile *, id>, void *> *> *[], std::__bucket_list_deallocator<std::allocator<std::__hash_node_base<std::__hash_node<std::__hash_value_type<MTLLoadedFile *, id>, void *> *> *>>> { void * *__ptr_; struct __bucket_list_deallocator<std::allocator<std::__hash_node_base<std::__hash_node<std::__hash_value_type<MTLLoadedFile *, id>, void *> *> *>> { unsigned long long __size_; } __deleter_; } __bucket_list_; struct __hash_node_base<std::__hash_node<std::__hash_value_type<MTLLoadedFile *, id>, void *> *> { void *__next_; } __first_node_; unsigned long long __size_; float __max_load_factor_; } __table_; } _claims;
}

/* class methods */
+ (signed char)ReadHashTable:(unsigned long long)table begin:(unsigned int)begin end:(unsigned int)end hashList:(void *)list reader:(id /* block */)reader errorHandler:(id /* block */)handler handler:(id /* block */)handler;
+ (signed char)isAIRHeaderExtLoadCommand:(const void *)command headerOffset:(unsigned long long *)offset headerSize:(unsigned long long *)size headerSection:(unsigned int *)section;
+ (signed char)deserializeHashesFromAIRNTHeaderAtOffset:(unsigned long long)offset headerSize:(unsigned long long)size singleHeaderExpected:(_Bool)expected reader:(id /* block */)reader errorHandler:(id /* block */)handler handler:(id /* block */)handler;
+ (signed char)deserializeObjectFromAIRNTHeaderAtSection:(struct { unsigned long long x0; unsigned long long x1; unsigned int x2; } *)section reader:(id /* block */)reader errorHandler:(id /* block */)handler handler:(id /* block */)handler;
+ (signed char)deserializePipelinesFromAIRNTAtSection:(struct { unsigned long long x0; unsigned long long x1; unsigned int x2; } *)section reader:(id /* block */)reader errorHandler:(id /* block */)handler handler:(id /* block */)handler;

/* instance methods */
- (id)init;
- (oneway void)dealloc;

@end

#endif /* MTLLoader_h */
