//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTLNamedConstantValue_h
#define MTLNamedConstantValue_h
@import Foundation;

@class NSObject, NSString;

@interface MTLNamedConstantValue : NSObject

@property (readonly) NSString *name;
@property (readonly) unsigned long long dataType;
@property (readonly) void * data;

/* instance methods */
- (id)initWithValue:(const void *)value type:(unsigned long long)type name:(id)name;
- (void)dealloc;
- (id)describe;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;

@end

#endif /* MTLNamedConstantValue_h */
