//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTLPointerTypeInternal_h
#define MTLPointerTypeInternal_h
@import Foundation;

#include "MTLType.h"

@interface MTLPointerTypeInternal :  {
    /* instance variables */
    unsigned long long _dataType;
    unsigned long long _elementType;
    MTLType *_elementTypeInfo;
    unsigned long long _access;
    unsigned long long _alignment;
    unsigned long long _dataSize;
    signed char _elementIsArgumentBuffer;
    signed char _isConstantBuffer;
    signed char _doRetain;
}

/* instance methods */
- (id)initWithElementType:(unsigned long long)type elementTypeDescription:(id)description access:(unsigned long long)access alignment:(unsigned long long)alignment dataSize:(unsigned long long)size elementIsIndirectArgumentBuffer:(signed char)buffer isConstantBuffer:(signed char)buffer doRetain:(signed char)retain;
- (id)initWithElementType:(unsigned long long)type elementTypeDescription:(id)description access:(unsigned long long)access alignment:(unsigned long long)alignment dataSize:(unsigned long long)size elementIsIndirectArgumentBuffer:(signed char)buffer isConstantBuffer:(signed char)buffer;
- (void)dealloc;
- (id)elementTypeDescription;
- (void)setAlignment:(unsigned long long)alignment dataSize:(unsigned long long)size;
- (signed char)isConstantBuffer;
- (signed char)elementIsArgumentBuffer;
- (signed char)elementIsIndirectArgumentBuffer;
- (id)elementStructType;
- (id)structType;
- (id)elementArrayType;
- (id)formattedDescription:(unsigned long long)description withPrintedTypes:(id)types;
- (signed char)isEqual:(id)equal;
- (unsigned long long)dataType;
- (unsigned long long)elementType;
- (unsigned long long)access;
- (unsigned long long)alignment;
- (unsigned long long)dataSize;

@end

#endif /* MTLPointerTypeInternal_h */
