//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTLStageInputOutputDescriptorInternal_h
#define MTLStageInputOutputDescriptorInternal_h
@import Foundation;

#include "MTLAttributeDescriptorArrayInternal.h"
#include "MTLBufferLayoutDescriptorArrayInternal.h"

@interface MTLStageInputOutputDescriptorInternal :  {
    /* instance variables */
    MTLBufferLayoutDescriptorArrayInternal *_vertexBufferArray;
    MTLAttributeDescriptorArrayInternal *_attributeArray;
    unsigned long long _indexBufferIndex;
    unsigned long long _indexType;
}

/* class methods */
+ (id)vertexDescriptor;

/* instance methods */
- (id)init;
- (id)layouts;
- (id)attributes;
- (unsigned long long)indexType;
- (void)setIndexType:(unsigned long long)type;
- (unsigned long long)indexBufferIndex;
- (void)setIndexBufferIndex:(unsigned long long)index;
- (void)dealloc;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;
- (void)reset;
- (id)copyWithZone:(struct _NSZone *)zone;
- (unsigned long long)hash;
- (signed char)isEqual:(id)equal;
- (id)newSerializedDescriptor;
- (signed char)validateWithVertexFunction:(id)function error:(id *)error renderPipelineDescriptor:(id)descriptor;

@end

#endif /* MTLStageInputOutputDescriptorInternal_h */
