//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTLTextureBindingInternal_h
#define MTLTextureBindingInternal_h
@import Foundation;

#include "MTLBindingInternal.h"
#include "MTLTextureBinding-Protocol.h"

@class NSString;

@interface MTLTextureBindingInternal : MTLBindingInternal <MTLTextureBinding> {
    /* instance variables */
    unsigned int _isDepthTexture:1;
}

@property (readonly) unsigned long long textureType;
@property (readonly) unsigned long long textureDataType;
@property (readonly) signed char depthTexture;
@property (readonly) unsigned long long arrayLength;
@property (readonly) NSString *name;
@property (readonly) long long type;
@property (readonly) unsigned long long access;
@property (readonly) unsigned long long index;
@property (readonly) signed char used;
@property (readonly) signed char argument;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithName:(id)name access:(unsigned long long)access isActive:(signed char)active locationIndex:(unsigned long long)index arraySize:(unsigned long long)size dataType:(unsigned long long)type textureType:(unsigned long long)type isDepthTexture:(_Bool)texture;
- (signed char)isDepthTexture;
- (id)formattedDescription:(unsigned long long)description;
- (signed char)isEqual:(id)equal;

@end

#endif /* MTLTextureBindingInternal_h */
