//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 370.63.7.0.0
//
#ifndef MTLVertexAttributeInternal_h
#define MTLVertexAttributeInternal_h
@import Foundation;

@class NSString;

@interface MTLVertexAttributeInternal :  {
    /* instance variables */
    unsigned char _flags;
    NSString *_name;
    unsigned long long _attributeIndex;
    unsigned long long _attributeType;
}

/* instance methods */
- (id)initWithName:(id)name attributeIndex:(unsigned long long)index attributeType:(unsigned long long)type flags:(struct MTLAttributeFlags { union { struct { unsigned int x0:1; unsigned int x1:1; unsigned int x2:1; unsigned int x3:5; } x0; unsigned char x1; } x0; })flags;
- (void)dealloc;
- (signed char)isActive;
- (signed char)isPatchData;
- (signed char)isPatchControlPointData;
- (void)setAttributeType:(unsigned long long)type;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;
- (id)name;
- (unsigned long long)attributeIndex;
- (unsigned long long)attributeType;

@end

#endif /* MTLVertexAttributeInternal_h */
