//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.7, SDK: 15.7, Tool: ld (1167.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 18.7, SDK: 18.7, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 368.52.0.0.0
//
#ifndef MTLComputePipelineState_Protocol_h
#define MTLComputePipelineState_Protocol_h
@import Foundation;

#include "MTLDevice-Protocol.h"
#include "NSObject-Protocol.h"

@class NSString;

@protocol MTLComputePipelineState <NSObject>

@required

@property (readonly) NSString *label;
@property (readonly) id <MTLDevice> device;
@property (readonly) unsigned long long maxTotalThreadsPerThreadgroup;
@property (readonly) unsigned long long threadExecutionWidth;
@property (readonly) unsigned long long staticThreadgroupMemoryLength;
@property (readonly) signed char supportIndirectCommandBuffers;
@property (readonly) struct MTLResourceID { unsigned long long x0; } gpuResourceID;
@property (readonly, nonatomic) long long shaderValidation;

/* required instance methods */
- (unsigned long long)imageblockMemoryLengthForDimensions:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })dimensions;
- (id)functionHandleWithFunction:(id)function;
- (id)newComputePipelineStateWithAdditionalBinaryFunctions:(id)functions error:(id *)error;
- (id)newVisibleFunctionTableWithDescriptor:(id)descriptor;
- (id)newIntersectionFunctionTableWithDescriptor:(id)descriptor;

@optional

@end

#endif /* MTLComputePipelineState_Protocol_h */
