//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.7, SDK: 15.7, Tool: ld (1167.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 18.7, SDK: 18.7, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 368.52.0.0.0
//
#ifndef MTLDrawable_Protocol_h
#define MTLDrawable_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol MTLDrawable <NSObject>

@required

@property (readonly, nonatomic) double presentedTime;
@property (readonly, nonatomic) unsigned long long drawableID;

/* required instance methods */
- (void)present;
- (void)presentAtTime:(double)time;
- (void)presentAfterMinimumDuration:(double)duration;
- (void)addPresentedHandler:(id /* block */)handler;

@optional

@end

#endif /* MTLDrawable_Protocol_h */
