//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.7, SDK: 15.7, Tool: ld (1167.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 18.7, SDK: 18.7, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 368.52.0.0.0
//
#ifndef MTLIndexedConstantValue_h
#define MTLIndexedConstantValue_h
@import Foundation;

@class NSObject;

@interface MTLIndexedConstantValue : NSObject

@property (readonly) unsigned long long index;
@property (readonly) unsigned long long dataType;
@property (readonly) void * data;

/* instance methods */
- (id)initWithValue:(const void *)value type:(unsigned long long)type index:(unsigned long long)index;
- (void)dealloc;
- (id)describe;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;

@end

#endif /* MTLIndexedConstantValue_h */
