//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.7, SDK: 15.7, Tool: ld (1167.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 18.7, SDK: 18.7, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 368.52.0.0.0
//
#ifndef MTLImageBlockArgument_h
#define MTLImageBlockArgument_h
@import Foundation;

#include "MTLBindingInternal.h"
#include "MTLStructTypeInternal.h"

@interface MTLImageBlockArgument : MTLBindingInternal {
    /* instance variables */
    unsigned long long _kind;
    unsigned int _dataSize;
    MTLStructTypeInternal *_masterStructMembers;
    _Bool _aliasImplicitImageBlock;
    unsigned int _aliasImplicitImageBlockRenderTarget;
}

/* instance methods */
- (id)initWithName:(id)name type:(unsigned long long)type access:(unsigned long long)access isActive:(signed char)active index:(unsigned long long)index kind:(unsigned long long)kind dataSize:(unsigned int)size masterStructMembers:(id)members aliasImplicitImageBlock:(_Bool)block aliasImplicitImageBlockRenderTarget:(unsigned int)target;
- (void)dealloc;
- (unsigned long long)imageBlockKind;
- (unsigned long long)imageBlockDataSize;
- (id)imageBlockMasterStructMembers;
- (signed char)aliasImplicitImageBlock;
- (unsigned long long)aliasImplicitImageBlockRenderTarget;
- (void)setStructType:(id)type;
- (signed char)isEqual:(id)equal;

@end

#endif /* MTLImageBlockArgument_h */
