//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.7, SDK: 15.7, Tool: ld (1167.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 18.7, SDK: 18.7, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 368.52.0.0.0
//
#ifndef MTLProgramAddressTable_Protocol_h
#define MTLProgramAddressTable_Protocol_h
@import Foundation;

@class NSArray, NSDictionary;

@protocol MTLProgramAddressTable

@required

@property (readonly) NSArray *binaryMappingsEncoderInternal;
@property (readonly) NSArray *binaryMappingsPerInvocation;
@property (readonly) NSDictionary *encoderInternalBinaries;

@optional

@end

#endif /* MTLProgramAddressTable_Protocol_h */
