//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.7, SDK: 15.7, Tool: ld (1167.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 18.7, SDK: 18.7, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 368.52.0.0.0
//
#ifndef MTLRasterizationRateMapSPI_Protocol_h
#define MTLRasterizationRateMapSPI_Protocol_h
@import Foundation;

#include "MTLRasterizationRateMap-Protocol.h"

@protocol MTLRasterizationRateMapSPI <MTLRasterizationRateMap>

@required

@property (readonly, nonatomic) unsigned long long mutability;
@property (readonly, nonatomic) float minFactor;

/* required instance methods */
- (id)formattedDescription:(unsigned long long)description;
- (void)resetUsingDescriptor:(id)descriptor;

@optional

@end

#endif /* MTLRasterizationRateMapSPI_Protocol_h */
