//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLAccelerationStructurePassDescriptorInternal_h
#define MTLAccelerationStructurePassDescriptorInternal_h
@import Foundation;

@interface MTLAccelerationStructurePassDescriptorInternal : 

@property (nonatomic) signed char enableSubstreams;

/* instance methods */
- (id)init;

@end

#endif /* MTLAccelerationStructurePassDescriptorInternal_h */
