//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLBindingInternal_h
#define MTLBindingInternal_h
@import Foundation;

#include "MTLArgument.h"
#include "MTLArgumentCompat-Protocol.h"
#include "MTLBinding-Protocol.h"
#include "MTLPointerType.h"
#include "MTLStructType.h"
#include "MTLStructTypeInternal.h"
#include "MTLType.h"

@class NSString;

@interface MTLBindingInternal :  <MTLArgumentCompat, MTLBinding> {
    /* instance variables */
    MTLType *_typeInfo;
}

@property signed char isUsed;
@property signed char argument;
@property (readonly) unsigned long long bufferAlignment;
@property (readonly) unsigned long long bufferDataSize;
@property (readonly) unsigned long long bufferDataType;
@property (readonly) MTLStructType *bufferStructType;
@property (readonly) MTLPointerType *bufferPointerType;
@property (readonly) unsigned long long threadgroupMemoryAlignment;
@property (readonly) unsigned long long threadgroupMemoryDataSize;
@property (readonly) unsigned long long textureType;
@property (readonly) unsigned long long textureDataType;
@property (readonly) signed char isDepthTexture;
@property (readonly) unsigned long long objectPayloadAlignment;
@property (readonly) unsigned long long objectPayloadDataSize;
@property (readonly) unsigned long long meshVertexCount;
@property (readonly) unsigned long long meshPrimitiveCount;
@property (readonly) unsigned long long meshTopologyType;
@property (readonly) MTLStructTypeInternal *meshVertexStruct;
@property (readonly) MTLStructTypeInternal *meshPrimitiveStruct;
@property (readonly) MTLArgument *bufferIndirectArgumentType;
@property (readonly) unsigned long long indirectConstantAlignment;
@property (readonly) unsigned long long indirectConstantDataSize;
@property (readonly) unsigned long long indirectConstantDataType;
@property (readonly) unsigned long long bufferPixelFormat;
@property (readonly) unsigned long long bufferALUType;
@property (readonly) MTLStructType *structType;
@property (readonly) unsigned long long builtInType;
@property (readonly) unsigned long long builtInDataType;
@property (readonly) unsigned long long imageBlockKind;
@property (readonly) unsigned long long imageBlockDataSize;
@property (readonly) MTLStructTypeInternal *imageBlockMasterStructMembers;
@property (readonly) signed char aliasImplicitImageBlock;
@property (readonly) unsigned long long aliasImplicitImageBlockRenderTarget;
@property (readonly) signed char vertexDescriptorBuffer;
@property (readonly) unsigned long long threadgroupMemoryDataType;
@property (readonly) MTLStructType *threadgroupMemoryStructType;
@property (readonly) NSString *name;
@property (readonly) long long type;
@property (readonly) unsigned long long access;
@property (readonly) unsigned long long index;
@property (readonly) signed char active;
@property (readonly) unsigned long long arrayLength;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) signed char used;

/* instance methods */
- (id)initWithName:(id)name type:(unsigned long long)type access:(unsigned long long)access index:(unsigned long long)index active:(signed char)active arrayLength:(unsigned long long)length;
- (id)initWithName:(id)name type:(unsigned long long)type access:(unsigned long long)access index:(unsigned long long)index active:(signed char)active arrayLength:(unsigned long long)length typeDescription:(id)description;
- (void)dealloc;
- (id)dataTypeDescription;
- (id)formattedDescription:(unsigned long long)description withPrintedTypes:(id)types;
- (id)formattedDescription:(unsigned long long)description;
- (signed char)isActive;
- (signed char)isEqual:(id)equal;
- (signed char)isArgument;
- (void)setIsArgument:(signed char)argument;
- (signed char)isVertexDescriptorBuffer;

@end

#endif /* MTLBindingInternal_h */
