//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLBinaryKey_h
#define MTLBinaryKey_h
@import Foundation;

#include "NSCopying-Protocol.h"

@class NSObject;

@interface MTLBinaryKey : NSObject <NSCopying> {
    /* instance variables */
    struct MTLFunctionId { struct { unsigned char x0[32]; } x0; struct { unsigned char x10[32]; } x[4]; unsigned int x2; } * _id;
}

@property (readonly) const struct { unsigned char x0[32]; } * value;

/* instance methods */
- (id)initWithHash:(const struct MTLMultiHashKey { struct { unsigned char x0[32]; } x0; struct { unsigned char x10[32]; } x[4]; unsigned int x2; } *)hash;
- (signed char)isEqualToKey:(id)key;
- (signed char)isEqual:(id)equal;
- (const struct MTLFunctionId { struct { unsigned char x0[32]; } x0; struct { unsigned char x10[32]; } x[4]; unsigned int x2; } *)getFunctionId;
- (void)dealloc;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;

@end

#endif /* MTLBinaryKey_h */
