//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLBinding_Protocol_h
#define MTLBinding_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@class NSString;

@protocol MTLBinding <NSObject>

@required

@property (readonly) NSString *name;
@property (readonly) long long type;
@property (readonly) unsigned long long access;
@property (readonly) unsigned long long index;
@property (readonly) signed char used;
@property (readonly) signed char argument;

/* required instance methods */
- (signed char)isUsed;
- (signed char)isArgument;

@optional

@end

#endif /* MTLBinding_Protocol_h */
