//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLDebugSubProgram_h
#define MTLDebugSubProgram_h
@import Foundation;

#include "MTLDebugInstrumentationData.h"

@class NSObject, NSString;

@interface MTLDebugSubProgram : NSObject {
    /* instance variables */
    MTLDebugInstrumentationData *_data;
    struct DebugSubProgram { unsigned int x0; unsigned int x1; unsigned int x2; } * _debugSubProgram;
}

@property (readonly, nonatomic) NSString *filename;
@property (readonly, nonatomic) NSString *name;
@property (readonly, nonatomic) unsigned int line;

/* instance methods */
- (id)retain;
- (oneway void)release;
- (oneway void)releaseInternal;

@end

#endif /* MTLDebugSubProgram_h */
