//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLIOScratchBufferAllocator_Protocol_h
#define MTLIOScratchBufferAllocator_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol MTLIOScratchBufferAllocator <NSObject>

@required

/* required instance methods */
- (id)newScratchBufferWithMinimumSize:(unsigned long long)size;

@optional

@end

#endif /* MTLIOScratchBufferAllocator_Protocol_h */
