//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLIOCommandBuffer_Protocol_h
#define MTLIOCommandBuffer_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@class NSError, NSString;

@protocol MTLIOCommandBuffer <NSObject>

@required

@property (copy) NSString *label;
@property (readonly) long long status;
@property (readonly) NSError *error;

/* required instance methods */
- (void)addCompletedHandler:(id /* block */)handler;
- (void)loadBytes:(void *)bytes size:(unsigned long long)size sourceHandle:(id)handle sourceHandleOffset:(unsigned long long)offset;
- (void)loadBuffer:(id)buffer offset:(unsigned long long)offset size:(unsigned long long)size sourceHandle:(id)handle sourceHandleOffset:(unsigned long long)offset;
- (void)loadTexture:(id)texture slice:(unsigned long long)slice level:(unsigned long long)level size:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })size sourceBytesPerRow:(unsigned long long)row sourceBytesPerImage:(unsigned long long)image destinationOrigin:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })origin sourceHandle:(id)handle sourceHandleOffset:(unsigned long long)offset;
- (void)copyStatusToBuffer:(id)buffer offset:(unsigned long long)offset;
- (void)commit;
- (void)waitUntilCompleted;
- (void)tryCancel;
- (void)addBarrier;
- (void)pushDebugGroup:(id)group;
- (void)popDebugGroup;
- (void)enqueue;
- (void)waitForEvent:(id)event value:(unsigned long long)value;
- (void)signalEvent:(id)event value:(unsigned long long)value;

@optional

@end

#endif /* MTLIOCommandBuffer_Protocol_h */
