//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLInferredInput_h
#define MTLInferredInput_h
@import Foundation;

@class NSObject;

@interface MTLInferredInput : NSObject

@property (readonly) unsigned long long dataType;
@property (readonly) unsigned long long pixelFormat;
@property (readonly) unsigned long long aluType;
@property (readonly) unsigned long long offset;
@property (readonly) unsigned long long bufferIndex;
@property (readonly) unsigned long long stride;
@property (readonly) unsigned long long stepFunction;
@property (readonly) unsigned long long stepRate;
@property (readonly) signed char baseInstanceUnused;

/* instance methods */
- (id)initWithDataType:(unsigned long long)type pixelFormat:(unsigned long long)format aluType:(unsigned long long)type offset:(unsigned long long)offset bufferIndex:(unsigned long long)index stride:(unsigned long long)stride stepFunction:(unsigned long long)function stepRate:(unsigned long long)rate baseInstanceUnused:(signed char)unused;
- (id)formattedDescription:(unsigned long long)description withPrintedTypes:(id)types;
- (id)description;

@end

#endif /* MTLInferredInput_h */
