//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLLibrarySPI_Protocol_h
#define MTLLibrarySPI_Protocol_h
@import Foundation;

#include "MTLLibrary-Protocol.h"

@class NSArray, NSData, NSString, NSUUID;

@protocol MTLLibrarySPI <MTLLibrary>

@required

@property (copy) NSString *overrideTriple;
@property (nonatomic) signed char shaderValidationEnabled;
@property (readonly) NSArray *externFunctionNames;
@property (readonly) NSData *bitcodeData;
@property (readonly, copy) NSUUID *libraryIdentifier;

/* required instance methods */
- (id)newExternFunctionWithName:(id)name;
- (id)newFunctionWithName:(id)name constantValues:(id)values functionCache:(id)cache error:(id *)error;
- (id)newFunctionWithName:(id)name constantValues:(id)values pipelineLibrary:(id)library error:(id *)error;
- (void)newFunctionWithName:(id)name constantValues:(id)values pipelineLibrary:(id)library completionHandler:(id /* block */)handler;
- (id)newFunctionWithDescriptor:(id)descriptor destinationArchive:(id)archive error:(id *)error;
- (signed char)serializeToURL:(id)url error:(id *)error;

@optional

@end

#endif /* MTLLibrarySPI_Protocol_h */
