//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLParallelRenderCommandEncoder_Protocol_h
#define MTLParallelRenderCommandEncoder_Protocol_h
@import Foundation;

#include "MTLCommandEncoder-Protocol.h"

@protocol MTLParallelRenderCommandEncoder <MTLCommandEncoder>

@required

/* required instance methods */
- (id)renderCommandEncoder;
- (void)setColorStoreAction:(unsigned long long)action atIndex:(unsigned long long)index;
- (void)setDepthStoreAction:(unsigned long long)action;
- (void)setStencilStoreAction:(unsigned long long)action;
- (void)setColorStoreActionOptions:(unsigned long long)options atIndex:(unsigned long long)index;
- (void)setDepthStoreActionOptions:(unsigned long long)options;
- (void)setStencilStoreActionOptions:(unsigned long long)options;

@optional

@end

#endif /* MTLParallelRenderCommandEncoder_Protocol_h */
