//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLRenderPipelineReflectionInternal_h
#define MTLRenderPipelineReflectionInternal_h
@import Foundation;

#include "MTLBinding-Protocol.h"

@class NSArray, NSData, NSDictionary;

@interface MTLRenderPipelineReflectionInternal :  {
    /* instance variables */
    struct { unsigned int fragmentUsesDiscard:1; unsigned int fragmentWritesSampleMask:1; unsigned int fragmentWritesDepth:1; unsigned int vertexRegisterSpill:1; unsigned int fragmentRegisterSpill:1; unsigned int fragmentReadsFramebufferValues:1; unsigned int fragmentPunchThrough:1; unsigned int vertexWritesPointSize:1; unsigned int private2:1; unsigned int vertexThreadInvariantRegisterSpill:1; unsigned int fragmentThreadInvariantRegisterSpill:1; unsigned int reserved:53; } _flags;
    NSArray *_vertexBuiltInArguments;
    unsigned long long _postVertexDumpStride;
    NSArray *_postVertexDumpOutputs;
    NSArray *_inferredInputs;
    NSArray *_vertexArguments;
    NSArray *_fragmentArguments;
    NSArray *_tileArguments;
    NSArray *_tileBuiltInArguments;
    id <MTLBinding> _imageBlockDataReturn;
    NSDictionary *_performanceStatistics;
    unsigned int _traceBufferIndex;
    NSData *_vertexPluginReturnData;
    NSData *_fragmentPluginReturnData;
    NSArray *_constantSamplerUniqueIdentifiers;
    NSArray *_constantSamplerDescriptors;
    NSDictionary *_vertexResourceBindingIndexRemappingTable;
    NSDictionary *_fragmentResourceBindingIndexRemappingTable;
    NSDictionary *_objectResourceBindingIndexRemappingTable;
    NSDictionary *_meshResourceBindingIndexRemappingTable;
    NSArray *_objectArguments;
    NSArray *_meshArguments;
    NSArray *_objectBuiltInArguments;
    NSArray *_meshBuiltInArguments;
    NSData *_objectPluginReturnData;
    NSData *_meshPluginReturnData;
    NSArray *_vertexBindings;
    NSArray *_fragmentBindings;
    NSArray *_tileBindings;
    NSArray *_objectBindings;
    NSArray *_meshBindings;
    NSDictionary *_tileResourceBindingIndexRemappingTable;
    unsigned long long _printStyle;
}

/* instance methods */
- (id)initWithVertexData:(id)data fragmentData:(id)data serializedVertexDescriptor:(id)descriptor device:(id)device options:(unsigned long long)options flags:(struct { unsigned int x0:1; unsigned int x1:1; unsigned int x2:1; unsigned int x3:1; unsigned int x4:1; unsigned int x5:1; unsigned int x6:1; unsigned int x7:1; unsigned int x8:1; unsigned int x9:1; unsigned int x10:1; unsigned int x11:53; })flags;
- (id)initWithTileData:(id)data functionType:(unsigned long long)type device:(id)device options:(unsigned long long)options flags:(struct { unsigned int x0:1; unsigned int x1:1; unsigned int x2:1; unsigned int x3:1; unsigned int x4:1; unsigned int x5:1; unsigned int x6:1; unsigned int x7:1; unsigned int x8:1; unsigned int x9:1; unsigned int x10:1; unsigned int x11:53; })flags;
- (id)initWithObjectData:(id)data meshData:(id)data fragmentData:(id)data device:(id)device options:(unsigned long long)options flags:(struct { unsigned int x0:1; unsigned int x1:1; unsigned int x2:1; unsigned int x3:1; unsigned int x4:1; unsigned int x5:1; unsigned int x6:1; unsigned int x7:1; unsigned int x8:1; unsigned int x9:1; unsigned int x10:1; unsigned int x11:53; })flags;
- (void)dealloc;
- (void)setPerformanceStatistics:(id)statistics;
- (id)performanceStatistics;
- (unsigned int)traceBufferIndex;
- (id)vertexPluginReturnData;
- (id)fragmentPluginReturnData;
- (id)constantSamplerUniqueIdentifiers;
- (id)constantSamplerDescriptors;
- (void)setConstantSamplerUniqueIdentifiers:(id)identifiers;
- (void)setConstantSamplerDescriptorsFromBitmasks:(unsigned long long *)bitmasks count:(unsigned long long)count;
- (void)setConstantSamplerDescriptorsFromBitmasks:(unsigned long long *)bitmasks stride:(unsigned int)stride count:(unsigned long long)count;
- (id)vertexResourceBindingIndexRemappingTable;
- (void)setVertexResourceBindingIndexRemappingTable:(id)table;
- (id)fragmentResourceBindingIndexRemappingTable;
- (void)setFragmentResourceBindingIndexRemappingTable:(id)table;
- (id)tileResourceBindingIndexRemappingTable;
- (void)setTileResourceBindingIndexRemappingTable:(id)table;
- (id)objectResourceBindingIndexRemappingTable;
- (void)setObjectResourceBindingIndexRemappingTable:(id)table;
- (id)meshResourceBindingIndexRemappingTable;
- (void)setMeshResourceBindingIndexRemappingTable:(id)table;
- (struct { unsigned int x0:1; unsigned int x1:1; unsigned int x2:1; unsigned int x3:1; unsigned int x4:1; unsigned int x5:1; unsigned int x6:1; unsigned int x7:1; unsigned int x8:1; unsigned int x9:1; unsigned int x10:1; unsigned int x11:53; })usageFlags;
- (id)vertexBuiltInArguments;
- (unsigned long long)postVertexDumpStride;
- (id)postVertexDumpOutputs;
- (id)inferredInputs;
- (id)vertexArguments;
- (id)fragmentArguments;
- (id)tileArguments;
- (id)imageBlockDataReturn;
- (id)objectArguments;
- (id)meshArguments;
- (id)objectBuiltInArguments;
- (id)meshBuiltInArguments;
- (id)objectPluginReturnData;
- (id)meshPluginReturnData;
- (id)vertexBindings;
- (id)fragmentBindings;
- (id)tileBindings;
- (id)objectBindings;
- (id)meshBindings;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;

@end

#endif /* MTLRenderPipelineReflectionInternal_h */
