//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLRenderPassColorAttachmentDescriptorArrayInternal_h
#define MTLRenderPassColorAttachmentDescriptorArrayInternal_h
@import Foundation;

#include "MTLRenderPassDepthAttachmentDescriptorInternal.h"
#include "MTLRenderPassStencilAttachmentDescriptorInternal.h"

@interface MTLRenderPassColorAttachmentDescriptorArrayInternal :  {
    /* instance variables */
    MTLRenderPassColorAttachmentDescriptorInternal *_color_descriptors[8];
    MTLRenderPassDepthAttachmentDescriptorInternal *_depth_descriptor;
    MTLRenderPassStencilAttachmentDescriptorInternal *_stencil_descriptor;
}

/* instance methods */
- (void)dealloc;
- (id)objectAtIndexedSubscript:(unsigned long long)subscript;
- (void)setObject:(id)object atIndexedSubscript:(unsigned long long)subscript;
- (id)_descriptorAtIndex:(unsigned long long)index;

@end

#endif /* MTLRenderPassColorAttachmentDescriptorArrayInternal_h */
