//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLRelocation_Protocol_h
#define MTLRelocation_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@class NSString;

@protocol MTLRelocation <NSObject>

@required

@property (readonly, nonatomic) NSString *symbolName;

@optional

@end

#endif /* MTLRelocation_Protocol_h */
