//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLResourceStatePassDescriptorInternal_h
#define MTLResourceStatePassDescriptorInternal_h
@import Foundation;

#include "MTLResourceStatePassSampleBufferAttachmentDescriptorArrayInternal.h"

@interface MTLResourceStatePassDescriptorInternal :  {
    /* instance variables */
    struct MTLResourceStatePassDescriptorPrivate { MTLResourceStatePassSampleBufferAttachmentDescriptorArrayInternal *sampleBufferAttachments; } _private;
}

/* class methods */
+ (id)resourceStatePassDescriptor;

/* instance methods */
- (id)init;
- (void)dealloc;
- (unsigned long long)hash;
- (signed char)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (const struct MTLResourceStatePassDescriptorPrivate { id x0; } *)_descriptorPrivate;
- (id)sampleBufferAttachments;

@end

#endif /* MTLResourceStatePassDescriptorInternal_h */
