//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLRasterizationRateMapDescriptorSPI_Protocol_h
#define MTLRasterizationRateMapDescriptorSPI_Protocol_h
@import Foundation;

@protocol MTLRasterizationRateMapDescriptorSPI

@required

@property (nonatomic) signed char skipSampleValidationAndInterpolation;
@property (nonatomic) signed char skipSampleValidationAndApplySampleAtTileGranularity;
@property (nonatomic) unsigned long long mutability;
@property (nonatomic) float minFactor;

/* required instance methods */
- (id)initWithScreenSize:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })size;
- (const id *)layerPointer:(unsigned long long *)pointer;
- (id)formattedDescription:(unsigned long long)description;

@optional

@end

#endif /* MTLRasterizationRateMapDescriptorSPI_Protocol_h */
