//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLRenderPipelineState_Protocol_h
#define MTLRenderPipelineState_Protocol_h
@import Foundation;

#include "MTLDevice-Protocol.h"
#include "NSObject-Protocol.h"

@class NSString;

@protocol MTLRenderPipelineState <NSObject>

@required

@property (readonly) NSString *label;
@property (readonly) id <MTLDevice> device;
@property (readonly) unsigned long long maxTotalThreadsPerThreadgroup;
@property (readonly) signed char threadgroupSizeMatchesTileSize;
@property (readonly) unsigned long long imageblockSampleLength;
@property (readonly) signed char supportIndirectCommandBuffers;
@property (readonly) unsigned long long maxTotalThreadsPerObjectThreadgroup;
@property (readonly) unsigned long long maxTotalThreadsPerMeshThreadgroup;
@property (readonly) unsigned long long objectThreadExecutionWidth;
@property (readonly) unsigned long long meshThreadExecutionWidth;
@property (readonly) unsigned long long maxTotalThreadgroupsPerMeshGrid;
@property (readonly) struct MTLResourceID { unsigned long long x0; } gpuResourceID;

/* required instance methods */
- (unsigned long long)imageblockMemoryLengthForDimensions:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })dimensions;
- (id)functionHandleWithFunction:(id)function stage:(unsigned long long)stage;
- (id)newVisibleFunctionTableWithDescriptor:(id)descriptor stage:(unsigned long long)stage;
- (id)newIntersectionFunctionTableWithDescriptor:(id)descriptor stage:(unsigned long long)stage;
- (id)newRenderPipelineStateWithAdditionalBinaryFunctions:(id)functions error:(id *)error;

@optional

@end

#endif /* MTLRenderPipelineState_Protocol_h */
