//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLSamplerDescriptorInternal_h
#define MTLSamplerDescriptorInternal_h
@import Foundation;

@class NSString;

@interface MTLSamplerDescriptorInternal :  {
    /* instance variables */
    struct MTLSamplerDescriptorPrivate { union { struct { unsigned int minFilter:2; unsigned int magFilter:2; unsigned int mipFilter:2; unsigned int sAddressMode:3; unsigned int tAddressMode:3; unsigned int rAddressMode:3; unsigned int normalizedCoords:1; unsigned int borderColor:2; unsigned int lodAverage:1; unsigned int compareFunction:3; unsigned int supportArgumentBuffers:1; unsigned int reductionMode:2; unsigned int forceResourceIndex:1; unsigned int forceSeamsOnCubemapFiltering:1; } x0; unsigned int miscHash; } x0; union { unsigned int lodMinClampHash; float lodMinClamp; } x1; union { unsigned int lodMaxClampHash; float lodMaxClamp; } x2; union { unsigned int lodBiasHash; float lodBias; } x3; unsigned long long maxAnisotropy; NSString *label; unsigned long long resourceIndex; unsigned int customBorderColorValue[4]; unsigned long long pixelFormat; } _private;
}

@property (nonatomic) unsigned long long borderColorSPI;
@property (nonatomic) unsigned int customBorderColorValue_0;
@property (nonatomic) unsigned int customBorderColorValue_1;
@property (nonatomic) unsigned int customBorderColorValue_2;
@property (nonatomic) unsigned int customBorderColorValue_3;
@property (nonatomic) unsigned long long reductionMode;
@property (nonatomic) signed char forceSeamsOnCubemapFiltering;

/* instance methods */
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;
- (unsigned long long)minFilter;
- (void)setMinFilter:(unsigned long long)filter;
- (unsigned long long)magFilter;
- (void)setMagFilter:(unsigned long long)filter;
- (unsigned long long)mipFilter;
- (void)setMipFilter:(unsigned long long)filter;
- (unsigned long long)maxAnisotropy;
- (void)setMaxAnisotropy:(unsigned long long)anisotropy;
- (unsigned long long)sAddressMode;
- (void)setSAddressMode:(unsigned long long)mode;
- (unsigned long long)tAddressMode;
- (void)setTAddressMode:(unsigned long long)mode;
- (unsigned long long)rAddressMode;
- (void)setRAddressMode:(unsigned long long)mode;
- (unsigned long long)borderColor;
- (void)setBorderColor:(unsigned long long)color;
- (signed char)normalizedCoordinates;
- (void)setNormalizedCoordinates:(signed char)coordinates;
- (float)lodMinClamp;
- (void)setLodMinClamp:(float)clamp;
- (float)lodMaxClamp;
- (void)setLodMaxClamp:(float)clamp;
- (float)lodBias;
- (void)setLodBias:(float)bias;
- (signed char)lodAverage;
- (void)setLodAverage:(signed char)average;
- (void)setPixelFormat:(unsigned long long)format;
- (unsigned long long)pixelFormat;
- (unsigned long long)compareFunction;
- (void)setCompareFunction:(unsigned long long)function;
- (signed char)supportArgumentBuffers;
- (void)setSupportArgumentBuffers:(signed char)buffers;
- (signed char)forceResourceIndex;
- (void)setForceResourceIndex:(signed char)index;
- (unsigned long long)resourceIndex;
- (void)setResourceIndex:(unsigned long long)index;
- (id)label;
- (void)setLabel:(id)label;
- (unsigned long long)hash;
- (signed char)isEqual:(id)equal;
- (const struct MTLSamplerDescriptorPrivate { union { struct { unsigned int x0:2; unsigned int x1:2; unsigned int x2:2; unsigned int x3:3; unsigned int x4:3; unsigned int x5:3; unsigned int x6:1; unsigned int x7:2; unsigned int x8:1; unsigned int x9:3; unsigned int x10:1; unsigned int x11:2; unsigned int x12:1; unsigned int x13:1; } x0; unsigned int x1; } x0; union { unsigned int x0; float x1; } x1; union { unsigned int x0; float x1; } x2; union { unsigned int x0; float x1; } x3; unsigned long long x4; id x5; unsigned long long x6; unsigned int x7[4]; unsigned long long x8; } *)descriptorPrivate;

@end

#endif /* MTLSamplerDescriptorInternal_h */
