//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.8, SDK: 14.8, Tool: ld (951.51)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.8, SDK: 17.8, Tool: ld (951.51)
//    - LC_SOURCE_VERSION: 343.21.0.0.0
//
#ifndef MTLVisibleFunctionTableDescriptorInternal_h
#define MTLVisibleFunctionTableDescriptorInternal_h
@import Foundation;

@interface MTLVisibleFunctionTableDescriptorInternal :  {
    /* instance variables */
    struct MTLVisibleFunctionTableDescriptorPrivate { unsigned long long functionCount; signed char forceResourceIndex; unsigned long long resourceIndex; } _private;
}

/* class methods */
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (unsigned long long)functionCount;
- (void)setFunctionCount:(unsigned long long)count;
- (signed char)forceResourceIndex;
- (void)setForceResourceIndex:(signed char)index;
- (unsigned long long)resourceIndex;
- (void)setResourceIndex:(unsigned long long)index;
- (unsigned long long)hash;
- (signed char)isEqual:(id)equal;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;

@end

#endif /* MTLVisibleFunctionTableDescriptorInternal_h */
