//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef _MTLRenderPipelineState_h
#define _MTLRenderPipelineState_h
@import Foundation;

#include "MTLDebugInstrumentationData.h"
#include "MTLDevice-Protocol.h"
#include "MTLRenderPipelineState-Protocol.h"

@class NSObject, NSString;

@interface _MTLRenderPipelineState : NSObject <MTLRenderPipelineState>

@property (readonly) NSString *label;
@property (readonly) id <MTLDevice> device;
@property (retain, nonatomic) MTLDebugInstrumentationData *vertexDebugInstrumentationData;
@property (retain, nonatomic) MTLDebugInstrumentationData *fragmentDebugInstrumentationData;
@property (retain, nonatomic) MTLDebugInstrumentationData *tileDebugInstrumentationData;
@property (readonly) long long textureWriteRoundingMode;
@property (readonly) unsigned long long uniqueIdentifier;
@property (readonly, nonatomic) unsigned long long resourceIndex;
@property (readonly, nonatomic) unsigned long long gpuAddress;
@property (readonly, nonatomic) unsigned long long allocatedSize;
@property (readonly) unsigned long long imageBlockSampleLength;
@property (readonly) unsigned long long maxTotalThreadsPerThreadgroup;
@property (readonly) signed char threadgroupSizeMatchesTileSize;
@property (readonly) unsigned long long imageblockSampleLength;
@property (readonly) signed char supportIndirectCommandBuffers;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithDevice:(id)device pipelineStateDescriptor:(id)descriptor;
- (id)initWithDeviceAndTileDesc:(id)desc tilePipelineStateDescriptor:(id)descriptor;
- (id)initWithParent:(id)parent;
- (id)initWithTileParent:(id)parent;
- (void)dealloc;
- (unsigned int)getVertexShaderTelemetryID;
- (unsigned int)getFragmentShaderTelemetryID;
- (unsigned long long)imageblockMemoryLengthForDimensions:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })dimensions;
- (long long)textureWriteFPRoundingMode;
- (id)vertexFunctionHandleWithFunction:(id)function;
- (id)fragmentFunctionHandleWithFunction:(id)function;
- (id)tileFunctionHandleWithFunction:(id)function;
- (id)functionHandleWithFunction:(id)function stage:(unsigned long long)stage;
- (id)newVisibleFunctionTableFromVertexStageWithDescriptor:(id)descriptor;
- (id)newVisibleFunctionTableFromFragmentStageWithDescriptor:(id)descriptor;
- (id)newVisibleFunctionTableFromTileStageWithDescriptor:(id)descriptor;
- (id)newVisibleFunctionTableWithDescriptor:(id)descriptor stage:(unsigned long long)stage;
- (id)newRenderPipelineStateWithAdditionalBinaryFunctions:(id)functions fragmentAdditionalBinaryFunctions:(id)functions error:(id *)error;
- (id)newTileRenderPipelineStateWithAdditionalBinaryFunctions:(id)functions error:(id *)error;
- (id)newRenderPipelineStateWithAdditionalBinaryFunctions:(id)functions error:(id *)error;
- (id)newVertexIntersectionFunctionTableWithDescriptor:(id)descriptor;
- (id)newFragmentIntersectionFunctionTableWithDescriptor:(id)descriptor;
- (id)newTileIntersectionFunctionTableWithDescriptor:(id)descriptor;
- (id)newIntersectionFunctionTableWithDescriptor:(id)descriptor stage:(unsigned long long)stage;

@end

#endif /* _MTLRenderPipelineState_h */
