//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef _MTLCommandBufferEncoderInfo_h
#define _MTLCommandBufferEncoderInfo_h
@import Foundation;

#include "MTLCommandBufferEncoderInfo-Protocol.h"

@class NSArray, NSObject, NSString;

@interface _MTLCommandBufferEncoderInfo : NSObject <MTLCommandBufferEncoderInfo>

@property (nonatomic) unsigned long long uniqueID;
@property (nonatomic) unsigned long long globalTraceObjectID;
@property (retain, nonatomic) NSString *label;
@property (retain, nonatomic) NSArray *debugSignposts;
@property (nonatomic) long long errorState;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;

@end

#endif /* _MTLCommandBufferEncoderInfo_h */
