//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef _MTLIndirectDrawIndexedArguments_h
#define _MTLIndirectDrawIndexedArguments_h
@import Foundation;

@class NSObject;

@interface _MTLIndirectDrawIndexedArguments : NSObject

@property (nonatomic) unsigned long long primitiveType;
@property (nonatomic) unsigned long long indexCount;
@property (nonatomic) unsigned long long indexType;
@property (nonatomic) void * indexBufferVirtualAddress;
@property (nonatomic) unsigned long long indexBufferOffset;
@property (nonatomic) unsigned long long instanceCount;
@property (nonatomic) unsigned long long baseVertex;
@property (nonatomic) unsigned long long baseInstance;

@end

#endif /* _MTLIndirectDrawIndexedArguments_h */
