//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef _MTLSharedEvent_h
#define _MTLSharedEvent_h
@import Foundation;

#include "MTLDevice-Protocol.h"
#include "MTLSharedEventSPI-Protocol.h"

@class IOSurfaceSharedEvent, NSString;

@interface _MTLSharedEvent : IOSurfaceSharedEvent <MTLSharedEventSPI> {
    /* instance variables */
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _labelLock;
}

@property (readonly) id <MTLDevice> device;
@property (copy) NSString *label;
@property (readonly) unsigned long long labelTraceID;
@property unsigned long long signaledValue;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (unsigned int)encodeKernelSignalEventCommandArgs:(struct IOAccelKernelCommandSignalOrWaitEventArgs { unsigned int x0; unsigned short x1; unsigned short x2; unsigned long long x3; } *)args value:(unsigned long long)value;
- (unsigned int)encodeKernelWaitEventCommandArgs:(struct IOAccelKernelCommandSignalOrWaitEventArgs { unsigned int x0; unsigned short x1; unsigned short x2; unsigned long long x3; } *)args value:(unsigned long long)value;
- (unsigned int)encodeKernelWaitEventCommandArgs:(struct IOAccelKernelCommandSignalOrWaitEventArgs { unsigned int x0; unsigned short x1; unsigned short x2; unsigned long long x3; } *)args value:(unsigned long long)value timeout:(unsigned int)timeout;
- (void)dealloc;
- (id)initWithSharedEventHandle:(id)handle;
- (id)initWithMachPort:(unsigned int)port;
- (id)newSharedEventHandle;
- (void)notifyListener:(id)listener atValue:(unsigned long long)value block:(id /* block */)block;
- (id)retainedLabel;

@end

#endif /* _MTLSharedEvent_h */
