//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef _MTLComputePipelineState_h
#define _MTLComputePipelineState_h
@import Foundation;

#include "MTLComputePipelineState-Protocol.h"
#include "MTLDebugInstrumentationData.h"
#include "MTLDevice-Protocol.h"

@class NSObject, NSString;

@interface _MTLComputePipelineState : NSObject <MTLComputePipelineState>

@property (readonly) NSString *label;
@property (readonly) id <MTLDevice> device;
@property (retain, nonatomic) MTLDebugInstrumentationData *debugInstrumentationData;
@property (readonly) unsigned long long uniqueIdentifier;
@property (readonly) long long textureWriteRoundingMode;
@property (readonly, nonatomic) unsigned long long resourceIndex;
@property (readonly, nonatomic) unsigned long long gpuAddress;
@property (readonly, nonatomic) unsigned long long allocatedSize;
@property (readonly) unsigned long long maxTotalThreadsPerThreadgroup;
@property (readonly) unsigned long long threadExecutionWidth;
@property (readonly) unsigned long long staticThreadgroupMemoryLength;
@property (readonly) signed char supportIndirectCommandBuffers;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithDevice:(id)device pipelineStateDescriptor:(id)descriptor;
- (id)initWithParent:(id)parent;
- (void)dealloc;
- (id)formattedDescription:(unsigned long long)description;
- (long long)textureWriteFPRoundingMode;
- (unsigned long long)imageblockMemoryLengthForDimensions:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })dimensions;
- (unsigned int)getComputeKernelTelemetryID;
- (id)functionPointerHandleWithFunction:(id)function;
- (id)functionPointerHandlesWithFunctions:(id)functions range:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (id)functionHandleWithFunction:(id)function;
- (id)newVisibleFunctionTableWithDescriptor:(id)descriptor;
- (id)newComputePipelineStateWithAdditionalBinaryFunctions:(id)functions error:(id *)error;
- (id)newIntersectionFunctionTableWithDescriptor:(id)descriptor;

@end

#endif /* _MTLComputePipelineState_h */
