//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef _MTLRasterizationRateMap_h
#define _MTLRasterizationRateMap_h
@import Foundation;

#include "MTLDevice-Protocol.h"
#include "MTLRasterizationRateMapSPI-Protocol.h"

@class NSObject, NSString;

@interface _MTLRasterizationRateMap : NSObject <MTLRasterizationRateMapSPI> {
    /* instance variables */
    struct { unsigned long long width; unsigned long long height; unsigned long long depth; } _dim;
}

@property (readonly) id <MTLDevice> device;
@property (readonly) NSString *label;
@property (readonly) struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } screenSize;
@property (readonly) unsigned long long layerCount;
@property (readonly) struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } physicalGranularity;
@property (readonly) struct { unsigned long long x0; unsigned long long x1; } parameterBufferSizeAndAlign;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (id)initWithDevice:(id)device descriptor:(id)descriptor;
- (void)dealloc;
- (void)copyParameterDataToBuffer:(id)buffer offset:(unsigned long long)offset;
- (void)copyParameterDataToBuffer:(id)buffer atOffset:(unsigned long long)offset;
- (struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })physicalSizeForLayer:(unsigned long long)layer;
- (struct { float x0; float x1; })physicalCoordinate:(struct { float x0; float x1; })coordinate forLayer:(unsigned long long)layer;
- (struct { float x0; float x1; })screenCoordinate:(struct { float x0; float x1; })coordinate forLayer:(unsigned long long)layer;
- (struct { float x0; float x1; })mapScreenToPhysicalCoordinates:(struct { float x0; float x1; })coordinates forLayer:(unsigned long long)layer;
- (struct { float x0; float x1; })mapPhysicalToScreenCoordinates:(struct { float x0; float x1; })coordinates forLayer:(unsigned long long)layer;
- (id)formattedDescription:(unsigned long long)description;

@end

#endif /* _MTLRasterizationRateMap_h */
