//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef _MTLDebugCommandEncoder_h
#define _MTLDebugCommandEncoder_h
@import Foundation;

#include "MTLDebugCommandEncoder-Protocol.h"
#include "MTLDevice-Protocol.h"
#include "_MTLCommandEncoder.h"

@class NSString;

@interface _MTLDebugCommandEncoder : _MTLCommandEncoder <MTLDebugCommandEncoder>

@property (readonly) id <MTLDevice> device;
@property (copy) NSString *label;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)kprintf:(id)kprintf;
- (void)IOLog:(id)iolog;
- (void)kprintfBytes:(const char *)bytes length:(unsigned long long)length;
- (void)IOLogBytes:(const char *)bytes length:(unsigned long long)length;

@end

#endif /* _MTLDebugCommandEncoder_h */
