//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef _MTLHeap_h
#define _MTLHeap_h
@import Foundation;

#include "_MTLObjectWithLabel.h"

@interface _MTLHeap : _MTLObjectWithLabel {
    /* instance variables */
    unsigned long long _heapResourceOptions;
    long long _heapType;
}

@property (readonly) long long type;
@property (readonly) unsigned long long cpuCacheMode;
@property (readonly) unsigned long long storageMode;
@property (readonly) unsigned long long hazardTrackingMode;
@property (readonly) unsigned long long resourceOptions;
@property (readonly) unsigned long long unfilteredResourceOptions;
@property (readonly, nonatomic) unsigned long long gpuAddress;

/* instance methods */
- (id)init;
- (id)initWithType:(long long)type options:(unsigned long long)options;
- (id)newBufferWithLength:(unsigned long long)length options:(unsigned long long)options atOffset:(unsigned long long)offset;
- (id)newTextureWithDescriptor:(id)descriptor atOffset:(unsigned long long)offset;
- (id)newBufferWithLength:(unsigned long long)length options:(unsigned long long)options offset:(unsigned long long)offset;
- (id)newTextureWithDescriptor:(id)descriptor offset:(unsigned long long)offset;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;

@end

#endif /* _MTLHeap_h */
