//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef _MTLCommandBufferDescriptor_h
#define _MTLCommandBufferDescriptor_h
@import Foundation;

#include "MTLCommandBufferDescriptor.h"

@interface _MTLCommandBufferDescriptor : MTLCommandBufferDescriptor {
    /* instance variables */
    signed char _retainedReferences;
    unsigned long long _errorOptions;
}

@property (nonatomic) signed char captureProgramAddressTable;

/* instance methods */
- (id)init;
- (id)copyWithZone:(struct _NSZone *)zone;
- (signed char)retainedReferences;
- (void)setRetainedReferences:(signed char)references;
- (unsigned long long)errorOptions;
- (void)setErrorOptions:(unsigned long long)options;

@end

#endif /* _MTLCommandBufferDescriptor_h */
