//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef _MTLLibrary_h
#define _MTLLibrary_h
@import Foundation;

#include "MTLDevice-Protocol.h"
#include "MTLLibrarySPI-Protocol.h"
#include "_MTLObjectWithLabel.h"

@class NSArray, NSData, NSMutableDictionary, NSString, NSUUID;

@interface _MTLLibrary : _MTLObjectWithLabel <MTLLibrarySPI>

@property (readonly, retain, nonatomic) NSMutableDictionary *functionDictionary;
@property (copy) NSString *label;
@property (readonly) id <MTLDevice> device;
@property (readonly, retain) NSArray *functionNames;
@property (readonly, retain) NSArray *externFunctionNames;
@property (readonly) struct MTLLibraryData { void * /* function */ *x0; struct { unsigned char x0[32]; } x1; _Atomic int x2; id x3; id x4; } * libraryData;
@property (readonly) struct MTLLibraryContainer { struct MTLPipelineCollection *x0; _Atomic int x1; struct { unsigned char x0[32]; } x2; struct MTLLibraryData *x3; id x4; id x5; id x6; id x7; id x8; } * cacheEntry;
@property (copy) NSString *overrideTriple;
@property (nonatomic) signed char shaderValidationEnabled;
@property (readonly, copy) NSUUID *libraryIdentifier;
@property (readonly) NSArray *variableList;
@property (readonly) NSData *bitcodeData;
@property (readonly) long long type;
@property (readonly) NSString *installName;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)libraryDataContents;
- (id)newFunctionWithNameInternal:(id)internal;
- (id)newExternFunctionWithName:(id)name;
- (id)newFunctionWithName:(id)name;
- (id)newFunctionWithName:(id)name constantValues:(id)values functionCache:(id)cache specializedName:(id)name error:(id *)error;
- (id)newFunctionWithName:(id)name constantValues:(id)values error:(id *)error;
- (id)newFunctionWithName:(id)name constantValues:(id)values pipelineLibrary:(id)library error:(id *)error;
- (void)newFunctionWithName:(id)name constantValues:(id)values functionCache:(id)cache specializedName:(id)name completionHandler:(id /* block */)handler;
- (void)newFunctionWithName:(id)name constantValues:(id)values completionHandler:(id /* block */)handler;
- (id)newFunctionWithName:(id)name constantValues:(id)values functionCache:(id)cache error:(id *)error;
- (void)newFunctionWithName:(id)name constantValues:(id)values pipelineLibrary:(id)library completionHandler:(id /* block */)handler;
- (void)newFunctionWithDescriptor:(id)descriptor destinationArchive:(id)archive functionCache:(id)cache completionHandler:(id /* block */)handler;
- (void)newFunctionWithDescriptor:(id)descriptor completionHandler:(id /* block */)handler;
- (id)newSpecializedFunctionWithDescriptorInternal:(id)internal destinationArchive:(id)archive functionCache:(id)cache error:(id *)error;
- (id)newFunctionWithDescriptor:(id)descriptor error:(id *)error;
- (id)newFunctionWithDescriptor:(id)descriptor destinationArchive:(id)archive error:(id *)error;
- (void)newIntersectionFunctionWithDescriptor:(id)descriptor completionHandler:(id /* block */)handler;
- (id)newIntersectionFunctionWithDescriptor:(id)descriptor error:(id *)error;
- (signed char)serializeToURL:(id)url error:(id *)error;
- (id)initWithLibraryContainer:(struct MTLLibraryContainer { struct MTLPipelineCollection *x0; _Atomic int x1; struct { unsigned char x0[32]; } x2; struct MTLLibraryData *x3; id x4; id x5; id x6; id x7; id x8; } *)container device:(id)device;
- (void)dealloc;
- (id)formattedDescription:(unsigned long long)description;

@end

#endif /* _MTLLibrary_h */
