//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef _MTLAccelerationStructureCommandEncoder_h
#define _MTLAccelerationStructureCommandEncoder_h
@import Foundation;

#include "MTLAccelerationStructureCommandEncoderSPI-Protocol.h"
#include "MTLDevice-Protocol.h"
#include "_MTLCommandEncoder.h"

@class NSString;

@interface _MTLAccelerationStructureCommandEncoder : _MTLCommandEncoder <MTLAccelerationStructureCommandEncoderSPI>

@property (readonly) id <MTLDevice> device;
@property (copy) NSString *label;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)buildAccelerationStructure:(id)structure descriptor:(id)descriptor scratchBuffer:(id)buffer scratchBufferOffset:(unsigned long long)offset;
- (void)writeCompactedAccelerationStructureSize:(id)size toBuffer:(id)buffer offset:(unsigned long long)offset;
- (void)writeCompactedAccelerationStructureSize:(id)size toBuffer:(id)buffer offset:(unsigned long long)offset sizeDataType:(unsigned long long)type;
- (void)copyAccelerationStructure:(id)structure toAccelerationStructure:(id)structure;
- (void)copyAndCompactAccelerationStructure:(id)structure toAccelerationStructure:(id)structure;
- (void)refitAccelerationStructure:(id)structure descriptor:(id)descriptor destination:(id)destination scratchBuffer:(id)buffer scratchBufferOffset:(unsigned long long)offset;
- (void)writeSerializedAccelerationStructureSize:(id)size toBuffer:(id)buffer sizeBufferOffset:(unsigned long long)offset;
- (void)writeDeserializedAccelerationStructureSize:(id)size serializedOffset:(unsigned long long)offset toBuffer:(id)buffer sizeBufferOffset:(unsigned long long)offset;
- (void)writeDeserializedPrimitiveAccelerationStructureSizes:(id)sizes serializedOffset:(unsigned long long)offset toBuffer:(id)buffer sizesBufferOffset:(unsigned long long)offset;
- (void)serializePrimitiveAccelerationStructure:(id)structure toBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset;
- (void)serializeInstanceAccelerationStructure:(id)structure primitiveAccelerationStructures:(id)structures toBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset;
- (void)deserializePrimitiveAccelerationStructure:(id)structure fromBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset;
- (void)deserializeInstanceAccelerationStructure:(id)structure primitiveAccelerationStructures:(id)structures fromBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset;
- (void)deserializePrimitiveAccelerationStructure:(id)structure fromBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset withDescriptor:(id)descriptor;
- (void)deserializeInstanceAccelerationStructure:(id)structure primitiveAccelerationStructures:(id)structures fromBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset withDescriptor:(id)descriptor;
- (void)serializeAccelerationStructure:(id)structure toBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset;
- (void)deserializeAccelerationStructure:(id)structure fromBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset;
- (void)deserializeAccelerationStructure:(id)structure primitiveAccelerationStructures:(id)structures fromBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset;
- (void)writeGeometrySizeOfAccelerationStructure:(id)structure toBuffer:(id)buffer sizeBufferOffset:(unsigned long long)offset;
- (void)writeGeometryOfAccelerationStructure:(id)structure toBuffer:(id)buffer geometryBufferOffset:(unsigned long long)offset;
- (signed char)writeGenericBVHStructureSizesOfAccelerationStructure:(id)structure into:(id)into;
- (signed char)writeGenericBVHStructureOfAccelerationStructure:(id)structure into:(id)into;
- (void)writeGenericBVHStructureSizesOfAccelerationStructure:(id)structure toBuffer:(id)buffer sizesBufferOffset:(unsigned long long)offset;
- (void)writeGenericBVHStructureOfAccelerationStructure:(id)structure headerBuffer:(id)buffer headerBufferOffset:(unsigned long long)offset innerNodeBuffer:(id)buffer innerNodeBufferOffset:(unsigned long long)offset leafNodeBuffer:(id)buffer leafNodeBufferOffset:(unsigned long long)offset primitiveBuffer:(id)buffer primitiveBufferOffset:(unsigned long long)offset geometryBuffer:(id)buffer geometryOffset:(unsigned long long)offset instanceTransformBuffer:(id)buffer instanceTransformOffset:(unsigned long long)offset;
- (void)sampleCountersInBuffer:(id)buffer atSampleIndex:(unsigned long long)index withBarrier:(signed char)barrier;
- (void)updateFence:(id)fence;
- (void)useHeap:(id)heap;
- (void)useHeaps:(const id *)heaps count:(unsigned long long)count;
- (void)useResource:(id)resource usage:(unsigned long long)usage;
- (void)useResources:(const id *)resources count:(unsigned long long)count usage:(unsigned long long)usage;
- (void)waitForFence:(id)fence;

@end

#endif /* _MTLAccelerationStructureCommandEncoder_h */
