//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef _MTLResource_h
#define _MTLResource_h
@import Foundation;

#include "_MTLObjectWithLabel.h"

@interface _MTLResource : _MTLObjectWithLabel

@property (readonly) unsigned long long allocationID;
@property (readonly) long long compressionType;
@property (readonly, nonatomic) unsigned long long compressionFootprint;

@end

#endif /* _MTLResource_h */
