//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLAttributeDescriptorInternal_h
#define MTLAttributeDescriptorInternal_h
@import Foundation;

#include "MTLAttributeDescriptor.h"

@interface MTLAttributeDescriptorInternal : MTLAttributeDescriptor {
    /* instance variables */
    unsigned long long _vertexFormat;
    unsigned long long _offset;
    unsigned long long _bufferIndex;
}

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (unsigned long long)format;
- (void)setFormat:(unsigned long long)format;
- (unsigned long long)bufferIndex;
- (void)setBufferIndex:(unsigned long long)index;
- (unsigned long long)offset;
- (void)setOffset:(unsigned long long)offset;

@end

#endif /* MTLAttributeDescriptorInternal_h */
