//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLAccelerationStructureCommandEncoderSPI_Protocol_h
#define MTLAccelerationStructureCommandEncoderSPI_Protocol_h
@import Foundation;

#include "MTLAccelerationStructureCommandEncoder-Protocol.h"

@protocol MTLAccelerationStructureCommandEncoderSPI <MTLAccelerationStructureCommandEncoder>

@required

/* required instance methods */
- (void)writeSerializedAccelerationStructureSize:(id)size toBuffer:(id)buffer sizeBufferOffset:(unsigned long long)offset;
- (void)writeDeserializedAccelerationStructureSize:(id)size serializedOffset:(unsigned long long)offset toBuffer:(id)buffer sizeBufferOffset:(unsigned long long)offset;
- (void)writeDeserializedPrimitiveAccelerationStructureSizes:(id)sizes serializedOffset:(unsigned long long)offset toBuffer:(id)buffer sizesBufferOffset:(unsigned long long)offset;
- (void)serializePrimitiveAccelerationStructure:(id)structure toBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset;
- (void)serializeInstanceAccelerationStructure:(id)structure primitiveAccelerationStructures:(id)structures toBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset;
- (void)deserializePrimitiveAccelerationStructure:(id)structure fromBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset;
- (void)deserializeInstanceAccelerationStructure:(id)structure primitiveAccelerationStructures:(id)structures fromBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset;
- (void)serializeAccelerationStructure:(id)structure toBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset;
- (void)deserializeAccelerationStructure:(id)structure fromBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset;
- (void)deserializeAccelerationStructure:(id)structure primitiveAccelerationStructures:(id)structures fromBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset;
- (void)writeGeometrySizeOfAccelerationStructure:(id)structure toBuffer:(id)buffer sizeBufferOffset:(unsigned long long)offset;
- (void)writeGeometryOfAccelerationStructure:(id)structure toBuffer:(id)buffer geometryBufferOffset:(unsigned long long)offset;

@optional

/* optional instance methods */
- (void)deserializePrimitiveAccelerationStructure:(id)structure fromBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset withDescriptor:(id)descriptor;
- (void)deserializeInstanceAccelerationStructure:(id)structure primitiveAccelerationStructures:(id)structures fromBuffer:(id)buffer serializedBufferOffset:(unsigned long long)offset withDescriptor:(id)descriptor;
- (signed char)writeGenericBVHStructureSizesOfAccelerationStructure:(id)structure into:(id)into;
- (signed char)writeGenericBVHStructureOfAccelerationStructure:(id)structure into:(id)into;
- (void)writeGenericBVHStructureSizesOfAccelerationStructure:(id)structure toBuffer:(id)buffer sizesBufferOffset:(unsigned long long)offset;
- (void)writeGenericBVHStructureOfAccelerationStructure:(id)structure headerBuffer:(id)buffer headerBufferOffset:(unsigned long long)offset innerNodeBuffer:(id)buffer innerNodeBufferOffset:(unsigned long long)offset leafNodeBuffer:(id)buffer leafNodeBufferOffset:(unsigned long long)offset primitiveBuffer:(id)buffer primitiveBufferOffset:(unsigned long long)offset geometryBuffer:(id)buffer geometryOffset:(unsigned long long)offset instanceTransformBuffer:(id)buffer instanceTransformOffset:(unsigned long long)offset;
- (void)writeGenericBVHStructureOfAccelerationStructure:(id)structure headerBuffer:(id)buffer headerBufferOffset:(unsigned long long)offset innerNodeBuffer:(id)buffer innerNodeBufferOffset:(unsigned long long)offset leafNodeBuffer:(id)buffer leafNodeBufferOffset:(unsigned long long)offset primitiveBuffer:(id)buffer primitiveBufferOffset:(unsigned long long)offset;

@end

#endif /* MTLAccelerationStructureCommandEncoderSPI_Protocol_h */
