//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLBufferLayoutDescriptorArrayInternal_h
#define MTLBufferLayoutDescriptorArrayInternal_h
@import Foundation;

#include "MTLBufferLayoutDescriptorArray.h"

@interface MTLBufferLayoutDescriptorArrayInternal : MTLBufferLayoutDescriptorArray {
    /* instance variables */
    MTLBufferLayoutDescriptorInternal *_descriptors[31];
}

/* instance methods */
- (void)dealloc;
- (id)objectAtIndexedSubscript:(unsigned long long)subscript;
- (void)setObject:(id)object atIndexedSubscript:(unsigned long long)subscript;

@end

#endif /* MTLBufferLayoutDescriptorArrayInternal_h */
