//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLBVHPolygonGeometryDescriptor_h
#define MTLBVHPolygonGeometryDescriptor_h
@import Foundation;

#include "MTLBVHGeometryDescriptor.h"
#include "MTLBuffer-Protocol.h"

@class NSArray;

@interface MTLBVHPolygonGeometryDescriptor : MTLBVHGeometryDescriptor

@property (nonatomic) unsigned long long polygonType;
@property (retain, nonatomic) NSArray *vertexBuffers;
@property (nonatomic) unsigned long long vertexStride;
@property (retain, nonatomic) id <MTLBuffer> indexBuffer;
@property (nonatomic) unsigned long long indexBufferOffset;
@property (nonatomic) unsigned long long indexType;

/* instance methods */
- (unsigned long long)primitiveType;
- (void)dealloc;

@end

#endif /* MTLBVHPolygonGeometryDescriptor_h */
