//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLComputePipelineDescriptorInternal_h
#define MTLComputePipelineDescriptorInternal_h
@import Foundation;

#include "MTLComputePipelineDescriptor.h"
#include "MTLFunction-Protocol.h"
#include "MTLLinkedFunctions.h"
#include "MTLPipelineBufferDescriptorArrayInternal.h"
#include "MTLPipelineLibrary-Protocol.h"
#include "MTLStageInputOutputDescriptor.h"

@class NSArray, NSDictionary, NSString;

@interface MTLComputePipelineDescriptorInternal : MTLComputePipelineDescriptor {
    /* instance variables */
    struct MTLComputePipelineDescriptorPrivate { NSString *label; <MTLFunction> *computeFunction; signed char threadGroupSizeIsMultipleOfThreadExecutionWidth; unsigned short maxTotalThreadsPerThreadgroup; MTLStageInputOutputDescriptor *stageInputDescriptor; NSDictionary *driverCompilerOptions; MTLPipelineBufferDescriptorArrayInternal *buffers; NSArray *binaryArchives; union { NSArray *preloadedLibraries; NSArray *insertLibraries; } x8; <MTLPipelineLibrary> *pipelineLibrary; signed char supportIndirectCommandBuffers; long long textureWriteRoundingMode; signed char forceResourceIndex; unsigned long long resourceIndex; NSDictionary *pluginData; signed char needsCustomBorderColorSamplers; unsigned int openGLMode:1; unsigned int openCLMode:1; unsigned int reserved:30; NSArray *functionPointers; NSDictionary *functionPointerGroups; MTLLinkedFunctions *linkedFunctions; unsigned long long maxStackCallDepth; signed char supportAddingBinaryFunctions; unsigned long long compilerTimeoutInSeconds; } _private;
    struct FlatBufferBuilder { struct vector_downward { struct Allocator *allocator_; _Bool own_allocator_; unsigned long long initial_size_; unsigned long long buffer_minalign_; unsigned long long reserved_; char *buf_; char *cur_; char *scratch_; } buf_; unsigned int num_field_loc; unsigned short max_voffset_; _Bool nested; _Bool finished; unsigned long long minalign_; _Bool force_defaults_; _Bool dedup_vtables_; void *string_pool; } _builder;
}

/* instance methods */
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;
- (void)reset;
- (id)label;
- (void)setLabel:(id)label;
- (void)setComputeFunction:(id)function;
- (id)computeFunction;
- (void)setStageInputDescriptor:(id)descriptor;
- (id)stageInputDescriptor;
- (void)setDriverCompilerOptions:(id)options;
- (id)driverCompilerOptions;
- (id)functionPointers;
- (void)setFunctionPointers:(id)pointers;
- (id)functionPointerGroups;
- (void)setFunctionPointerGroups:(id)groups;
- (id)linkedFunctions;
- (void)setLinkedFunctions:(id)functions;
- (signed char)supportAddingBinaryFunctions;
- (void)setSupportAddingBinaryFunctions:(signed char)functions;
- (unsigned long long)maxCallStackDepth;
- (void)setMaxCallStackDepth:(unsigned long long)depth;
- (id)binaryArchives;
- (void)setBinaryArchives:(id)archives;
- (id)binaryLibraries;
- (void)setBinaryLibraries:(id)libraries;
- (id)preloadedLibraries;
- (void)setPreloadedLibraries:(id)libraries;
- (id)insertLibraries;
- (void)setInsertLibraries:(id)libraries;
- (id)dynamicLibraries;
- (void)setDynamicLibraries:(id)libraries;
- (void)setPipelineLibrary:(id)library;
- (id)pipelineLibrary;
- (void)setThreadGroupSizeIsMultipleOfThreadExecutionWidth:(signed char)width;
- (signed char)threadGroupSizeIsMultipleOfThreadExecutionWidth;
- (void)setMaxTotalThreadsPerThreadgroup:(unsigned long long)threadgroup;
- (unsigned long long)maxTotalThreadsPerThreadgroup;
- (void)setSupportIndirectCommandBuffers:(signed char)buffers;
- (signed char)supportIndirectCommandBuffers;
- (void)setTextureWriteRoundingMode:(long long)mode;
- (long long)textureWriteRoundingMode;
- (void)setTextureWriteFPRoundingMode:(long long)mode;
- (long long)textureWriteFPRoundingMode;
- (signed char)forceResourceIndex;
- (void)setForceResourceIndex:(signed char)index;
- (unsigned long long)resourceIndex;
- (void)setResourceIndex:(unsigned long long)index;
- (signed char)openGLModeEnabled;
- (void)setOpenGLModeEnabled:(signed char)enabled;
- (signed char)openCLModeEnabled;
- (void)setOpenCLModeEnabled:(signed char)enabled;
- (signed char)needsCustomBorderColorSamplers;
- (void)setNeedsCustomBorderColorSamplers:(signed char)samplers;
- (unsigned long long)compilerTimeoutInSeconds;
- (void)setCompilerTimeoutInSeconds:(unsigned long long)seconds;
- (const struct MTLComputePipelineDescriptorPrivate { id x0; id x1; signed char x2; unsigned short x3; id x4; id x5; id x6; id x7; union { id x0; id x1; } x8; id x9; signed char x10; long long x11; signed char x12; unsigned long long x13; id x14; signed char x15; unsigned int x16:1; unsigned int x17:1; unsigned int x18:30; id x19; id x20; id x21; unsigned long long x22; signed char x23; unsigned long long x24; } *)_descriptorPrivate;
- (id)buffers;
- (id)pluginData;
- (void)setPluginData:(id)data;
- (unsigned long long)hash;
- (signed char)isEqual:(id)equal;
- (signed char)validateWithDevice:(id)device error:(id *)error;
- (void)validateWithDevice:(id)device;
- (id)newSerializedComputeData;
- (id)newSerializedComputeDataWithFlags:(unsigned long long)flags options:(unsigned long long)options;
- (const void *)getPipelineScript;

@end

#endif /* MTLComputePipelineDescriptorInternal_h */
