//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLCounterSampleBufferDescriptorInternal_h
#define MTLCounterSampleBufferDescriptorInternal_h
@import Foundation;

#include "MTLCounterSampleBufferDescriptor.h"
#include "MTLCounterSet-Protocol.h"
#include "NSCopying-Protocol.h"

@class NSString;

@interface MTLCounterSampleBufferDescriptorInternal : MTLCounterSampleBufferDescriptor <NSCopying> {
    /* instance variables */
    id <MTLCounterSet> _counterSet;
    unsigned long long _storageMode;
    NSString *_label;
    unsigned long long _sampleCount;
}

/* instance methods */
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)zone;
- (signed char)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)counterSet;
- (void)setCounterSet:(id)set;
- (unsigned long long)storageMode;
- (void)setStorageMode:(unsigned long long)mode;
- (id)label;
- (void)setLabel:(id)label;
- (unsigned long long)sampleCount;
- (void)setSampleCount:(unsigned long long)count;

@end

#endif /* MTLCounterSampleBufferDescriptorInternal_h */
