//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLCounterSampleBufferDescriptor_h
#define MTLCounterSampleBufferDescriptor_h
@import Foundation;

#include "MTLCounterSet-Protocol.h"
#include "NSCopying-Protocol.h"

@class NSObject, NSString;

@interface MTLCounterSampleBufferDescriptor : NSObject <NSCopying>

@property (retain) id <MTLCounterSet> counterSet;
@property (copy) NSString *label;
@property unsigned long long storageMode;
@property unsigned long long sampleCount;

/* class methods */
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;

@end

#endif /* MTLCounterSampleBufferDescriptor_h */
