//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLCompileOptions_h
#define MTLCompileOptions_h
@import Foundation;

#include "NSCopying-Protocol.h"

@class NSArray, NSDictionary, NSObject, NSString;

@interface MTLCompileOptions : NSObject <NSCopying>

@property (nonatomic) signed char tracingEnabled;
@property (nonatomic) signed char framebufferReadEnabled;
@property (nonatomic) signed char debuggingEnabled;
@property (nonatomic) signed char compileTimeStatisticsEnabled;
@property (copy, nonatomic) NSString *additionalCompilerArguments;
@property (nonatomic) unsigned char sourceLanguage;
@property (copy, nonatomic) NSDictionary *preprocessorMacros;
@property (nonatomic) signed char fastMathEnabled;
@property (nonatomic) unsigned long long languageVersion;
@property (nonatomic) long long libraryType;
@property (copy, nonatomic) NSString *installName;
@property (copy, nonatomic) NSArray *libraries;
@property (nonatomic) signed char preserveInvariance;

/* class methods */
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;

@end

#endif /* MTLCompileOptions_h */
