//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLCaptureManager_h
#define MTLCaptureManager_h
@import Foundation;

#include "MTLCaptureScope-Protocol.h"

@class NSObject;

@interface MTLCaptureManager : NSObject

@property (retain) id <MTLCaptureScope> defaultCaptureScope;
@property (readonly) signed char isCapturing;

/* class methods */
+ (id)sharedCaptureManager;

/* instance methods */
- (void)notifySubmissionForEyeSPI:(unsigned long long)spi iosurface:(struct __IOSurface *)iosurface bounds:(const struct MTLVRTextureBounds { float x0; float x1; float x2; float x3; } *)bounds submitFlags:(unsigned long long)flags;
- (void)notifyPostPresentHandoffSPI;
- (void)dealloc;
- (id)newCaptureScopeWithDevice:(id)device;
- (id)newCaptureScopeWithCommandQueue:(id)queue;
- (signed char)startCaptureWithDescriptor:(id)descriptor error:(id *)error;
- (void)startCaptureWithDevice:(id)device;
- (void)startCaptureWithCommandQueue:(id)queue;
- (void)startCaptureWithScope:(id)scope;
- (void)stopCapture;
- (signed char)supportsDestination:(long long)destination;

@end

#endif /* MTLCaptureManager_h */
