//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLConstantRelocation_h
#define MTLConstantRelocation_h
@import Foundation;

#include "MTLRelocation-Protocol.h"

@class NSObject, NSString;
@protocol OS_dispatch_data;

@interface MTLConstantRelocation : NSObject <MTLRelocation>

@property (readonly, nonatomic) NSObject<OS_dispatch_data> *data;
@property (readonly, nonatomic) NSString *symbolName;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithSymbolName:(id)name data:(id)data;
- (id)initWithSymbolName:(id)name bytes:(void *)bytes length:(unsigned long long)length;
- (void)dealloc;

@end

#endif /* MTLConstantRelocation_h */
