//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLCounterSetInternal_h
#define MTLCounterSetInternal_h
@import Foundation;

#include "MTLCounterSet-Protocol.h"

@class NSArray, NSObject, NSString;

@interface MTLCounterSetInternal : NSObject <MTLCounterSet>

@property (readonly, copy) NSString *name;
@property (readonly, copy) NSArray *counters;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithName:(id)name description:(id)description counters:(id)counters;
- (void)dealloc;
- (signed char)isEqual:(id)equal;

@end

#endif /* MTLCounterSetInternal_h */
