//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLCommandQueueDescriptorInternal_h
#define MTLCommandQueueDescriptorInternal_h
@import Foundation;

#include "MTLCommandQueueDescriptor.h"

@class NSObject;
@protocol OS_dispatch_queue;

@interface MTLCommandQueueDescriptorInternal : MTLCommandQueueDescriptor {
    /* instance variables */
    unsigned long long _maxCommandBufferCount;
    unsigned long long _qosLevel;
    NSObject<OS_dispatch_queue> *_commitQueue;
    signed char _commitSynchronously;
    NSObject<OS_dispatch_queue> *_completionQueue;
    signed char _disableCrossQueueHazardTracking;
    signed char _openGLQueue;
    unsigned long long _devicePartition;
}

@property signed char isOpenGLQueue;

/* instance methods */
- (id)init;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;
- (unsigned long long)maxCommandBufferCount;
- (void)setMaxCommandBufferCount:(unsigned long long)count;
- (unsigned long long)qosLevel;
- (void)setQosLevel:(unsigned long long)level;
- (id)commitQueue;
- (void)setCommitQueue:(id)queue;
- (signed char)commitSynchronously;
- (void)setCommitSynchronously:(signed char)synchronously;
- (id)completionQueue;
- (void)setCompletionQueue:(id)queue;
- (signed char)disableCrossQueueHazardTracking;
- (void)setDisableCrossQueueHazardTracking:(signed char)tracking;
- (unsigned long long)devicePartition;
- (void)setDevicePartition:(unsigned long long)partition;

@end

#endif /* MTLCommandQueueDescriptorInternal_h */
