//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLDepthStencilDescriptor_h
#define MTLDepthStencilDescriptor_h
@import Foundation;

#include "MTLStencilDescriptor.h"
#include "NSCopying-Protocol.h"

@class NSObject, NSString;

@interface MTLDepthStencilDescriptor : NSObject <NSCopying>

@property (readonly) const struct MTLDepthStencilDescriptorPrivate { id x0; id x1; unsigned long long x2; signed char x3; id x4; } * depthStencilPrivate;
@property (nonatomic) unsigned long long depthCompareFunction;
@property (nonatomic) signed char depthWriteEnabled;
@property (copy, nonatomic) MTLStencilDescriptor *frontFaceStencil;
@property (copy, nonatomic) MTLStencilDescriptor *backFaceStencil;
@property (copy, nonatomic) NSString *label;

/* class methods */
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;

@end

#endif /* MTLDepthStencilDescriptor_h */
