//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLDynamicLibraryContainer_h
#define MTLDynamicLibraryContainer_h
@import Foundation;

#include "MTLDebugInstrumentationData.h"
#include "MTLDevice-Protocol.h"
#include "MTLLoadedFile.h"

@class NSArray, NSData, NSObject, NSString;
@protocol OS_dispatch_data;

@interface MTLDynamicLibraryContainer : NSObject {
    /* instance variables */
    MTLLoadedFile *_fileMapping;
    id <MTLDevice> _device;
    NSObject<OS_dispatch_data> *_vendorData;
    NSArray *_exportedFunctions;
    NSArray *_exportedVariables;
    NSArray *_importedSymbols;
    NSArray *_importedLibraries;
    NSString *_installName;
    NSData *_airData;
    unsigned long long _airOffset;
    unsigned long long _airSize;
    int _airVersion;
    struct { unsigned char key[32]; } _libraryUUID;
    MTLDebugInstrumentationData *_debugInstrumentationData;
}

/* instance methods */
- (id)initWithLibrary:(struct MTLLibraryData { void * /* function */ *x0; struct { unsigned char x0[32]; } x1; _Atomic int x2; id x3; id x4; } *)library binaryData:(id)data device:(id)device error:(id *)error;
- (id)initWithURL:(id)url device:(id)device options:(unsigned long long)options error:(id *)error;
- (void)dealloc;
- (oneway void)release;
- (id)airData;
- (signed char)serializeToURL:(id)url options:(unsigned long long)options error:(id *)error;

@end

#endif /* MTLDynamicLibraryContainer_h */
