//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLDepthStencilDescriptorInternal_h
#define MTLDepthStencilDescriptorInternal_h
@import Foundation;

#include "MTLDepthStencilDescriptor.h"
#include "MTLStencilDescriptorInternal.h"

@class NSString;

@interface MTLDepthStencilDescriptorInternal : MTLDepthStencilDescriptor {
    /* instance variables */
    struct MTLDepthStencilDescriptorPrivate { MTLStencilDescriptorInternal *frontFaceStencil; MTLStencilDescriptorInternal *backFaceStencil; unsigned long long depthCompareFunction; signed char depthWriteEnabled; NSString *label; } _private;
}

@property (readonly) const struct MTLDepthStencilDescriptorPrivate { id x0; id x1; unsigned long long x2; signed char x3; id x4; } * depthStencilPrivate;

/* instance methods */
- (id)init;
- (void)dealloc;
- (unsigned long long)hash;
- (signed char)isEqual:(id)equal;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;
- (unsigned long long)depthCompareFunction;
- (void)setDepthCompareFunction:(unsigned long long)function;
- (signed char)isDepthWriteEnabled;
- (void)setDepthWriteEnabled:(signed char)enabled;
- (id)frontFaceStencil;
- (void)setFrontFaceStencil:(id)stencil;
- (id)backFaceStencil;
- (void)setBackFaceStencil:(id)stencil;
- (id)label;
- (void)setLabel:(id)label;

@end

#endif /* MTLDepthStencilDescriptorInternal_h */
