//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLDebugInstrumentationData_h
#define MTLDebugInstrumentationData_h
@import Foundation;

#include "MTLDebugLocation.h"
#include "MTLDebugSubProgram.h"

@class NSData, NSObject, __CFString;
@protocol OS_dispatch_data;

@interface MTLDebugInstrumentationData : NSObject {
    /* instance variables */
    NSObject<OS_dispatch_data> *_dataMap;
    const void * _data;
    struct vector<const __CFString *, std::allocator<const __CFString *>> { struct __CFString * *__begin_; struct __CFString * *__end_; struct __compressed_pair<const __CFString **, std::allocator<const __CFString *>> { struct __CFString * *__value_; } __end_cap_; } _strings;
    struct vector<MTLDebugLocation *, std::allocator<MTLDebugLocation *>> { id *__begin_; id *__end_; struct __compressed_pair<MTLDebugLocation **, std::allocator<MTLDebugLocation *>> { id *__value_; } __end_cap_; } _debugLocations;
    struct vector<MTLDebugSubProgram *, std::allocator<MTLDebugSubProgram *>> { id *__begin_; id *__end_; struct __compressed_pair<MTLDebugSubProgram **, std::allocator<MTLDebugSubProgram *>> { id *__value_; } __end_cap_; } _debugSubPrograms;
    NSData *_globalConstantsData;
    NSObject<OS_dispatch_data> *_userReflectionData;
}

@property (readonly, nonatomic) signed char hasGlobalConstantsInstrumentationFailures;
@property (readonly, nonatomic) signed char hasArgumentBufferInstrumentationFailures;
@property (readonly, nonatomic) signed char hasArgumentLimitsInstrumentationFailures;
@property (readonly, nonatomic) unsigned int threadgroupArgumentOffset;
@property (readonly, nonatomic) unsigned int activeThreadgroupMask;
@property (readonly, nonatomic) unsigned long long bufferAccessMask;

/* instance methods */
- (id)initWithData:(id)data;
- (id)stringForID:(unsigned int)id;
- (id)debugLocationForID:(unsigned int)id;
- (id)debugSubProgramForID:(unsigned int)id;
- (id)globalConstantsData;
- (id)userReflectionData;
- (void)dealloc;

@end

#endif /* MTLDebugInstrumentationData_h */
