//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLFunctionStitchingFunctionNode_h
#define MTLFunctionStitchingFunctionNode_h
@import Foundation;

#include "MTLFunctionStitchingNode-Protocol.h"

@class NSArray, NSObject, NSString;

@interface MTLFunctionStitchingFunctionNode : NSObject <MTLFunctionStitchingNode>

@property (copy, nonatomic) NSString *name;
@property (copy, nonatomic) NSArray *arguments;
@property (copy, nonatomic) NSArray *controlDependencies;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (id)initWithName:(id)name arguments:(id)arguments controlDependencies:(id)dependencies;
- (id)copyWithZone:(struct _NSZone *)zone;
- (signed char)isEqual:(id)equal;
- (void)dealloc;
- (id)formattedDescription:(unsigned long long)description;

@end

#endif /* MTLFunctionStitchingFunctionNode_h */
