//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLFunctionStitchingGraph_h
#define MTLFunctionStitchingGraph_h
@import Foundation;

#include "MTLFunctionStitchingFunctionNode.h"
#include "NSCopying-Protocol.h"

@class NSArray, NSObject, NSString;

@interface MTLFunctionStitchingGraph : NSObject <NSCopying>

@property (copy, nonatomic) NSString *functionName;
@property (copy, nonatomic) NSArray *nodes;
@property (copy, nonatomic) MTLFunctionStitchingFunctionNode *outputNode;
@property (copy, nonatomic) NSArray *attributes;

/* instance methods */
- (id)init;
- (id)initWithFunctionName:(id)name nodes:(id)nodes outputNode:(id)node attributes:(id)attributes;
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)dealloc;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;

@end

#endif /* MTLFunctionStitchingGraph_h */
