//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLFunctionDescriptor_h
#define MTLFunctionDescriptor_h
@import Foundation;

#include "MTLFunctionConstantValues.h"
#include "NSCopying-Protocol.h"

@class NSArray, NSDictionary, NSObject, NSString;

@interface MTLFunctionDescriptor : NSObject <NSCopying> {
    /* instance variables */
    struct MTLFunctionDescriptorPrivate { NSString *name; NSString *specializedName; unsigned long long options; MTLFunctionConstantValues *constantValues; NSArray *binaryArchives; signed char applyFunctionConstants; NSArray *privateFunctions; } _private;
    unsigned long long _pipelineOptions;
    NSDictionary *_pluginData;
}

@property (copy, nonatomic) NSString *name;
@property (copy, nonatomic) NSString *specializedName;
@property (copy, nonatomic) MTLFunctionConstantValues *constantValues;
@property (nonatomic) unsigned long long options;
@property (copy, nonatomic) NSArray *binaryArchives;

/* class methods */
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;
+ (id)functionDescriptor;

/* instance methods */
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)privateFunctions;
- (void)setPrivateFunctions:(id)functions;
- (unsigned long long)hash;
- (struct { unsigned char x0[32]; })hashStableWithFunction:(id)function;
- (signed char)isEqual:(id)equal;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;
- (void)setPipelineOptions:(unsigned long long)options;
- (unsigned long long)pipelineOptions;
- (void)setPluginData:(id)data;
- (id)pluginData;
- (void)setApplyFunctionConstants:(signed char)constants;
- (signed char)applyFunctionConstants;

@end

#endif /* MTLFunctionDescriptor_h */
