//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLFunctionReflectionInternal_h
#define MTLFunctionReflectionInternal_h
@import Foundation;

#include "MTLFunctionReflection.h"

@class NSArray, NSData;

@interface MTLFunctionReflectionInternal : MTLFunctionReflection {
    /* instance variables */
    NSArray *_builtInArguments;
    NSArray *_arguments;
    NSData *_pluginReturnData;
    unsigned long long _primitiveKind;
    NSArray *_tags;
}

/* instance methods */
- (id)initWithArguments:(id *)arguments argumentCount:(unsigned int)count builtInArgumentCount:(unsigned int)count pluginReturnData:(id)data primitiveKind:(unsigned long long)kind tags:(id *)tags tagCount:(unsigned int)count;
- (id)initWithDevice:(id)device reflectionData:(id)data functionType:(unsigned long long)type options:(unsigned long long)options;
- (void)dealloc;
- (id)builtInArguments;
- (id)arguments;
- (id)pluginReturnData;
- (unsigned long long)primitiveKind;
- (id)tags;

@end

#endif /* MTLFunctionReflectionInternal_h */
