//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLFunctionStitchingFunctionNodeSPI_h
#define MTLFunctionStitchingFunctionNodeSPI_h
@import Foundation;

#include "MTLFunctionStitchingFunctionNode.h"

@interface MTLFunctionStitchingFunctionNodeSPI : MTLFunctionStitchingFunctionNode

@property (nonatomic) signed char isEarlyReturn;

/* instance methods */
- (id)initWithName:(id)name arguments:(id)arguments controlDependencies:(id)dependencies isEarlyReturn:(signed char)_return;
- (id)copyWithZone:(struct _NSZone *)zone;
- (signed char)isEqual:(id)equal;
- (unsigned long long)hash;

@end

#endif /* MTLFunctionStitchingFunctionNodeSPI_h */
