//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLFunctionConstant_h
#define MTLFunctionConstant_h
@import Foundation;

@class NSObject, NSString;

@interface MTLFunctionConstant : NSObject

@property (readonly) NSString *name;
@property (readonly) unsigned long long type;
@property (readonly) unsigned long long index;
@property (readonly) signed char required;

/* class methods */
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;

@end

#endif /* MTLFunctionConstant_h */
