//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLFunctionLogDebugLocation_Protocol_h
#define MTLFunctionLogDebugLocation_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@class NSString, NSURL;

@protocol MTLFunctionLogDebugLocation <NSObject>

@required

@property (readonly, nonatomic) NSString *functionName;
@property (readonly, nonatomic) NSURL *URL;
@property (readonly, nonatomic) unsigned long long line;
@property (readonly, nonatomic) unsigned long long column;

@optional

@end

#endif /* MTLFunctionLogDebugLocation_Protocol_h */
