//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLFunctionVariant_h
#define MTLFunctionVariant_h
@import Foundation;

@class NSObject;
@protocol OS_dispatch_data;

@interface MTLFunctionVariant : NSObject {
    /* instance variables */
    void * _inputInfo;
    unsigned long long _inputInfoSize;
}

@property (nonatomic) NSObject<OS_dispatch_data> *debugInstrumentationData;

/* instance methods */
- (id)initWithCompilerOutput:(id)output;
- (void)dealloc;
- (const void *)inputInfoAndSize:(unsigned long long *)size;
- (void)setInputInfo:(const void *)info size:(unsigned long long)size;
- (const void *)outputInfoAndSize:(unsigned long long *)size;
- (void)setOutputInfo:(const void *)info size:(unsigned long long)size;

@end

#endif /* MTLFunctionVariant_h */
