//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLFunctionStitchingBuiltinThreadPositionInThreadgroup_h
#define MTLFunctionStitchingBuiltinThreadPositionInThreadgroup_h
@import Foundation;

#include "MTLFunctionStitchingInputBuiltin-Protocol.h"

@class NSObject, NSString;

@interface MTLFunctionStitchingBuiltinThreadPositionInThreadgroup : NSObject <MTLFunctionStitchingInputBuiltin>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (signed char)isEqual:(id)equal;

@end

#endif /* MTLFunctionStitchingBuiltinThreadPositionInThreadgroup_h */
