//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLIOAccelParallelRenderCommandEncoder_h
#define MTLIOAccelParallelRenderCommandEncoder_h
@import Foundation;

#include "_MTLParallelRenderCommandEncoder.h"

@interface MTLIOAccelParallelRenderCommandEncoder : _MTLParallelRenderCommandEncoder

/* instance methods */
- (id)initWithCommandBuffer:(id)buffer renderPassDescriptor:(id)descriptor;
- (void)setLabel:(id)label;
- (void)endEncoding;
- (void)pushDebugGroup:(id)group;
- (void)popDebugGroup;
- (unsigned long long)getType;
- (signed char)isMemorylessRender;
- (signed char)separateCommits;
- (void)setSeparateCommits:(signed char)commits;

@end

#endif /* MTLIOAccelParallelRenderCommandEncoder_h */
