//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLIOAccelCommandBuffer_h
#define MTLIOAccelCommandBuffer_h
@import Foundation;

#include "MTLDevice-Protocol.h"
#include "MTLIOAccelDevice.h"
#include "_MTLCommandBuffer.h"

@class NSMutableSet, NSObject;
@protocol OS_dispatch_semaphore;

@interface MTLIOAccelCommandBuffer : _MTLCommandBuffer {
    /* instance variables */
    struct MTLIOAccelCommandBufferStorage { id x0; struct MTLIOAccelCommandBufferStoragePool *x1; struct { struct MTLIOAccelCommandBufferStorage *x0; struct MTLIOAccelCommandBufferStorage * *x1; } x2; id x3; char *x4; char *x5; char *x6; id x7; char *x8; char *x9; struct IOAccelSegmentListHeader *x10; struct IOAccelSegmentResourceListHeader *x11; struct IOAccelSegmentResourceDescriptorGroup *x12; struct IOAccelResourceList { unsigned short x0[256]; struct IOAccelSegmentResourceDescriptorGroup *x1; unsigned long long x2; unsigned long long x3; unsigned int x4; unsigned int x5; unsigned int x6; unsigned int x7; unsigned int x8; unsigned int x9; unsigned int x10; void * /* function */ x11; void *x12; } x13; id x14; id x15; unsigned long long x16; unsigned long long x17; id *x18; struct MTLIOAccelCommandBufferResourceInfo *x19; id x20; id *x21; unsigned int x22; unsigned long long x23; struct IOAccelSegmentListShmemHeader *x24; struct IOAccelSegmentKernelCommmandListHeader *x25; unsigned int x26; unsigned int x27; int x28; int x29; unsigned int x30; struct IOAccelSegmentResourceListHeader *x31; struct IOAccelSegmentResourceDescriptorGroup *x32; unsigned int x33; } * _storage;
    unsigned long long * _submitToHardwareTimeStampPointer;
    unsigned long long _protectionOptions;
    void * _scheduledCallbackBlockPtr;
    void * _completedCallbackBlockPtr;
    NSObject<OS_dispatch_semaphore> *_commitAndResetSem;
    NSMutableSet *_purgedResources;
}

@property (readonly) struct MTLIOAccelCommandBufferResourceInfo { unsigned long long x0; unsigned int *x1; unsigned int *x2; unsigned int *x3; id x4; struct IOAccelResourceInfo { struct __IOSurface *x0; unsigned int x1:56; unsigned int x2:7; unsigned int x3:1; unsigned int x4; } x5; } * commandBufferResourceInfo;
@property (readonly) struct IOAccelResourceList { unsigned short x0[256]; struct IOAccelSegmentResourceDescriptorGroup *x1; unsigned long long x2; unsigned long long x3; unsigned int x4; unsigned int x5; unsigned int x6; unsigned int x7; unsigned int x8; unsigned int x9; unsigned int x10; void * /* function */ x11; void *x12; } * ioAccelResourceList;
@property (readonly) id <MTLDevice> device;
@property (readonly) struct MTLIOAccelCommandBufferStorage { id x0; struct MTLIOAccelCommandBufferStoragePool *x1; struct { struct MTLIOAccelCommandBufferStorage *x0; struct MTLIOAccelCommandBufferStorage * *x1; } x2; id x3; char *x4; char *x5; char *x6; id x7; char *x8; char *x9; struct IOAccelSegmentListHeader *x10; struct IOAccelSegmentResourceListHeader *x11; struct IOAccelSegmentResourceDescriptorGroup *x12; struct IOAccelResourceList { unsigned short x0[256]; struct IOAccelSegmentResourceDescriptorGroup *x1; unsigned long long x2; unsigned long long x3; unsigned int x4; unsigned int x5; unsigned int x6; unsigned int x7; unsigned int x8; unsigned int x9; unsigned int x10; void * /* function */ x11; void *x12; } x13; id x14; id x15; unsigned long long x16; unsigned long long x17; id *x18; struct MTLIOAccelCommandBufferResourceInfo *x19; id x20; id *x21; unsigned int x22; unsigned long long x23; struct IOAccelSegmentListShmemHeader *x24; struct IOAccelSegmentKernelCommmandListHeader *x25; unsigned int x26; unsigned int x27; int x28; int x29; unsigned int x30; struct IOAccelSegmentResourceListHeader *x31; struct IOAccelSegmentResourceDescriptorGroup *x32; unsigned int x33; } * commandBufferStorage;

/* instance methods */
- (id)initWithQueue:(id)queue retainedReferences:(signed char)references synchronousDebugMode:(signed char)mode;
- (id)initWithQueue:(id)queue retainedReferences:(signed char)references;
- (void)setLabel:(id)label;
- (void)dealloc;
- (void)getCurrentKernelCommandBufferStart:(void * *)start current:(void * *)current end:(void * *)end;
- (void)getCurrentKernelCommandBufferPointer:(void * *)pointer end:(void * *)end;
- (void)setCurrentKernelCommandBufferPointer:(void *)pointer;
- (void)growKernelCommandBuffer:(unsigned long long)buffer;
- (void)allocCommandBufferResourceAtIndex:(unsigned int)index;
- (void)didCompleteWithStartTime:(unsigned long long)time endTime:(unsigned long long)time error:(id)error;
- (struct IOAccelSegmentListHeader { unsigned long long x0; unsigned int x1; unsigned int x2; struct IOAccelSegmentResourceListHeader { unsigned long long x30; unsigned int x1; unsigned int x2; unsigned int x3; unsigned int x4; struct IOAccelSegmentResourceDescriptorGroup { unsigned int x50[6]; unsigned long long x1[6]; unsigned short x2[6]; unsigned short x3; unsigned short x4; } x[0]; } x[0]; } *)getSegmentListHeader;
- (void)getSegmentListPointerStart:(void * *)start current:(void * *)current end:(void * *)end;
- (void)setCurrentSegmentListPointer:(void *)pointer;
- (void)growSegmentList;
- (void)beginSegment:(void *)segment;
- (void)endCurrentSegment;
- (void)validate;
- (void)commit;
- (void)commitAndReset;
- (id)akResourceList;
- (id)akPrivateResourceList;
- (void)kernelCommandCollectTimeStamp;
- (void)setCurrentCommandEncoder:(id)encoder;
- (void)pushDebugGroup:(id)group;
- (void)popDebugGroup;
- (void *)_reserveKernelCommandBufferSpace:(unsigned long long)space;
- (void)_debugBytes:(const char *)bytes length:(unsigned long long)length output_type:(unsigned int)output_type;
- (void)commitEncoder;
- (void)kprintfBytes:(const char *)bytes length:(unsigned long long)length;
- (void)encodeSubmitSleepMS:(unsigned int)ms;
- (void)encodeSignalEvent:(id)event value:(unsigned long long)value;
- (void)encodeWaitForEvent:(id)event value:(unsigned long long)value;
- (void)encodeWaitForEvent:(id)event value:(unsigned long long)value timeout:(unsigned int)timeout;
- (signed char)getSegmentListLockedPeerIndex:(unsigned int *)index;
- (void)setSegmentListLockedPeerIndex:(unsigned int)index;
- (unsigned long long)protectionOptions;
- (void)setProtectionOptions:(unsigned long long)options;
- (void)addPurgedResource:(id)resource;
- (void)addPurgedHeap:(id)heap;
- (void)_encodePurgedResources;
- (void)doCorruptCBSPI:(int)cbspi;

@end

#endif /* MTLIOAccelCommandBuffer_h */
