//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLIOAccelIndirectArgumentEncoder_h
#define MTLIOAccelIndirectArgumentEncoder_h
@import Foundation;

#include "_MTLIndirectArgumentEncoder.h"

@interface MTLIOAccelIndirectArgumentEncoder : _MTLIndirectArgumentEncoder

@property (readonly) unsigned long long encodedLength;

/* instance methods */
- (void)setIndirectArgumentBuffer:(id)buffer offset:(unsigned long long)offset;
- (void)setBuffer:(id)buffer offset:(unsigned long long)offset atIndex:(unsigned long long)index;
- (void)setBuffers:(const id *)buffers offsets:(const unsigned long long *)offsets withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)setTexture:(id)texture atIndex:(unsigned long long)index;
- (void)setTextures:(const id *)textures withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)setSamplerState:(id)state atIndex:(unsigned long long)index;
- (void)setSamplerStates:(const id *)states withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void *)constantDataAtIndex:(unsigned long long)index;
- (void)setIndirectCommandBuffer:(id)buffer atIndex:(unsigned long long)index;
- (void)setIndirectCommandBuffers:(const id *)buffers withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)setVisibleFunctionTable:(id)table atBufferIndex:(unsigned long long)index;
- (void)setVisibleFunctionTables:(const id *)tables withBufferRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)setIntersectionFunctionTable:(id)table atBufferIndex:(unsigned long long)index;
- (void)setIntersectionFunctionTables:(const id *)tables withBufferRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)setVisibleFunctionTable:(id)table atIndex:(unsigned long long)index;
- (void)setVisibleFunctionTables:(const id *)tables withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)setIntersectionFunctionTable:(id)table atIndex:(unsigned long long)index;
- (void)setIntersectionFunctionTables:(const id *)tables withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;

@end

#endif /* MTLIOAccelIndirectArgumentEncoder_h */
