//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLIOAccelResourceStateCommandEncoder_h
#define MTLIOAccelResourceStateCommandEncoder_h
@import Foundation;

#include "MTLIOAccelCommandEncoder.h"

@interface MTLIOAccelResourceStateCommandEncoder : MTLIOAccelCommandEncoder

/* instance methods */
- (void)updateTextureMappings:(id)mappings mode:(unsigned long long)mode regions:(const struct { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x0; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x1; } *)regions mipLevels:(const unsigned long long *)levels slices:(const unsigned long long *)slices numRegions:(unsigned long long)regions;
- (void)updateTextureMapping:(id)mapping mode:(unsigned long long)mode region:(struct { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x0; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x1; })region mipLevel:(unsigned long long)level slice:(unsigned long long)slice;
- (void)updateTextureMapping:(id)mapping mode:(unsigned long long)mode indirectBuffer:(id)buffer indirectBufferOffset:(unsigned long long)offset;
- (unsigned long long)getType;

@end

#endif /* MTLIOAccelResourceStateCommandEncoder_h */
