//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLIOAccelDevice_h
#define MTLIOAccelDevice_h
@import Foundation;

#include "MTLDeviceSPI-Protocol.h"
#include "MTLIOAccelDeviceShmemPool.h"
#include "MTLIOAccelService.h"
#include "MTLIOMemoryInfo.h"
#include "MTLResourceListPool.h"
#include "_MTLDevice.h"

@class NSLock, NSObject;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface MTLIOAccelDevice : _MTLDevice {
    /* instance variables */
    struct __IOAccelDevice * _deviceRef;
    struct __IOAccelShared * _sharedRef;
    MTLIOAccelService *_acceleratorService;
    struct { MTLIOAccelDeviceShmemPool *segmentListShmemPool; MTLIOAccelDeviceShmemPool *kernelCommandShmemPool; id *hwResourcePools; unsigned int hwResourcePoolCount; MTLResourceListPool *akResourceListPool; MTLResourceListPool *akPrivateResourceListPool; } _storageCreateParams;
    struct MTLIOAccelCommandBufferStoragePool { struct storageQueue { struct MTLIOAccelCommandBufferStorage *x0; struct MTLIOAccelCommandBufferStorage * *x1; } x0; struct os_unfair_lock_s { unsigned int x0; } x1; int x2; _Atomic int x3; id x4; } * _commandBufferStoragePool;
    unsigned int _configBits;
    unsigned int _deviceBits;
    unsigned long long _textureRam;
    unsigned long long _videoRam;
    unsigned int _accelID;
    unsigned long long _segmentByteThreshold;
    unsigned int _peerMask;
    NSLock *_peerConnectionsLock;
    struct { MTLIOAccelDevice *device; int refCount; } _peerConnections[4];
    struct MTLIOAccelBufferHeap { MTLIOAccelBuffer *buffers[64]; struct MTLRangeAllocator { struct MTLRangeAllocatorElement *elements; unsigned int numElements; unsigned long long capacity; unsigned long long capacityIncrement; unsigned long long defaultAlignmentMask; } allocators[64]; unsigned int allocations[64]; unsigned int count; } _bufferHeaps[16];
    NSObject<OS_dispatch_queue> *_device_dispatch_queue;
    NSObject<OS_dispatch_queue> *_device_pool_cleanup_queue;
    NSObject<OS_dispatch_source> *_device_pool_cleanup_source;
    _Bool _device_pool_cleanup_scheduled;
    unsigned int _fenceAllocatedCount;
    unsigned int _fenceMaximumCount;
    unsigned int _fenceBitmapSearchStart;
    unsigned int _fenceBitmapCount;
    unsigned long long * _fenceAllocationBitmap;
    id <MTLDeviceSPI> _deviceWrapper;
}

@property (readonly) id * hwResourcePools;
@property (readonly) unsigned int hwResourcePoolCount;
@property (readonly) int numCommandBuffers;
@property (readonly) unsigned int acceleratorPort;
@property (readonly) unsigned long long sharedMemorySize;
@property (readonly) unsigned long long dedicatedMemorySize;
@property (readonly) unsigned long long recommendedMaxWorkingSetSize;
@property (readonly) unsigned long long registryID;
@property (readonly) unsigned long long peerGroupID;
@property (readonly) unsigned int peerIndex;
@property (readonly) unsigned int peerCount;
@property (readonly) signed char lowPower;
@property (readonly) signed char headless;
@property (readonly) signed char removable;
@property (readonly) signed char hasUnifiedMemory;
@property (readonly) unsigned long long location;
@property (readonly) unsigned long long locationNumber;
@property (readonly) unsigned long long maxTransferRate;
@property (readonly) signed char supportsVertexAmplification;
@property (readonly) signed char supportPriorityBand;
@property (readonly) unsigned long long currentAllocatedSize;
@property (readonly) MTLIOMemoryInfo *memoryInfo;
@property (readonly) signed char supportLazyInitialization;
@property (readonly) Class bufferClass;

/* class methods */
+ (void)registerDevices;

/* instance methods */
- (void)dealloc;
- (void)setSegmentListShmemSize:(unsigned int)size;
- (void)setComputePipelineStateCommandShmemSize:(unsigned int)size;
- (void)_setAcceleratorService:(id)service;
- (id)initWithAcceleratorPort:(unsigned int)port;
- (signed char)lazyInitialize;
- (unsigned int)initialKernelCommandShmemSize;
- (unsigned int)initialSegmentListShmemSize;
- (void)setHwResourcePool:(id *)pool count:(int)count;
- (void)_purgeDevice;
- (id)akResourceListPool;
- (id)akPrivateResourceListPool;
- (struct __IOAccelDevice *)deviceRef;
- (struct __IOAccelShared *)sharedRef;
- (signed char)isLowPower;
- (signed char)isHeadless;
- (signed char)isRemovable;
- (id)newGLDrawable;
- (int)getSurfaceMode:(unsigned long long *)mode width:(unsigned int *)width height:(unsigned int *)height forId:(unsigned int)id;
- (signed char)isBuiltIn;
- (signed char)isSlotted;
- (void)getSlottedGPUProperties:(unsigned long long *)gpuproperties transferRate:(unsigned long long *)rate;
- (void)getExternalGPUProperties:(unsigned long long *)gpuproperties transferRate:(unsigned long long *)rate;
- (void)getBuiltInGPUProperties:(unsigned long long *)gpuproperties transferRate:(unsigned long long *)rate;
- (void)updateGPUSelectionProperties;
- (signed char)supportsVertexAmplificationCount:(unsigned long long)count;
- (short)heapIndexWithOptions:(unsigned long long)options;
- (id)allocBufferSubDataWithLength:(unsigned long long)length options:(unsigned long long)options alignment:(unsigned long long)alignment heapIndex:(short *)index bufferIndex:(short *)index bufferOffset:(unsigned long long *)offset;
- (void)deallocBufferSubData:(id)data heapIndex:(short)index bufferIndex:(short)index bufferOffset:(unsigned long long)offset length:(unsigned long long)length;
- (id)newCommandQueueWithDescriptor:(id)descriptor;
- (id)newFence;
- (void)releaseFenceIndex:(unsigned int)index;
- (id)newIndirectArgumentBufferLayoutWithStructType:(id)type;
- (id)newArgumentEncoderWithLayout:(id)layout;
- (id)newIndirectArgumentEncoderWithLayout:(id)layout;
- (id)newIndirectCommandBufferWithDescriptor:(id)descriptor maxCommandCount:(unsigned long long)count options:(unsigned long long)options;
- (id)indirectArgumentBufferDecodingData;
- (void)setIndirectArgumentBufferDecodingData:(id)data;
- (id)newTiledTextureWithBytesNoCopy:(void *)copy length:(unsigned long long)length descriptor:(id)descriptor offset:(unsigned long long)offset bytesPerRow:(unsigned long long)row;
- (id)newTiledTextureWithBytesNoCopy:(void *)copy length:(unsigned long long)length deallocator:(id /* block */)deallocator descriptor:(id)descriptor offset:(unsigned long long)offset bytesPerRow:(unsigned long long)row;
- (void)_addResource:(id)resource;
- (void)_removeResource:(id)resource;
- (id)newEvent;
- (unsigned long long)maxBufferLength;
- (signed char)retainPeerConnection:(id)connection;
- (void)releasePeerConnection:(id)connection;
- (void)kickCleanupQueue;
- (void)updateResourcePoolPurgeability;
- (void)_setDeviceWrapper:(id)wrapper;
- (id)_deviceWrapper;
- (signed char)setResourcesPurgeableState:(id *)state newState:(unsigned long long)state oldState:(unsigned long long *)state count:(int)count;
- (id)newAccelerationStructureWithSize:(unsigned long long)size;
- (id)newAccelerationStructureWithSize:(unsigned long long)size resourceIndex:(unsigned long long)index;
- (id)newAccelerationStructureWithBuffer:(id)buffer offset:(unsigned long long)offset;
- (id)newIntersectionFunctionTableWithDescriptor:(id)descriptor;

@end

#endif /* MTLIOAccelDevice_h */
