//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLIOAccelComputeCommandEncoder_h
#define MTLIOAccelComputeCommandEncoder_h
@import Foundation;

#include "MTLIOAccelCommandEncoder.h"

@interface MTLIOAccelComputeCommandEncoder : MTLIOAccelCommandEncoder

/* instance methods */
- (unsigned long long)getType;
- (void)updateFence:(id)fence;
- (void)waitForFence:(id)fence;
- (id)getComputePipelineState;
- (void *)getBufferContentsAtIndex:(unsigned long long)index;
- (void)bindEmulationArguments;
- (void)useResource:(id)resource usage:(unsigned long long)usage;
- (void)useResources:(const id *)resources count:(unsigned long long)count usage:(unsigned long long)usage;
- (void)useHeap:(id)heap;
- (void)useHeaps:(const id *)heaps count:(unsigned long long)count;
- (void)setEmulationBuffers:(const id *)buffers offsets:(const unsigned long long *)offsets withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)setEmulationTextures:(const id *)textures withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)setEmulationSamplerStates:(const id *)states withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)memoryBarrierWithScope:(unsigned long long)scope;
- (void)memoryBarrierWithResources:(const id *)resources count:(unsigned long long)count;
- (void)executeCommandsInBuffer:(id)buffer withRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)executeCommandsInBuffer:(id)buffer indirectBuffer:(id)buffer indirectBufferOffset:(unsigned long long)offset;
- (void)sampleCountersInBuffer:(id)buffer atSampleIndex:(unsigned long long)index withBarrier:(signed char)barrier;
- (void)setVisibleFunctionTable:(id)table atBufferIndex:(unsigned long long)index;
- (void)setVisibleFunctionTables:(const id *)tables withBufferRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)setIntersectionFunctionTable:(id)table atBufferIndex:(unsigned long long)index;
- (void)setIntersectionFunctionTables:(const id *)tables withBufferRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;

@end

#endif /* MTLIOAccelComputeCommandEncoder_h */
