//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLIOAccelIndirectCommandBuffer_h
#define MTLIOAccelIndirectCommandBuffer_h
@import Foundation;

#include "MTLIOAccelBuffer.h"
#include "MTLIOAccelResource.h"
#include "MTLIndirectCommandBufferDescriptor.h"

@protocol MTLIndirectComputeCommandEncoder, MTLIndirectRenderCommandEncoder;

@interface MTLIOAccelIndirectCommandBuffer : MTLIOAccelResource {
    /* instance variables */
    unsigned long long _maxCommandCount;
    id <MTLIndirectComputeCommandEncoder> _privateIndirectComputeEncoder;
    id <MTLIndirectRenderCommandEncoder> _privateIndirectRenderEncoder;
    struct MTLIndirectCommandBufferHeader { unsigned long long headerSize; unsigned int commandTypes; signed char inheritPipelineState; signed char inheritBuffers; unsigned char maxVertexBufferBindCount; unsigned char maxFragmentBufferBindCount; unsigned char maxKernelBufferBindCount; unsigned long long size; } _internalHeader;
}

@property (readonly) MTLIOAccelBuffer *privateICBuffer;
@property (readonly) unsigned long long commandBufferType;
@property (readonly) MTLIndirectCommandBufferDescriptor *descriptor;
@property (readonly) unsigned long long storageMode;
@property (readonly) unsigned long long size;

/* instance methods */
- (id)initWithBuffer:(id)buffer descriptor:(id)descriptor maxCommandCount:(unsigned long long)count;
- (void)getHeader:(void * *)header headerSize:(unsigned long long *)size;
- (id)indirectRenderCommandAtIndex:(unsigned long long)index;
- (id)indirectComputeCommandAtIndex:(unsigned long long)index;
- (void)resetWithRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })range;
- (void)dealloc;
- (unsigned long long)uniqueIdentifier;
- (signed char)isAliasable;
- (void)makeAliasable;
- (unsigned long long)setPurgeableState:(unsigned long long)state;
- (signed char)doesAliasAllResources:(const id *)resources count:(unsigned long long)count;
- (signed char)doesAliasAnyResources:(const id *)resources count:(unsigned long long)count;
- (signed char)doesAliasResource:(id)resource;
- (signed char)isComplete;
- (void)waitUntilComplete;
- (signed char)isWriteComplete;

@end

#endif /* MTLIOAccelIndirectCommandBuffer_h */
