//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLLinkedFunctions_h
#define MTLLinkedFunctions_h
@import Foundation;

#include "NSCopying-Protocol.h"

@class NSArray, NSDictionary, NSObject;

@interface MTLLinkedFunctions : NSObject <NSCopying>

@property (copy, nonatomic) NSArray *functions;
@property (copy, nonatomic) NSArray *binaryFunctions;
@property (copy, nonatomic) NSDictionary *groups;
@property (copy, nonatomic) NSArray *privateFunctions;

/* class methods */
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;
+ (id)linkedFunctions;

/* instance methods */
- (void)reset;
- (id)copyWithZone:(struct _NSZone *)zone;

@end

#endif /* MTLLinkedFunctions_h */
