//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLLinkedFunctionsInternal_h
#define MTLLinkedFunctionsInternal_h
@import Foundation;

#include "MTLLinkedFunctions.h"

@class NSArray, NSDictionary;

@interface MTLLinkedFunctionsInternal : MTLLinkedFunctions {
    /* instance variables */
    struct MTLLinkedFunctionsPrivate { NSArray *functions; NSArray *privateFunctions; NSArray *binaryFunctions; NSDictionary *groups; } _private;
}

/* class methods */
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)dealloc;
- (id)functions;
- (void)setFunctions:(id)functions;
- (id)privateFunctions;
- (void)setPrivateFunctions:(id)functions;
- (id)binaryFunctions;
- (void)setBinaryFunctions:(id)functions;
- (id)groups;
- (void)setGroups:(id)groups;
- (_Bool)isEmpty;
- (unsigned long long)hash;
- (signed char)isEqual:(id)equal;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;

@end

#endif /* MTLLinkedFunctionsInternal_h */
