//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLMotionEstimatorCapabilities_h
#define MTLMotionEstimatorCapabilities_h
@import Foundation;

#include "NSCopying-Protocol.h"

@class NSObject;

@interface MTLMotionEstimatorCapabilities : NSObject <NSCopying>

@property (readonly, nonatomic) unsigned long long minTextureWidth;
@property (readonly, nonatomic) unsigned long long maxTextureWidth;
@property (readonly, nonatomic) unsigned long long minTextureHeight;
@property (readonly, nonatomic) unsigned long long maxTextureHeight;
@property (readonly, nonatomic) unsigned long long macroBlockWidth;
@property (readonly, nonatomic) unsigned long long macroBlockHeight;
@property (readonly, nonatomic) unsigned long long regionWidth;
@property (readonly, nonatomic) unsigned long long regionHeight;
@property (readonly, nonatomic) unsigned long long precisionNumerator;
@property (readonly, nonatomic) unsigned long long precisionDenominator;

/* class methods */
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;

@end

#endif /* MTLMotionEstimatorCapabilities_h */
