//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLMotionEstimationPipelineDescriptorInternal_h
#define MTLMotionEstimationPipelineDescriptorInternal_h
@import Foundation;

#include "MTLMotionEstimationPipelineDescriptor.h"

@interface MTLMotionEstimationPipelineDescriptorInternal : MTLMotionEstimationPipelineDescriptor {
    /* instance variables */
    struct MTLMotionEstimationPipelineDescriptorPrivate { unsigned long long textureWidth; unsigned long long textureHeight; } _private;
}

/* instance methods */
- (unsigned long long)textureWidth;
- (void)setTextureWidth:(unsigned long long)width;
- (unsigned long long)textureHeight;
- (void)setTextureHeight:(unsigned long long)height;
- (struct MTLMotionEstimationPipelineDescriptorPrivate { unsigned long long x0; unsigned long long x1; } *)descriptorPrivate;
- (signed char)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;

@end

#endif /* MTLMotionEstimationPipelineDescriptorInternal_h */
