//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLMotionKeyframeData_h
#define MTLMotionKeyframeData_h
@import Foundation;

#include "MTLBuffer-Protocol.h"

@class NSObject;

@interface MTLMotionKeyframeData : NSObject

@property (retain, nonatomic) id <MTLBuffer> buffer;
@property (nonatomic) unsigned long long offset;

/* class methods */
+ (id)data;

/* instance methods */
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)zone;
- (signed char)isEqual:(id)equal;
- (unsigned long long)hash;

@end

#endif /* MTLMotionKeyframeData_h */
