//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLProgramAddressTableMappedBinary_Protocol_h
#define MTLProgramAddressTableMappedBinary_Protocol_h
@import Foundation;

@class NSString;

@protocol MTLProgramAddressTableMappedBinary

@required

@property (readonly) unsigned long long mappedAddress;
@property (readonly) unsigned long long mappedSize;
@property (readonly) unsigned long long binaryUniqueId;
@property (readonly) NSString *type;

@optional

@end

#endif /* MTLProgramAddressTableMappedBinary_Protocol_h */
