//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLPostVertexDumpOutput_h
#define MTLPostVertexDumpOutput_h
@import Foundation;

@class NSObject, NSString;

@interface MTLPostVertexDumpOutput : NSObject

@property (readonly) NSString *airMDType;
@property (readonly) unsigned long long dataType;
@property (readonly) unsigned long long pixelFormat;
@property (readonly) unsigned long long aluType;
@property (readonly) NSString *name;
@property (readonly) unsigned long long offset;

/* instance methods */
- (id)initWithAirMDType:(id)mdtype dataType:(unsigned long long)type pixelFormat:(unsigned long long)format aluType:(unsigned long long)type name:(id)name offset:(unsigned long long)offset;
- (void)dealloc;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;

@end

#endif /* MTLPostVertexDumpOutput_h */
