//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLPipelineBufferDescriptorInternal_h
#define MTLPipelineBufferDescriptorInternal_h
@import Foundation;

#include "MTLPipelineBufferDescriptor.h"

@interface MTLPipelineBufferDescriptorInternal : MTLPipelineBufferDescriptor {
    /* instance variables */
    struct MTLPipelineBufferDescriptorPrivate { union { struct { unsigned int mutability:2; } x0; struct { unsigned long long bits; } x1; } x0; } _private;
}

/* instance methods */
- (id)init;
- (void)dealloc;
- (signed char)isEqual:(id)equal;
- (signed char)isDefault;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;
- (unsigned long long)mutability;
- (void)setMutability:(unsigned long long)mutability;
- (const struct MTLPipelineBufferDescriptorPrivate { union { struct { unsigned int x0:2; } x0; struct { unsigned long long x0; } x1; } x0; } *)_descriptorPrivate;

@end

#endif /* MTLPipelineBufferDescriptorInternal_h */
