//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLRenderPassColorAttachmentDescriptor_h
#define MTLRenderPassColorAttachmentDescriptor_h
@import Foundation;

#include "MTLRenderPassAttachmentDescriptor.h"

@interface MTLRenderPassColorAttachmentDescriptor : MTLRenderPassAttachmentDescriptor

@property (nonatomic) struct { double x0; double x1; double x2; double x3; } clearColor;

/* class methods */
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;

@end

#endif /* MTLRenderPassColorAttachmentDescriptor_h */
