//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLResourceList_h
#define MTLResourceList_h
@import Foundation;

#include "MTLResourceListPool.h"

@class NSObject;

@interface MTLResourceList : NSObject {
    /* instance variables */
    struct { int chunkEntryCapacity; struct MTLResourceListChunk { int currentEntry; void * *entries; struct MTLResourceListChunk *nextChunk; } currentChunk; MTLResourceListPool *pool; struct { MTLResourceList *tqe_next; id *tqe_prev; } entry; unsigned long long time_added; } _listPriv;
}

/* instance methods */
- (id)initWithCapacity:(int)capacity;
- (void)releaseAllObjectsAndReset;
- (void)dealloc;

@end

#endif /* MTLResourceList_h */
