//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLRenderPipelineDescriptor_h
#define MTLRenderPipelineDescriptor_h
@import Foundation;

#include "MTLFunction-Protocol.h"
#include "MTLLinkedFunctions.h"
#include "MTLPipelineBufferDescriptorArray.h"
#include "MTLRenderPipelineColorAttachmentDescriptorArray.h"
#include "MTLVertexDescriptor.h"
#include "NSCopying-Protocol.h"

@class NSArray, NSObject, NSString;

@interface MTLRenderPipelineDescriptor : NSObject <NSCopying>

@property (copy, nonatomic) NSString *label;
@property (retain, nonatomic) id <MTLFunction> vertexFunction;
@property (retain, nonatomic) id <MTLFunction> fragmentFunction;
@property (copy, nonatomic) MTLVertexDescriptor *vertexDescriptor;
@property (nonatomic) unsigned long long sampleCount;
@property (nonatomic) unsigned long long rasterSampleCount;
@property (nonatomic) signed char alphaToCoverageEnabled;
@property (nonatomic) signed char alphaToOneEnabled;
@property (nonatomic) signed char rasterizationEnabled;
@property (nonatomic) unsigned long long maxVertexAmplificationCount;
@property (readonly) MTLRenderPipelineColorAttachmentDescriptorArray *colorAttachments;
@property (nonatomic) unsigned long long depthAttachmentPixelFormat;
@property (nonatomic) unsigned long long stencilAttachmentPixelFormat;
@property (nonatomic) unsigned long long inputPrimitiveTopology;
@property (nonatomic) unsigned long long tessellationPartitionMode;
@property (nonatomic) unsigned long long maxTessellationFactor;
@property (nonatomic) signed char tessellationFactorScaleEnabled;
@property (nonatomic) unsigned long long tessellationFactorFormat;
@property (nonatomic) unsigned long long tessellationControlPointIndexType;
@property (nonatomic) unsigned long long tessellationFactorStepFunction;
@property (nonatomic) unsigned long long tessellationOutputWindingOrder;
@property (readonly) MTLPipelineBufferDescriptorArray *vertexBuffers;
@property (readonly) MTLPipelineBufferDescriptorArray *fragmentBuffers;
@property (nonatomic) signed char supportIndirectCommandBuffers;
@property (copy, nonatomic) NSArray *binaryArchives;
@property (copy, nonatomic) NSArray *vertexPreloadedLibraries;
@property (copy, nonatomic) NSArray *fragmentPreloadedLibraries;
@property (copy, nonatomic) MTLLinkedFunctions *vertexLinkedFunctions;
@property (copy, nonatomic) MTLLinkedFunctions *fragmentLinkedFunctions;
@property (nonatomic) signed char supportAddingVertexBinaryFunctions;
@property (nonatomic) signed char supportAddingFragmentBinaryFunctions;
@property (nonatomic) unsigned long long maxVertexCallStackDepth;
@property (nonatomic) unsigned long long maxFragmentCallStackDepth;

/* class methods */
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;

/* instance methods */
- (void)reset;
- (id)copyWithZone:(struct _NSZone *)zone;

@end

#endif /* MTLRenderPipelineDescriptor_h */
