//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLRenderPassDescriptor_h
#define MTLRenderPassDescriptor_h
@import Foundation;

#include "MTLBuffer-Protocol.h"
#include "MTLRasterizationRateMap-Protocol.h"
#include "MTLRenderPassColorAttachmentDescriptorArray.h"
#include "MTLRenderPassDepthAttachmentDescriptor.h"
#include "MTLRenderPassSampleBufferAttachmentDescriptorArray.h"
#include "MTLRenderPassStencilAttachmentDescriptor.h"
#include "NSCopying-Protocol.h"

@class NSObject;

@interface MTLRenderPassDescriptor : NSObject <NSCopying>

@property (readonly) MTLRenderPassColorAttachmentDescriptorArray *colorAttachments;
@property (copy, nonatomic) MTLRenderPassDepthAttachmentDescriptor *depthAttachment;
@property (copy, nonatomic) MTLRenderPassStencilAttachmentDescriptor *stencilAttachment;
@property (retain, nonatomic) id <MTLBuffer> visibilityResultBuffer;
@property (nonatomic) unsigned long long renderTargetArrayLength;
@property (nonatomic) unsigned long long imageblockSampleLength;
@property (nonatomic) unsigned long long threadgroupMemoryLength;
@property (nonatomic) unsigned long long tileWidth;
@property (nonatomic) unsigned long long tileHeight;
@property (nonatomic) unsigned long long defaultRasterSampleCount;
@property (nonatomic) unsigned long long renderTargetWidth;
@property (nonatomic) unsigned long long renderTargetHeight;
@property (retain, nonatomic) id <MTLRasterizationRateMap> rasterizationRateMap;
@property (readonly) MTLRenderPassSampleBufferAttachmentDescriptorArray *sampleBufferAttachments;

/* class methods */
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;
+ (id)renderPassDescriptor;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)setSamplePositions:(const struct { float x0; float x1; } *)positions count:(unsigned long long)count;
- (unsigned long long)getSamplePositions:(struct { float x0; float x1; } *)positions count:(unsigned long long)count;

@end

#endif /* MTLRenderPassDescriptor_h */
