//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLRenderPassAttachmentDescriptor_h
#define MTLRenderPassAttachmentDescriptor_h
@import Foundation;

#include "MTLTexture-Protocol.h"
#include "NSCopying-Protocol.h"

@class NSObject;

@interface MTLRenderPassAttachmentDescriptor : NSObject <NSCopying>

@property (retain, nonatomic) id <MTLTexture> texture;
@property (nonatomic) unsigned long long level;
@property (nonatomic) unsigned long long slice;
@property (nonatomic) unsigned long long depthPlane;
@property (retain, nonatomic) id <MTLTexture> resolveTexture;
@property (nonatomic) unsigned long long resolveLevel;
@property (nonatomic) unsigned long long resolveSlice;
@property (nonatomic) unsigned long long resolveDepthPlane;
@property (nonatomic) unsigned long long loadAction;
@property (nonatomic) unsigned long long storeAction;
@property (nonatomic) unsigned long long storeActionOptions;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;

@end

#endif /* MTLRenderPassAttachmentDescriptor_h */
