//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLRasterizationRateLayerDescriptor_h
#define MTLRasterizationRateLayerDescriptor_h
@import Foundation;

#include "MTLRasterizationRateSampleArray.h"
#include "NSCopying-Protocol.h"

@class NSObject;

@interface MTLRasterizationRateLayerDescriptor : NSObject <NSCopying>

@property (nonatomic) struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } sampleCount;
@property (readonly, nonatomic) struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } maxSampleCount;
@property (readonly, nonatomic) float * horizontalSampleStorage;
@property (readonly, nonatomic) float * verticalSampleStorage;
@property (readonly, nonatomic) MTLRasterizationRateSampleArray *horizontal;
@property (readonly, nonatomic) MTLRasterizationRateSampleArray *vertical;

/* class methods */
+ (id)allocWithZone:(struct _NSZone *)zone;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)init;
- (id)initWithSampleCount:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })count;
- (id)initWithSampleCount:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })count horizontal:(const float *)horizontal vertical:(const float *)vertical;

@end

#endif /* MTLRasterizationRateLayerDescriptor_h */
