//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLResourceStatePassDescriptor_h
#define MTLResourceStatePassDescriptor_h
@import Foundation;

#include "MTLResourceStatePassSampleBufferAttachmentDescriptorArray.h"
#include "NSCopying-Protocol.h"

@class NSObject;

@interface MTLResourceStatePassDescriptor : NSObject <NSCopying>

@property (readonly) MTLResourceStatePassSampleBufferAttachmentDescriptorArray *sampleBufferAttachments;

/* class methods */
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;
+ (id)resourceStatePassDescriptor;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;

@end

#endif /* MTLResourceStatePassDescriptor_h */
