//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLRasterizationRateLayerArrayInternal_h
#define MTLRasterizationRateLayerArrayInternal_h
@import Foundation;

#include "MTLRasterizationRateLayerArray.h"
#include "MTLRasterizationRateMapDescriptor.h"

@interface MTLRasterizationRateLayerArrayInternal : MTLRasterizationRateLayerArray {
    /* instance variables */
    MTLRasterizationRateMapDescriptor *_parent;
}

/* instance methods */
- (id)initWithParent:(id)parent;
- (id)objectAtIndexedSubscript:(unsigned long long)subscript;
- (void)setObject:(id)object atIndexedSubscript:(unsigned long long)subscript;

@end

#endif /* MTLRasterizationRateLayerArrayInternal_h */
