//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLSamplerDescriptor_h
#define MTLSamplerDescriptor_h
@import Foundation;

#include "NSCopying-Protocol.h"

@class NSObject, NSString;

@interface MTLSamplerDescriptor : NSObject <NSCopying>

@property (nonatomic) signed char forceResourceIndex;
@property (nonatomic) unsigned long long resourceIndex;
@property (nonatomic) unsigned long long reductionMode;
@property (nonatomic) unsigned long long pixelFormat;
@property (nonatomic) unsigned long long minFilter;
@property (nonatomic) unsigned long long magFilter;
@property (nonatomic) unsigned long long mipFilter;
@property (nonatomic) unsigned long long maxAnisotropy;
@property (nonatomic) unsigned long long sAddressMode;
@property (nonatomic) unsigned long long tAddressMode;
@property (nonatomic) unsigned long long rAddressMode;
@property (nonatomic) unsigned long long borderColor;
@property (nonatomic) signed char normalizedCoordinates;
@property (nonatomic) float lodMinClamp;
@property (nonatomic) float lodMaxClamp;
@property (nonatomic) signed char lodAverage;
@property (nonatomic) unsigned long long compareFunction;
@property (nonatomic) signed char supportArgumentBuffers;
@property (copy, nonatomic) NSString *label;

/* class methods */
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;

@end

#endif /* MTLSamplerDescriptor_h */
