//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLSharedEvent_Protocol_h
#define MTLSharedEvent_Protocol_h
@import Foundation;

#include "MTLEvent-Protocol.h"

@protocol MTLSharedEvent <MTLEvent>

@required

@property unsigned long long signaledValue;

/* required instance methods */
- (void)notifyListener:(id)listener atValue:(unsigned long long)value block:(id /* block */)block;
- (id)newSharedEventHandle;

@optional

@end

#endif /* MTLSharedEvent_Protocol_h */
