//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLSharedEventSPI_Protocol_h
#define MTLSharedEventSPI_Protocol_h
@import Foundation;

#include "MTLSharedEvent-Protocol.h"

@protocol MTLSharedEventSPI <MTLSharedEvent>

@required

/* required instance methods */
- (signed char)waitUntilSignaledValue:(unsigned long long)value timeoutMS:(unsigned long long)ms;

@optional

@end

#endif /* MTLSharedEventSPI_Protocol_h */
