//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLSharedEventHandle_h
#define MTLSharedEventHandle_h
@import Foundation;

#include "NSSecureCoding-Protocol.h"

@class NSObject, NSString;

@interface MTLSharedEventHandle : NSObject <NSSecureCoding> {
    /* instance variables */
    struct MTLSharedEventHandlePrivate { unsigned int x0; id x1; unsigned long long x2; } * _priv;
}

@property (readonly) NSString *label;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (unsigned int)eventPort;
- (unsigned long long)labelTraceID;
- (id)initWithSharedEvent:(id)event;
- (void)dealloc;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;

@end

#endif /* MTLSharedEventHandle_h */
