//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLTileRenderPipelineDescriptor_h
#define MTLTileRenderPipelineDescriptor_h
@import Foundation;

#include "MTLFunction-Protocol.h"
#include "MTLLinkedFunctions.h"
#include "MTLPipelineBufferDescriptorArray.h"
#include "MTLTileRenderPipelineColorAttachmentDescriptorArray.h"
#include "NSCopying-Protocol.h"

@class NSArray, NSObject, NSString;

@interface MTLTileRenderPipelineDescriptor : NSObject <NSCopying>

@property (copy, nonatomic) NSString *label;
@property (retain, nonatomic) id <MTLFunction> tileFunction;
@property (nonatomic) unsigned long long rasterSampleCount;
@property (readonly) MTLTileRenderPipelineColorAttachmentDescriptorArray *colorAttachments;
@property (nonatomic) signed char threadgroupSizeMatchesTileSize;
@property (readonly) MTLPipelineBufferDescriptorArray *tileBuffers;
@property (nonatomic) unsigned long long maxTotalThreadsPerThreadgroup;
@property (copy, nonatomic) NSArray *binaryArchives;
@property (copy, nonatomic) NSArray *preloadedLibraries;
@property (copy, nonatomic) MTLLinkedFunctions *linkedFunctions;
@property (nonatomic) signed char supportAddingBinaryFunctions;
@property (nonatomic) unsigned long long maxCallStackDepth;

/* class methods */
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;

/* instance methods */
- (void)reset;
- (id)copyWithZone:(struct _NSZone *)zone;

@end

#endif /* MTLTileRenderPipelineDescriptor_h */
