//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLTileRenderPipelineDescriptorInternal_h
#define MTLTileRenderPipelineDescriptorInternal_h
@import Foundation;

#include "MTLFunction-Protocol.h"
#include "MTLLinkedFunctions.h"
#include "MTLPipelineBufferDescriptorArrayInternal.h"
#include "MTLTileRenderPipelineColorAttachmentDescriptorArrayInternal.h"
#include "MTLTileRenderPipelineDescriptor.h"

@class NSArray, NSDictionary, NSString;

@interface MTLTileRenderPipelineDescriptorInternal : MTLTileRenderPipelineDescriptor {
    /* instance variables */
    struct MTLTileRenderPipelineDescriptorPrivate { MTLTileRenderPipelineColorAttachmentDescriptorArrayInternal *attachments; union { unsigned long long sampleCount; unsigned long long rasterSampleCount; } x1; NSString *label; <MTLFunction> *tileFunction; _Bool threadgroupSizeMatchesTileSize; unsigned long long paddingToRemove; unsigned long long colorSampleCount; MTLPipelineBufferDescriptorArrayInternal *tileBuffers; unsigned short maxTotalThreadsPerThreadgroup; long long textureWriteRoundingMode; NSDictionary *pluginData; NSArray *binaryArchives; MTLLinkedFunctions *linkedFunctions; NSArray *preloadedLibraries; unsigned long long maxStackCallDepth; signed char supportAddingBinaryFunctions; } _private;
}

/* instance methods */
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;
- (unsigned long long)sampleCount;
- (void)setSampleCount:(unsigned long long)count;
- (unsigned long long)rasterSampleCount;
- (void)setRasterSampleCount:(unsigned long long)count;
- (id)pluginData;
- (void)setPluginData:(id)data;
- (unsigned long long)colorSampleCount;
- (void)setColorSampleCount:(unsigned long long)count;
- (id)tileBuffers;
- (void)reset;
- (id)label;
- (void)setLabel:(id)label;
- (void)setTileFunction:(id)function;
- (id)tileFunction;
- (void)setThreadgroupSizeMatchesTileSize:(signed char)size;
- (signed char)threadgroupSizeMatchesTileSize;
- (const struct MTLTileRenderPipelineDescriptorPrivate { id x0; union { unsigned long long x0; unsigned long long x1; } x1; id x2; id x3; _Bool x4; unsigned long long x5; unsigned long long x6; id x7; unsigned short x8; long long x9; id x10; id x11; id x12; id x13; unsigned long long x14; signed char x15; } *)_descriptorPrivate;
- (void)setMaxTotalThreadsPerThreadgroup:(unsigned long long)threadgroup;
- (unsigned long long)maxTotalThreadsPerThreadgroup;
- (void)setTextureWriteRoundingMode:(long long)mode;
- (long long)textureWriteRoundingMode;
- (void)setBinaryArchives:(id)archives;
- (id)binaryArchives;
- (id)linkedFunctions;
- (void)setLinkedFunctions:(id)functions;
- (id)preloadedLibraries;
- (void)setPreloadedLibraries:(id)libraries;
- (id)insertLibraries;
- (void)setInsertLibraries:(id)libraries;
- (signed char)supportAddingBinaryFunctions;
- (void)setSupportAddingBinaryFunctions:(signed char)functions;
- (unsigned long long)maxCallStackDepth;
- (void)setMaxCallStackDepth:(unsigned long long)depth;
- (unsigned long long)hash;
- (signed char)isEqual:(id)equal;
- (id)colorAttachments;
- (signed char)validateWithDevice:(id)device error:(id *)error;
- (void)validateWithDevice:(id)device;
- (id)newSerializedTileDataWithFlags:(unsigned long long)flags options:(unsigned long long)options error:(id *)error;

@end

#endif /* MTLTileRenderPipelineDescriptorInternal_h */
