//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLTypeInternal_h
#define MTLTypeInternal_h
@import Foundation;

#include "MTLType.h"

@interface MTLTypeInternal : MTLType {
    /* instance variables */
    unsigned long long _dataType;
}

/* instance methods */
- (id)initWithDataType:(unsigned long long)type;
- (void)dealloc;
- (unsigned long long)dataType;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;

@end

#endif /* MTLTypeInternal_h */
