//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLTextureDescriptor_h
#define MTLTextureDescriptor_h
@import Foundation;

#include "NSCopying-Protocol.h"

@class NSObject;

@interface MTLTextureDescriptor : NSObject <NSCopying>

@property (nonatomic) signed char forceResourceIndex;
@property (nonatomic) unsigned long long resourceIndex;
@property (nonatomic) unsigned long long textureType;
@property (nonatomic) unsigned long long pixelFormat;
@property (nonatomic) unsigned long long width;
@property (nonatomic) unsigned long long height;
@property (nonatomic) unsigned long long depth;
@property (nonatomic) unsigned long long mipmapLevelCount;
@property (nonatomic) unsigned long long sampleCount;
@property (nonatomic) unsigned long long arrayLength;
@property (nonatomic) unsigned long long resourceOptions;
@property (nonatomic) unsigned long long cpuCacheMode;
@property (nonatomic) unsigned long long storageMode;
@property (nonatomic) unsigned long long hazardTrackingMode;
@property (nonatomic) unsigned long long usage;
@property (nonatomic) signed char allowGPUOptimizedContents;
@property (nonatomic) long long compressionType;
@property (nonatomic) struct { unsigned char x0; unsigned char x1; unsigned char x2; unsigned char x3; } swizzle;

/* class methods */
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;
+ (id)texture2DDescriptorWithPixelFormat:(unsigned long long)format width:(unsigned long long)width height:(unsigned long long)height mipmapped:(signed char)mipmapped;
+ (id)textureCubeDescriptorWithPixelFormat:(unsigned long long)format size:(unsigned long long)size mipmapped:(signed char)mipmapped;
+ (id)textureBufferDescriptorWithPixelFormat:(unsigned long long)format width:(unsigned long long)width resourceOptions:(unsigned long long)options usage:(unsigned long long)usage;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;

@end

#endif /* MTLTextureDescriptor_h */
