//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLVertexDescriptor_h
#define MTLVertexDescriptor_h
@import Foundation;

#include "MTLVertexAttributeDescriptorArray.h"
#include "MTLVertexBufferLayoutDescriptorArray.h"
#include "NSCopying-Protocol.h"

@class NSObject;

@interface MTLVertexDescriptor : NSObject <NSCopying>

@property (readonly) MTLVertexBufferLayoutDescriptorArray *layouts;
@property (readonly) MTLVertexAttributeDescriptorArray *attributes;

/* class methods */
+ (id)vertexDescriptor;
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)zone;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)reset;
- (id)formattedDescription:(unsigned long long)description;

@end

#endif /* MTLVertexDescriptor_h */
