//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 12.7, SDK: 12.7, Tool: ld (760)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 15.7, SDK: 15.7, Tool: ld (760)
//    - LC_SOURCE_VERSION: 263.9.0.0.0
//
#ifndef MTLVertexDescriptorInternal_h
#define MTLVertexDescriptorInternal_h
@import Foundation;

#include "MTLVertexAttributeDescriptorArrayInternal.h"
#include "MTLVertexBufferLayoutDescriptorArrayInternal.h"
#include "MTLVertexDescriptor.h"

@interface MTLVertexDescriptorInternal : MTLVertexDescriptor {
    /* instance variables */
    MTLVertexBufferLayoutDescriptorArrayInternal *_vertexBufferArray;
    MTLVertexAttributeDescriptorArrayInternal *_attributeArray;
}

/* class methods */
+ (id)vertexDescriptor;

/* instance methods */
- (id)init;
- (id)layouts;
- (id)attributes;
- (void)dealloc;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;
- (void)reset;
- (id)copyWithZone:(struct _NSZone *)zone;
- (unsigned long long)hash;
- (signed char)isEqual:(id)equal;
- (id)newSerializedDescriptor;
- (signed char)validateWithVertexFunction:(id)function error:(id *)error renderPipelineDescriptor:(id)descriptor;

@end

#endif /* MTLVertexDescriptorInternal_h */
