//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_SOURCE_VERSION: 370.57.0.0.0
//
#ifndef MTL4MachineLearningPipelineState_Protocol_h
#define MTL4MachineLearningPipelineState_Protocol_h
@import Foundation;

#include "MTL4MachineLearningPipelineReflection.h"
#include "MTLAllocation-Protocol.h"
#include "MTLDevice-Protocol.h"
#include "NSObject-Protocol.h"

@class NSString;

@protocol MTL4MachineLearningPipelineState <MTLAllocation, NSObject>

@required

@property (readonly) NSString *label;
@property (readonly) id <MTLDevice> device;
@property (readonly) MTL4MachineLearningPipelineReflection *reflection;
@property (readonly) unsigned long long intermediatesHeapSize;

@optional

@end

#endif /* MTL4MachineLearningPipelineState_Protocol_h */
