//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_SOURCE_VERSION: 370.57.0.0.0
//
#ifndef MTL4MachineLearningPipelineStateGGDSPI_Protocol_h
#define MTL4MachineLearningPipelineStateGGDSPI_Protocol_h
@import Foundation;

#include "MTL4MachineLearningPipelineStateSPI-Protocol.h"

@protocol MTL4MachineLearningPipelineStateGGDSPI <MTL4MachineLearningPipelineStateSPI>

@required

/* required instance methods */
- (id)optimizedBytecode;
- (id)resourceBlobForByteCodeSignature:(id)signature resourceName:(id)name error:(id *)error;
- (id)runWithInputsArray:(id)array resultsArray:(id)array intermediateOperations:(id)operations;

@optional

@end

#endif /* MTL4MachineLearningPipelineStateGGDSPI_Protocol_h */
