//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_SOURCE_VERSION: 370.57.0.0.0
//
#ifndef MTLArgumentDescriptorInternal_h
#define MTLArgumentDescriptorInternal_h
@import Foundation;

@interface MTLArgumentDescriptorInternal :  {
    /* instance variables */
    struct MTLArgumentDescriptorPrivate { unsigned long long dataType; unsigned long long index; unsigned long long arrayLength; unsigned long long access; unsigned long long textureType; unsigned long long constantBlockAlignment; } _private;
}

/* class methods */
+ (id)indirectArgumentDescriptor;

/* instance methods */
- (id)init;
- (id)copyWithZone:(struct _NSZone *)zone;
- (signed char)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)formattedDescription:(unsigned long long)description;
- (id)description;
- (unsigned long long)dataType;
- (void)setDataType:(unsigned long long)type;
- (unsigned long long)index;
- (void)setIndex:(unsigned long long)index;
- (unsigned long long)arrayLength;
- (void)setArrayLength:(unsigned long long)length;
- (unsigned long long)access;
- (void)setAccess:(unsigned long long)access;
- (unsigned long long)textureType;
- (void)setTextureType:(unsigned long long)type;
- (unsigned long long)constantBlockAlignment;
- (void)setConstantBlockAlignment:(unsigned long long)alignment;

@end

#endif /* MTLArgumentDescriptorInternal_h */
