//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_SOURCE_VERSION: 370.57.0.0.0
//
#ifndef MTLDynamicLibrarySPI_Protocol_h
#define MTLDynamicLibrarySPI_Protocol_h
@import Foundation;

#include "MTLDebugInstrumentationData.h"
#include "MTLDynamicLibrary-Protocol.h"

@class NSArray, NSObject, NSString;
@protocol OS_dispatch_data;

@protocol MTLDynamicLibrarySPI <MTLDynamicLibrary>

@required

@property (readonly) NSObject<OS_dispatch_data> *binaryData;
@property (readonly) NSObject<OS_dispatch_data> *reflectionData;
@property (readonly) NSArray *exportedFunctions;
@property (readonly) NSArray *exportedVariables;
@property (readonly) NSArray *importedSymbols;
@property (readonly) NSArray *importedLibraries;
@property (readonly) NSString *libraryPath;
@property (readonly) const struct { unsigned char x0[32]; } * libraryUUID;
@property (copy, nonatomic) NSArray *relocations;
@property (retain, nonatomic) MTLDebugInstrumentationData *debugInstrumentationData;
@property (readonly, nonatomic) signed char shaderValidationEnabled;

/* required instance methods */
- (signed char)serializeToURL:(id)url options:(unsigned long long)options error:(id *)error;
- (id)formattedDescription:(unsigned long long)description;

@optional

@end

#endif /* MTLDynamicLibrarySPI_Protocol_h */
