//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_SOURCE_VERSION: 370.57.0.0.0
//
#ifndef MTLDynamicLibrary_Protocol_h
#define MTLDynamicLibrary_Protocol_h
@import Foundation;

#include "MTLDevice-Protocol.h"
#include "NSObject-Protocol.h"

@class NSString;

@protocol MTLDynamicLibrary <NSObject>

@required

@property (copy) NSString *label;
@property (readonly) id <MTLDevice> device;
@property (readonly) NSString *installName;

/* required instance methods */
- (signed char)serializeToURL:(id)url error:(id *)error;

@optional

@end

#endif /* MTLDynamicLibrary_Protocol_h */
