//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_SOURCE_VERSION: 370.57.0.0.0
//
#ifndef MTLIndirectComputeCommand_Protocol_h
#define MTLIndirectComputeCommand_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@protocol MTLIndirectComputeCommand <NSObject>

@required

/* required instance methods */
- (void)setComputePipelineState:(id)state;
- (void)setKernelBuffer:(id)buffer offset:(unsigned long long)offset atIndex:(unsigned long long)index;
- (void)setKernelBuffer:(id)buffer offset:(unsigned long long)offset attributeStride:(unsigned long long)stride atIndex:(unsigned long long)index;
- (void)concurrentDispatchThreadgroups:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroups threadsPerThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup;
- (void)concurrentDispatchThreads:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threads threadsPerThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup;
- (void)setBarrier;
- (void)clearBarrier;
- (void)setImageblockWidth:(unsigned long long)width height:(unsigned long long)height;
- (void)reset;
- (void)setThreadgroupMemoryLength:(unsigned long long)length atIndex:(unsigned long long)index;
- (void)setStageInRegion:(struct { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x0; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; } x1; })region;

@optional

@end

#endif /* MTLIndirectComputeCommand_Protocol_h */
