//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_SOURCE_VERSION: 370.57.0.0.0
//
#ifndef MTLIndirectRenderCommandSPI_Protocol_h
#define MTLIndirectRenderCommandSPI_Protocol_h
@import Foundation;

#include "MTLIndirectRenderCommand-Protocol.h"

@protocol MTLIndirectRenderCommandSPI <MTLIndirectRenderCommand>

@required

/* required instance methods */
- (void *)getVertexBufferAtIndex:(unsigned long long)index;
- (void *)getFragmentBufferAtIndex:(unsigned long long)index;
- (unsigned long long)getVertexAttributeStrideAtIndex:(unsigned long long)index;
- (unsigned long long)getVertexBufferAddressAtIndex:(unsigned long long)index;
- (unsigned long long)getFragmentBufferAddressAtIndex:(unsigned long long)index;
- (unsigned long long)getObjectBufferAddressAtIndex:(unsigned long long)index;
- (unsigned long long)getMeshBufferAddressAtIndex:(unsigned long long)index;
- (unsigned long long)getCommandType;
- (id)drawArguments;
- (id)drawIndexedArguments;
- (id)drawPatchesArguments;
- (id)drawIndexedPatchesArguments;
- (id)getTessellationFactorArguments;
- (id)drawMeshThreadgroupsArguments;
- (id)drawMeshThreadsArguments;
- (void)setObjectBuffer:(id)buffer offset:(unsigned long long)offset atIndex:(unsigned long long)index;
- (void)setMeshBuffer:(id)buffer offset:(unsigned long long)offset atIndex:(unsigned long long)index;
- (void)setBarrier;
- (void)clearBarrier;
- (signed char)hasBarrier;
- (void)drawMeshThreadgroups:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroups threadsPerObjectThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup threadsPerMeshThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup;
- (void)drawMeshThreads:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threads threadsPerObjectThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup threadsPerMeshThreadgroup:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; })threadgroup;
- (unsigned long long)getObjectThreadgroupMemoryLengthAtIndex:(unsigned long long)index;
- (unsigned long long)getOptimizedStatus;
- (unsigned long long)getPipelineStateUniqueIdentifier;

@optional

@end

#endif /* MTLIndirectRenderCommandSPI_Protocol_h */
