//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_SOURCE_VERSION: 370.57.0.0.0
//
#ifndef MTLIOAccelService_h
#define MTLIOAccelService_h
@import Foundation;

#include "MTLDeviceSPI-Protocol.h"
#include "MTLIOAccelDevice.h"

@class NSObject;

@interface MTLIOAccelService : NSObject {
    /* instance variables */
    struct IONotificationPort * _notifyPort;
    unsigned int _notifyObject;
    MTLIOAccelDevice<MTLDeviceSPI> *_weakDevice;
    Class _deviceClass;
}

@property (readonly) unsigned int acceleratorPort;
@property (readonly) unsigned long long registryID;

/* instance methods */
- (id)initWithAcceleratorPort:(unsigned int)port deviceClass:(Class)_class;
- (id)weakDevice;
- (void)_safeEjectRequested;
- (void)_safeEjectCancelled;
- (void)_wasTerminated;
- (void)dealloc;

@end

#endif /* MTLIOAccelService_h */
