//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_SOURCE_VERSION: 370.57.0.0.0
//
#ifndef MTLLoadedFileContentsWrapper_h
#define MTLLoadedFileContentsWrapper_h
@import Foundation;

@class NSData, NSObject;
@protocol OS_dispatch_data;

@interface MTLLoadedFileContentsWrapper : NSObject

@property (readonly, nonatomic) NSData *sourceContents;
@property (readonly, nonatomic) NSObject<OS_dispatch_data> *dispatchData;
@property (readonly, nonatomic) const void * bytes;
@property (readonly, nonatomic) unsigned long long length;

/* instance methods */
- (id)initWithData:(id)data;
- (void)dealloc;

@end

#endif /* MTLLoadedFileContentsWrapper_h */
