//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_SOURCE_VERSION: 370.57.0.0.0
//
#ifndef MTLSharedEvent_Protocol_h
#define MTLSharedEvent_Protocol_h
@import Foundation;

#include "MTLEvent-Protocol.h"

@protocol MTLSharedEvent <MTLEvent>

@required

@property unsigned long long signaledValue;

/* required instance methods */
- (void)notifyListener:(id)listener atValue:(unsigned long long)value block:(id /* block */)block;
- (id)newSharedEventHandle;
- (signed char)waitUntilSignaledValue:(unsigned long long)value timeoutMS:(unsigned long long)ms;

@optional

@end

#endif /* MTLSharedEvent_Protocol_h */
