//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_SOURCE_VERSION: 370.57.0.0.0
//
#ifndef MTLThreadgroupBinding_Protocol_h
#define MTLThreadgroupBinding_Protocol_h
@import Foundation;

#include "MTLBinding-Protocol.h"

@protocol MTLThreadgroupBinding <MTLBinding>

@required

@property (readonly) unsigned long long threadgroupMemoryAlignment;
@property (readonly) unsigned long long threadgroupMemoryDataSize;

@optional

@end

#endif /* MTLThreadgroupBinding_Protocol_h */
