//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.612, BuildCommit: c73c73f8f119d4f3ef7519c9d2740cfce8d632b9)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 26, SDK: 26, Tool: ld (1220.2)
//    - LC_SOURCE_VERSION: 370.57.0.0.0
//
#ifndef NSCopying_Protocol_h
#define NSCopying_Protocol_h
@import Foundation;

@protocol NSCopying

@required

/* required instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;

@optional

@end

#endif /* NSCopying_Protocol_h */
